### ISSUE TITLE
No longer works and get's your IP blocked?

### ISSUE THREAD

**Issue by kbtbc** [Anorov/cloudflare-scrape#101]
I have a script that uses cfscrape, and starting today, from two different locations, I have been totally blocked by CloudFlare after using the script.  Any help on getting unblocked?

**Comment by Xonshiz** [comment]
I'm using this library as well and it's working just fine. How're you sure that you got blocked? Maybe wait for a day or so and then try again. If you're hitting a website too frequently, CF may temporarily ban your ip.

**Comment by Anorov** [comment]
This does not appear to be an issue with the library, as far as I can tell. Cloudflare may be blocking you because of something else unusual about your requests, or maybe the sites you're trying to make requests to have some kind of detection that is flagging you.
