### ISSUE TITLE
authenticate with login form

### ISSUE THREAD

**Issue by masihfathi** [Anorov/cloudflare-scrape#102]
tnx for your extension.
is it possible to login with login form for example login with "https://github.com/login" form? and then get a page "https://github.com/settings/profile" which need a user to be authenticated? in php the symfony browser kit do this job well but it has problem with site which protected with cloudflare.

**Comment by Xonshiz** [comment]
It should be able to do it. If you can maintain sessions for a connection in PHP, then surely. Check [this comment](https://github.com/Anorov/cloudflare-scrape/issues/100#issuecomment-295520019), the code is in Python though.

**Comment by Anorov** [comment]
See @Xonshiz's answer.
