### ISSUE TITLE
passing an existing session (with proxies that require authentication) to cloudflare-scrape

### ISSUE THREAD

**Issue by sydbarrett** [Anorov/cloudflare-scrape#103]
I am having an issue using an existing session with cloudflare-scrape. 

Code 1 works and goes through the proxy authentication just fine.

_Code 1_
```
s = requests.Session()
s.proxies.update({'http': 'http://username:password@proxy_ip_address:port', 'https': 'https://username:password@proxy_ip_address:port'})
s.trust_env=False;  #this line must be there otherwise auth wont work
res = s.get('http://python.org')
```

I tried passing that session when creating a scrapper as seen in Code 2.
_Code 2_
```
s=requests.Session()
s.proxies.update({'http': 'http://username:password@proxy_ip_address:port', 'https': 'https://username:password@proxy_ip_address:port'})
s.auth = HTTPProxyAuth('username', 'password') 
s.trust_env=False
scraper = cfscrape.create_scraper(sess=s) 
scraper.get('http://python.org').content
```

However, I got the following error, 
```
requests.exceptions.ProxyError: HTTPSConnectionPool(host='python.org', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to prox
y.', error('Tunnel connection failed: 407 Proxy Authentication Required',))).
```

Please note that I would get the same error in Code 1 if I commented out the s.trust_env=False line, which lead me to believe that the _trust_env_ variable is not populated when create_scraper is called. 
My conclusion was correct as you can see blow _trust_env_ was not one of the attributes set by create_scraper.
_original code from create_scraper_
```
 if sess:
        attrs = ["auth", "cert", "cookies", "headers", "hooks", "params", "proxies", "data"]
        for attr in attrs:
                val = getattr(sess, attr, None)
                if val:
                        setattr(scraper, attr, val)
```

I tried to simply add _trust_env_ to the attrs so that create_srcaper would set it but It did not help.
```
 if sess:
        attrs = ["trust_env","auth", "cert", "cookies", "headers", "hooks", "params", "proxies", "data"]
        for attr in attrs:
                val = getattr(sess, attr, None)
                if val:
                        setattr(scraper, attr, val)
```

**Comment by Anorov** [comment]
Try replacing `requests.Session()` with `cfscrape.create_scraper()`.

**Comment by sydbarrett** [comment]
Yep, that worked. However, I am a bit embraced cause that issue/solution was brought up in the README.md usage section. I don't know how I missed that part. Anyway, thanks for your fast feedback.

Cheers,
