### ISSUE TITLE
Tor Proxy With cloudflare-scrape

### ISSUE THREAD

**Issue by PhanDuc** [Anorov/cloudflare-scrape#104]
Hi,

Can you give me instruction how to user Tor with cloudflare-scrape ?

I had some example PhantomJS with Tor but don't know how to use tor with cloudflare-scrape.

 Many thanks for considering my request.

**Comment by Coriou** [comment]
Hey,

From the main readme file:

> get_tokens and get_cookie_string both accept Requests' usual keyword arguments (like get_tokens(url, proxies={"http": "socks5://localhost:9050"})). Please read [Requests' documentation](http://docs.python-requests.org/en/master/api/#requests.Session.request) on request arguments for more information.

The answer to your question is to proxy all requests through Tor before hand, using [Python's Requests](http://docs.python-requests.org/en/master/). From what I can read, Tor provides a Socks5 interface so it should be trivial to do.

**Comment by quant61** [comment]
I found a more clean way to set proxy.
```python
import cfscrape
import json

scraper = cfscrape.create_scraper()
scraper.proxies = {"http": "socks5://127.0.0.1:9050", "https": "socks5://127.0.0.1:9050"}

data = scraper.get("https://httpbin.org/get").content
parsed = json.loads(data)
print(parsed['origin'])
```
