### ISSUE TITLE
Code 404

### ISSUE THREAD

**Issue by cr998** [Anorov/cloudflare-scrape#105]
Sometimes web servers return 404 code from script but never from the browser in the same url, I think that it is possible because the script don´t send user-agent

sorry for my english

**Comment by Anorov** [comment]
The script should always be sending a random legitimate-looking user-agent. Could you please provide an example or packet capture where it isn't? Thanks.

**Comment by Xonshiz** [comment]
Not sure if I'm correct, but check the url for "Spaces". The browsers automatically replaces spaces with "`%20`", while, the script may not do so. That could also be the reason you're getting 404. If some website is checked user-agent and stuff, chances are that you'll get `403`, but not `404`. I may be wrong here though. Just double check your url.

**Comment by cr998** [comment]
Sorry , I have been disconnect from some days , I must to delete 1 character at the end of line "%20"
Thanks for the help
