### ISSUE TITLE
Send data per post

### ISSUE THREAD

**Issue by Danytech** [Anorov/cloudflare-scrape#107]
Hello, how do I send data by the post method by skipping the Cloudflare

**Comment by Xonshiz** [comment]
You can't "Skip" Cloudflare if it's being active on that particular section of the website. But, you can use `cfscrape` in any case, along with `requests`. Hopefully, you could do this in other languages as well, but for python, you could go on about something like this : 

	import cfscrape
	import requests

	sess = requests.session()
	sess.headers = {'user-agent' : 'my experiment'}
	sess = cfscrape.create_scraper(sess)

	# Now, use `sess` as normal request instance.

	connect = sess.post(url, data=payload)

	if connect.status_code == 200:
	    print(connect.content)
	else:
	    print("I couldn't connect")
	    print(connect.status_code)
	    print(connect.content)

This will work just fine.

**Comment by Anorov** [comment]
Please see @Xonshiz's answer.
