### ISSUE TITLE
Run in PHP or tomcat

### ISSUE THREAD

**Issue by Danytech** [Anorov/cloudflare-scrape#108]
I would like to know if I can run this script from php or tomcat, if so I would like to see some example of execution.

**Comment by Xonshiz** [comment]
Yes, you can run this in PHP. I'm not that good at PHP, but you can refer to these Issues for code snippets and move forward from there : 

https://github.com/Anorov/cloudflare-scrape/issues/87

https://github.com/Anorov/cloudflare-scrape/issues/98

**Comment by Anorov** [comment]
Please see @Xonshiz's answer.
