### ISSUE TITLE
Library does not resolve protected emails

### ISSUE THREAD

**Issue by tonimartos** [Anorov/cloudflare-scrape#109]
Hi,

I'm scrapping the website of the parliament of UK, and using the "simple way" to get the source code through the library I'm still retrieving protected emails.

My code:
`url = "http://www.parliament.uk/biographies/commons/paul-blomfield/4058"`
`scraper = cfscrape.create_scraper()`
`print scraper.get(url).content`

The source code I'm getting:
`<a id="ctl00_ctl00_FormContent_SiteSpecificPlaceholder_PageContent_addParliamentaryAddress_rptAddresses_ctl00_hypEmailAddress" href="/cdn-cgi/l/email-protection#7c1d181d11521d1a0e1505151952110c3c0c1d0e10151d11191208520917"><span class="__cf_email__" data-cfemail="6c0d080d01420d0a1e0515050942011c2c1c0d1e00050d01090218421907">[email&#160;protected]</span><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></a>`

Is there anything I'm doing wrong? Perhaps Cloudflare is using new encoding?

Thanks in advance!

**Comment by Xonshiz** [comment]
Trying this, I got text : 

```
import requests
import cfscrape

sess = requests.session()
sess = cfscrape.create_scraper(sess)

content = sess.get('http://www.parliament.uk/biographies/commons/paul-blomfield/4058').text.encode('utf-8')
print(content)
```

**Comment by Xonshiz** [comment]
Instead of `.content`, use `.text.encode('utf-8')` and it should work.

**Comment by tonimartos** [comment]
I keep having the same problem. When you execute this code you are able to see the email address properly in the requested source code? I'm getting the same result:

My code:
`scraper = cfscrape.create_scraper()`
`print scraper.get(response.url).text.encode('utf-8')`
(I also tried with the requesting the session as you suggested first, with the same result)

Source code:
`<p id="ctl00_ctl00_FormContent_SiteSpecificPlaceholder_PageContent_addParliamentaryAddress_rptAddresses_ctl00_pnlEmail" data-generic-id="email-address">
                Email:
            <a id="ctl00_ctl00_FormContent_SiteSpecificPlaceholder_PageContent_addParliamentaryAddress_rptAddresses_ctl00_hypEmailAddress" href="/cdn-cgi/l/email-protection#f49e9b9ada95879c839b86809cda9984b4849586989d9599919a80da819f"><span class="__cf_email__" data-cfemail="ee848180c08f9d8699819c9a86c0839eae9e8f9c82878f838b809ac09b85">[email&#160;protected]</span><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></a>
            </p>`

Thanks again

**Comment by Xonshiz** [comment]
Oh crap, I misread your Issue. I didn't get to check that part.

**Comment by tonimartos** [comment]
Jaja no problem man. Actually, the solution you gave did not make so much sense for the problem I got, but I tried requesting the session just in case it would make the difference. Let me know if you make any advance.

Thank you!

**Comment by Anorov** [comment]
This is intentional behavior. I'm aware there are some non-spam reasons to desire this, but I do not want to potentially aid spammers.
