### ISSUE TITLE
run to scrape CF protected website, return 500 internal error

### ISSUE THREAD

**Issue by mphz** [Anorov/cloudflare-scrape#110]
<html><head><title>500 Internal Server Error</title></head><body bgcolor=white><h1>500 Internal Server Error</h1><p>The server encountered an internal error and was unable to complete your request.</p></body></html>\n'

**Comment by Xonshiz** [comment]
Probably it would be better if you could share the URL you're trying to work with?

**Comment by Anorov** [comment]
This does not appear to be related to cloudflare-scrape. If you believe it is, please re-open the issue and follow the instructions at https://github.com/Anorov/cloudflare-scrape#updates
