### ISSUE TITLE
Bug on Kali2.0

### ISSUE THREAD

**Issue by AnonBinarySecurity** [Anorov/cloudflare-scrape#113]
It will not collect a cookie from a IUAM Browser page but will collect a cookie if the mode is lower than such.

**Comment by Anorov** [comment]
Which cookie are you referring to? cf_clearance or __cfduid? And have you replicated the behavior for multiple websites, when those same websites work on a different operating system?

**Comment by AnonBinarySecurity** [comment]
cf clearance seems to be the problem. And yes, tested on multiple websites. The same websites work on a different operating system I.E Ubuntu.

**Comment by Anorov** [comment]
Sorry, I don't have a Kali environment to test on. Could you make sure it's running the latest version of node.js? And is it possible Cloudflare is detecting and blocking some fingerprint left by Kali (which would make sense for IUAM to block)?

**Comment by Anorov** [comment]
Closing this issue at this time. Please re-open if you have more updates.
