### ISSUE TITLE
ValueError: Unable to parse Cloudflare anti-bots page

### ISSUE THREAD

**Issue by celord** [Anorov/cloudflare-scrape#115]
Hi, I hope I'm reporting this the righ way:

import cfscrape

scraper = cfscrape.create_scraper()
m=  scraper.get('https://www.pelispedia.tv/pelicula/spider-man-homecoming/')
scraper.solve_cf_challenge(m)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-32-06b6bc6fa60c> in <module>()
      3 scraper = cfscrape.create_scraper()
      4 m=  scraper.get('https://www.pelispedia.tv/pelicula/spider-man-homecoming/')
----> 5 scraper.solve_cf_challenge(m)

C:\ProgramData\Anaconda2\lib\site-packages\cfscrape\__init__.pyc in solve_cf_challenge(self, resp, **original_kwargs)
     72             # technique. If you see this and are running the latest version,
     73             # please open a GitHub issue so I can update the code accordingly.
---> 74             raise ValueError("Unable to parse Cloudflare anti-bots page: %s %s" % (e.message, BUG_REPORT))
     75 
     76         # Solve the Javascript challenge

ValueError: Unable to parse Cloudflare anti-bots page: 'NoneType' object has no attribute 'group' Cloudflare may have changed their technique, or there may be a bug in the script.

**Comment by Anorov** [comment]
`solve_cf_challenge` is not intended to be called by users of the library; the library handles it automatically. You are trying to call it on a page that doesn't actually appear to be protected with Cloudflare IUAM ("I'm Under Attack Mode"), which is causing the error.

From a quick look at the page you're trying to scrape, it looks like it's embedding a separate page which is protected with Cloudflare IUAM. That's the page you'll actually want to make a request to (as well as removing the `solve_cf_challenge` call).

Closing as this isn't a problem with cloudflare-scrape.
