### ISSUE TITLE
Is cfscrape a tool to breakthrough cloud flare

### ISSUE THREAD

**Issue by evering7** [Anorov/cloudflare-scrape#116]
Hi, I am new to cloudflare. And I google out this tool but is very difficulty to find the real use of this tool even after I read some part of readme. Could you describe the real function of this tool for cloudflare. 

I want to know whether this tool could be integrated with sqlmap.

Thank you very much

**Comment by Anorov** [comment]
It bypasses Cloudflare's "I'm Under Attack Mode". And yes, it can be
integrated with sqlmap or any other application. Please re-read the README.

Thanks.
