### ISSUE TITLE
Website Bypass work in localhost, but not work on heroku server.

### ISSUE THREAD

**Issue by michele87cb** [Anorov/cloudflare-scrape#119]
Great work with this library!
But I can't use it on heroku server, it give me 403 error.
In localhost all is ok.

**Comment by KushFace** [comment]
Same Error. If I do the following:
```
scraper = cfscrape.create_scraper()
newspage = scraper.get('MY_URL')
print(newspage.content.decode())
```
Then I get the following HTML Code (only on my Ubuntu Server)
```
</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span data-translate="performance_security_by">Performance &amp; security by</span> <a data-orig-proto="https" data-orig-ref="www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
  </p>
</div><!-- /.error-footer -->
    </div><!-- /#cf-error-details -->
  </div><!-- /#cf-wrapper -->
  <script type="text/javascript">
  window._cf_translation = {};
</script>
</body>
</html>
```
On Windows I will get the full HTML of the Website I want.

**Comment by Anorov** [comment]
Is this happening for every URL?

**Comment by KushFace** [comment]
didn't test it with other cloudflare pages. The thing is. If i visit this page with windows browser (no matter which PC) i doesn't get a cloudflare page (no "you will redirect in 5 seconds" page). 

Only when I want to access this website with my Ubuntu Server I get the HTML of cloudflare page. 
But not if im starting the same bot from my Windows PC. It's really weird.

**Comment by Anorov** [comment]
I also don't see a Cloudflare IUAM page for that URL. It's possible Cloudflare has flagged your Ubuntu server's IP as malicious and is showing it a response intended for high-risk IPs.

This isn't something cloudflare-scrape can help with; you'll want to reach out to Cloudflare's support. I'll be closing this issue now. If I was wrong in my assessment (e.g. if your Ubuntu server and Windows PC are going through the same public IP, meaning they likely couldn't block only your server without also blocking your PC), please re-open this issue.

**Comment by deluxemonitor** [comment]
Did you manage to make it works ? I'm trying to run script on heroku server, and got same problem :/ Working perfectly find in local.
