### ISSUE TITLE
Occasional lapses when the target site is under load

### ISSUE THREAD

**Issue by dakyri** [Anorov/cloudflare-scrape#120]
I've had issues over the last few days connecting to an ETH exchange on cloudflare. When I've tracked scraper, it seems to be getting in a loop of challenge response which never gets satisfied.
I did manage to do a quick hack fix on this to get it to work by increasing the sleep time in solve_cf_challenge to 8 secs. That works. It's arbitrary I know, and not worth submitting as a fix. It would be good to maybe make this adaptive or something, given that it was (apparently) looping through solve_cf_challenge recursively.

Anyway, also, thanks for the awesome work. It really has been a life saver.

**Comment by Anorov** [comment]
Could you please link the site you're talking about? Does it still seem to regularly exhibit this issue when the sleep is set to 5 seconds?

**Comment by dakyri** [comment]
https://etherdelta.com/ .. it's not a regular problem, but it's happened when the site is highly loaded. Over the last month, it's happened maybe 3 times, but for a whole night. It seems to be traffic/routing related (we can run the script in germany ok, but still have issues in hungary). When the problem has happened I've often been able to connect ok on a browser. I think the most awkward aspect is this recursive loop of challenge-response. Cloudflare would just repeat a challenge rather than rejecting the session ... because this happens quietly, the script would hang ... I only saw what was going down after putting traces into cf-scrape for a few runs.

**Comment by arnau-foraster** [comment]
I've been facing the same issue, increasing delay time solves the problem

https://github.com/Anorov/cloudflare-scrape/pull/137

**Comment by Anorov** [comment]
The delay can now be specified and repeated challenges should now raise an exception asking the user to increase the delay.

https://github.com/Anorov/cloudflare-scrape/commit/d78325caf015f87eebd5c162bc9ed6797806a4d2
