### ISSUE TITLE
[NOT WORKING] Is still working

### ISSUE THREAD

**Issue by dannyeuu** [Anorov/cloudflare-scrape#124]
I'm trying to test with a single `scraper.get()` and return this error:

![screenshot from 2017-12-18 18-45-30](https://user-images.githubusercontent.com/6808348/34127321-d01abc08-e423-11e7-81fe-0d495f75f761.png)

There ate someone in production this days?

**Comment by Anorov** [comment]
Please read the README. Cloudflare may have flagged your IP or behavior as
suspicious.

"Note: This only works when regular Cloudflare anti-bots is enabled (the
"Checking your browser before accessing..." loading page). If there is a
reCAPTCHA challenge, you're out of luck."
