### ISSUE TITLE
Add a version marker to __init__.py

### ISSUE THREAD

**Issue by yan12125** [Anorov/cloudflare-scrape#126]
So that clients know whether cfscrape uses the relatively safer ```vm``` module or the unsafe ```js2py```. For example, after the ```import execjs``` line:

```
__version__ = '1.9.1'
```

**Comment by Anorov** [comment]
https://github.com/Anorov/cloudflare-scrape/commit/c06237e30df808e343f91ae6823650f41c3261ec

Done.
