### ISSUE TITLE
Bittrex return 503 error

### ISSUE THREAD

**Issue by sequencer** [Anorov/cloudflare-scrape#127]
[Original Issue](https://github.com/slazarov/python-bittrex-websocket/issues/12)
Wanna check if there is problem on other websites.

**Comment by veteranbv** [comment]
I’ve been running the cfscrape 1.9.1 release for last 24 hours and scraping sites behind the cf redirect without any issues. There was an update to Cloudflare’s headers a couple of days ago, which is why cfscrape was updated. Not sure if this is the cause of your issue.

**Comment by sequencer** [comment]
Alright, checking other possible problems. Thank you!

**Comment by dezza** [comment]
I am behind a VPN I am looking into the issue - I have tried to proxy with Charles and this fixes it magically. I cannot see my HTTP Connect or Connection headers stripped- so I assume there's something with signalr - probably this recent patch- which bittrex prolly haven't applied yet (Dec, 2017) commit..
