### ISSUE TITLE
cfscrape doesn't bypass Cloudflare anymore

### ISSUE THREAD

**Issue by saitam1** [Anorov/cloudflare-scrape#128]
For a few days the `cfscrape` lib doesn't work for me.
Try it yourself e.g. on this page:

```
import cfscrape
scraper = cfscrape.create_scraper()
url = 'https://tether.to'
print(scraper.get(url).content)
```

additionally you can add `BeautifulSoup` for a better code structure:

```
import cfscrape
from bs4 import BeautifulSoup

scraper = cfscrape.create_scraper()
url = 'https://tether.to'
content = scraper.get(url).content
soup = BeautifulSoup(content, "html.parser") 
print(soup)
```

**Comment by veteranbv** [comment]
I’ve been scraping around the clock for the last several days without any issues, including in the last couple hours. Have you upgraded to the latest release? Are you generating any errors?

**Comment by saitam1** [comment]
Oh thanks, I forgot to upgrade.
