### ISSUE TITLE
requests.exceptions.HTTPError: 503 Server Error

### ISSUE THREAD

**Issue by 1271** [Anorov/cloudflare-scrape#129]
Hello.
Today received an error 503 on the site "http://www3.mangafreak.net"
I also showed on the other the same problem. cloudflare returned 503 to the defense page.

I'm checked response with the browser. The protection page returned code 503.
In this case, the library can return only one token of two.

Here's what you can get:

[<RequestsCookieJar[Cookie(version=0, name='**__cfduid**', value='dc3ee0dec3847cc5801bf13204436ee061515857600', port=None, port_specified=False, domain='.mangafreak.net', domain_specified=True, domain_initial_dot=True, path='/', path_specified=True, secure=False, expires=1547493600, discard=False, comment=None, comment_url=None, rest={'HttpOnly': None}, rfc2109=False)]>]

In the headers missing **cf_clearance**

OS: win8, x64.
cloudflare-scrape: latest version (1.9.1)

Thanks.

//Sorry for my English

**Comment by Anorov** [comment]
I am unable to reproduce this issue. Could you please submit a PCAP of a failed attempt? Thanks.

**Comment by 1271** [comment]
The error appears only on windows.
I will send you the data after my work.

**Comment by 1271** [comment]
Wireshark dump log with error:
[wire-dump.dump.gz.pcap.zip](https://github.com/Anorov/cloudflare-scrape/files/1653740/wire-dump.dump.gz.pcap.zip)

**Comment by 1271** [comment]
terminal error log:

```bash
>>> tokens, user_agent = cfscrape.get_tokens("http://www3.mangafreak.net")
ERROR:root:'http://www3.mangafreak.net' returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\35\lib\site-packages\cfscrape\__init__.py", line 159, in get_tokens
    resp.raise_for_status()
  File "C:\Python\35\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Temporarily Unavailable for url: http://www3.mangafreak.net/
```

**Comment by Anorov** [comment]
Can you please make sure you have the latest version of cfscrape and run the following from a Python console:

```python
import cfscrape
print(cfscrape.__version__)
```

**Comment by 1271** [comment]
```
>>> import cfscrape
>>> print(cfscrape.__version__)
1.9.3
```

You fixed the error, how do I see? Now everything works well. Thank you! 👍
