### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by ne0ark** [Anorov/cloudflare-scrape#13]
cfscrape.py", line 61, in solve_cf_challenge
    answer = str(int(ctxt.eval(builder)) + len(domain))
SyntaxError: SyntaxError: Illegal return statement (  @ 2 : 77 )  -> !![]+!![]+!![]+!![]+!![]+!![]+!![]+!![])); return parseInt(UQTeuzc.TiasKf, 10)

**Comment by ne0ark** [comment]
Also seems like the change to PyExecJS is causing segmentation fault (core dumped)

**Comment by Anorov** [comment]
That's very strange, I haven't encountered either of those issues.

Were you using V8 as your JS engine in both the first and second examples? Can you see if the problem goes away if you use another engine like Node or Spidermonkey? `sudo apt-get install nodejs` works for Node.
