### ISSUE TITLE
cfscrape stopped bypassing cloudflare protection

### ISSUE THREAD

**Issue by defecat0r** [Anorov/cloudflare-scrape#130]
Hi,
I've been using cfscrape for a couple of months now with the following URL: 
https://socket.bittrex.com/signalR/negotiate

I've been using the following code:
url = "https://socket.bittrex.com/signalR/negotiate"
scraper = cfscrape.create_scraper()
result = scraper.get(url).content.decode()

As of this morning it's stopped working, the contents of 'result' is now the CloudFlare re-direct page:
https://pastebin.com/e4NV5syM

It should be returning a couple of lines of JSON, as you can see if you paste the link into the browser.

Thanks for the help and the great module!

**Comment by dhannyz** [comment]
I can confirm this, I get the same behaviour

**Comment by Lavande** [comment]
It's the same here. My script used to crawl data from etherscan.io now failed with the error of getting redirection page content instead of the actually page.

**Comment by veteranbv** [comment]
I've been using version 1.9.1 around the clock since its release, with latest scrape in the last hour and haven't had any hangs on the redirect page. I was encountering the same issue you're describing before upgrading to the latest about a month ago, but no problems since. Which version are you all using?

**Comment by defecat0r** [comment]
I've just upgraded to 1.9.1 this morning after experiencing the issue, no change for me.

**Comment by Lavande** [comment]
Ah, a bit strange as yours. I was using 1.9.0 just now and experienced the issue. Then I upgraded to 1.9,1 and it's working now!

**Comment by Xonshiz** [comment]
I've been using cfscrape in almost all my scrapping projects and now cfscrape isn't working for crunchyroll as well. I have not diagnosed the issue properly, but it doesn't return the cookies now. I'm on cfscrape 1.9.1. But again, I have not dived into the issue properly, could be some other changes. But, seems like some people are having similar 503 issue.

**Comment by defecat0r** [comment]
Correction, i thought i was using 1.9.1, but was using an older version. Upgrading to 1.9.1 has fixed it for me! Thanks!

**Comment by veteranbv** [comment]
That’s awesome @defecat0r and @Lavande. Unless @Anorov recommends differently, @defecat0r if your issue has been resolved I’d close the issue. For everyone else still experiencing issues, double check that your cfscrape version is up to date and then open another issue with more detailed information. I know the crunchyroll scrape project has a lot of other dependencies and have gone through a long thread on their side trying to keep their scrape capability up.

**Comment by defecat0r** [comment]
Roger that, thanks for the help!
