### ISSUE TITLE
have any problems

### ISSUE THREAD

**Issue by welest** [Anorov/cloudflare-scrape#131]
hello.

i'm try parse:
 work with url = https://etherscan.io, but don't work with url = https://etherscan.io/token/0xb5a5f22694352c15b00323844ad545abb2b11028#balances and other )) 

What should I do to work with all the links?

I will gladly pay for the solution of this problem ))

**Comment by Anorov** [comment]
I am unable to reproduce this issue. Could you please submit a PCAP of a failed attempt? Thanks.

**Comment by Anorov** [comment]
Closing due to lack of response.
