### ISSUE TITLE
PyExecJS is dropped

### ISSUE THREAD

**Issue by ololoe** [Anorov/cloudflare-scrape#136]
https://github.com/doloopwhile/PyExecJS

> End of life
> 
> This library is no longer maintananced. Bugs are not be fixed (even if they are trivial or essential).
> 
> We suggest to use other library or to make a fork.

I'm interested in a library with safe javascript evaluation too

**Comment by Anorov** [comment]
The dependency has been removed and replaced with a regular execution of the `node` binary (which was all PyExecJS was doing under the hood for cloudflare-scrape anyway).

https://github.com/Anorov/cloudflare-scrape/commit/d78325caf015f87eebd5c162bc9ed6797806a4d2
