### ISSUE TITLE
cfscrape through proxy

### ISSUE THREAD

**Issue by SergeevGregory** [Anorov/cloudflare-scrape#139]
Dear developer,
I try to use your lib through proxy:

import cfscrape

proxies = {"http": "bad_proxy"}
tokens, user_agent = cfscrape.get_tokens("http://somesite.com", proxies=proxies)
print tokens

I enter to proxies not correct proxy, but whatever get correct tokens and user_agent that works without proxy and not with it. Is it right? Where my error?

**Comment by Anorov** [comment]
What does `tokens` contain when you use a proxy? Can you try using a few different proxies?

**Comment by Anorov** [comment]
Closing due to lack of response.
