### ISSUE TITLE
Use a bash command under a cloudflare-scrape session

### ISSUE THREAD

**Issue by Sh0cknsl** [Anorov/cloudflare-scrape#14]
hello,

I have a question, I tried to use some tools like weevely, those tools can't bypass cloudflare because they use some custom cookies (the cookies are obfuscated and regenerated after each get request)

So, I would use cfscrape to bypass cloudflare and use weevely under the cfscrape session but seems to be not possible, any ideas ?

**Comment by Zalvie** [comment]
CloudFlare has started to append a refresh header at the protection page with the actual answer and everything, you could just use that.

**Comment by Anorov** [comment]
@Zalvie Nope, the Refresh header only includes the `pass` value, which is their newly added time token (Unix time + MAC signature to prevent tampering) to ensure you've waited a certain number of seconds before getting past the challenge. I'm guessing the Refresh header was possibly added to improve performance for clients who've already passed the challenge once, though I'm not entirely sure of the intended flow.

@Sh0cknsl I'll answer this question later today.

**Comment by Anorov** [comment]
@Sh0cknsl I created 2 convenience functions to help with extracting just the cookies: `get_tokens()` and `get_cookie_string()`. See https://github.com/Anorov/cloudflare-scrape#integration

For weevely in particular, you're going to want to modify `additional_headers` in core/config.py. See https://github.com/epinna/weevely3/blob/master/core/config.py#L32

At the bottom of config.py but before the `DO NOT CHANGE` LINE, I would add something like

```python
import cfscrape

cookie = cfscrape.get_cookie_string("http://somesite.com")
additional_headers.append(("Cookie", cookie))
```
