### ISSUE TITLE
Currently Not working

### ISSUE THREAD

**Issue by nemesis668** [Anorov/cloudflare-scrape#140]
Seems to not be working at the moment on cloudflare sites, doesn't seem to try and wait the 5 secs just does it instantly and shows the usual cloudflare jargon.

Sites I have noted not working are

https://www.animepace.si/
http://kimcartoon.me/

**Comment by Anorov** [comment]
These websites are working for me. Can you please make sure you're using the latest version of cloudflare-scrape? To check, see if `cfscrape.__version__` is `1.9.4`.

**Comment by nemesis668** [comment]
I've done pip install cfscrape as have been using it a long time and it's
saying all dependancies satisfied.

**Comment by veteranbv** [comment]
@nemesis668 When you execute “pip show cfscrape” what’s the output for the version field?

**Comment by nemesis668** [comment]
Says 1.9.0

**Comment by nemesis668** [comment]
I un-installed and installed again and now it seems to be running the latest version and all working :)
