### ISSUE TITLE
Web not scrapped

### ISSUE THREAD

**Issue by Fran008** [Anorov/cloudflare-scrape#142]
I execute the program but it gives me a web with the CloudFlare not passed:

This is the web I am trying to load:

htmlcontent = scraper.get("http://arenavision2018.tk/01?wiuhkascohln").content
print htmlcontent

And this is what it returns:

<html><head><script type="text/javascript">
//<![CDATA[
window.__cfRocketOptions = {byc:0,p:0,petok:"652c3608a8caa6f8e94b657ed75a11de872e28b4-1521463278-1800"};
//]]>
</script>
<script type="text/javascript" src="https://ajax.cloudflare.com/cdn-cgi/scripts/935cb224/cloudflare-static/rocket.min.js"></script>
<script type="text/rocketscript">function set_cookie(){var now = new Date();var time = now.getTime();time += 19360000 * 1000;now.setTime(time);document.cookie='beget=begetok'+'; expires='+now.toGMTString()+'; path=/';}set_cookie();location.reload();;</script></head><body></body></html>

I must say that the web is not in UAM mode in the moment I am trying to access it. But it gives me a wrong html answer anyway (it should give the answer you get by accessing "http://arenavision2018.tk/01?wiuhkascohln" from the web browser)

**Comment by NitroXenon** [comment]
Set the cookie and try again :P

**Comment by Fran008** [comment]
I works! Thank you for your fast reply. Your software is awesome, and it gives me a really good solution for my problems. Please keep it updated! :)
