### ISSUE TITLE
Is PyExecJS still needed or not?

### ISSUE THREAD

**Issue by nneonneo** [Anorov/cloudflare-scrape#143]
https://github.com/Anorov/cloudflare-scrape/blob/22400ee549174a16b9f078f4cfec4beff51df4b0/setup.py#L21

Here, you have a PyExecJS dependency listed. However, it seems that you're now making a direct call to `node` rather than running things through PyExecJS. If this is the case, perhaps you can remove this dependency from the list to avoid installing extraneous packages.

**Comment by Anorov** [comment]
Fixed.
