### ISSUE TITLE
Error parsing Cloudflare IUAM Javascript challenge

### ISSUE THREAD

**Issue by pl77** [Anorov/cloudflare-scrape#145]
script was working reliably for weeks, but this morning spit out the above error.  

Here is a pastebin of the page text: https://pastebin.com/HXmdsm0E

Page url in the pastebin.  

it's failing at the start of the script, with the line: 
`cookie_arg, user_agent = cfscrape.get_cookie_string(url)`

**Comment by pl77** [comment]
Okay, running through a VPN it appears to be working fine now, so this was likely an IP-specific issue.  I will close this issue.

**Comment by pl77** [comment]
I take it back.  Seconds after I closed the issue the script suddenly quit again with the same error message: 
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "D:\Anaconda\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "E:/Downloads/torrentdumps/threedload.py", line 54, in run
    r = self.http.get(url)
  File "D:\Anaconda\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "D:\Anaconda\lib\site-packages\cfscrape\__init__.py", line 66, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "D:\Anaconda\lib\site-packages\cfscrape\__init__.py", line 97, in solve_cf_challenge
    params["jschl_answer"] = str(self.solve_challenge(body) + len(domain))
  File "D:\Anaconda\lib\site-packages\cfscrape\__init__.py", line 127, in solve_challenge
    raise ValueError("Error parsing Cloudflare IUAM Javascript challenge. %s" % BUG_REPORT)
ValueError: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues."

Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Anaconda\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "E:/Downloads/torrentdumps/threedload.py", line 54, in run
    r = self.http.get(url)
  File "D:\Anaconda\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "D:\Anaconda\lib\site-packages\cfscrape\__init__.py", line 66, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "D:\Anaconda\lib\site-packages\cfscrape\__init__.py", line 106, in solve_cf_challenge
    redirect_location = urlparse(redirect.headers["Location"])
  File "D:\Anaconda\lib\site-packages\requests\structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
```

**Comment by SIDECHAIN3D** [comment]
Confirming same issue on my side for CF-enabled site. 

Rerunning my script seemed to do the trick earlier today, but it looks like the error is being thrown on the initial request now, as well.

**Comment by issues420** [comment]
Also confirming this same issue, I just started getting this.  about every 5 or so requests do seem to make it through.

**Comment by Anorov** [comment]
Please provide the URLs you're trying to make requests to. Thanks.

**Comment by pl77** [comment]
@Anorov - the only one I've tried so far is 3d-load.net

**Comment by iraykhel** [comment]
Also not working, also bittrex. URL is their socket subscriber https://socket.bittrex.com/signalr/negotiate?clientProtocol=1.5&connectionData=%5B%7B%22name%22%3A%22corehub%22%7D%5D

**Comment by Eastkap** [comment]
I also have the issue on [http://oneblockdown.it/](http://oneblockdown.it/)

**Comment by iamnotturner** [comment]
same issue on https://www.off---white.com

**Comment by michaelwayman** [comment]
This was working on bittrex for me this morning/later last night, but then all of a sudden I'm getting the same error `ValueError: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.`

**Comment by gungorkdr** [comment]
Confirming same issue for http://socket.bittrex.com/signalr

**Comment by slazarov** [comment]
http://socket.bittrex.com/signalr is not the correct URL, you have to append it.

**Comment by Anorov** [comment]
Thanks everyone. I'm pre-occupied at the moment, but I've identified the change Cloudflare made and will get the module working again in a few hours.

**Comment by Anorov** [comment]
I have just pushed a new commit. Can you all please run `pip install cfscrape -U` to update to the latest version and see if the issue is resolved now?

**Comment by adrival0799** [comment]
Working fine on my scripts!!

**Comment by pl77** [comment]
Thanks very much, Anorov.  Works good from here.  I'm also proxying through crawlera and that didn't seem to cause any issues with the new build either. 

Thanks again!

**Comment by issues420** [comment]
Works here. A BIG Thanks you!

**Comment by gungorkdr** [comment]
Works like a charm. Thank you!

**Comment by partibrejker2** [comment]
for me it's still not working

SEARCHQUEUE-MANUAL-75719 :: [Torrent9] :: [1d34bcb] Request failed: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.

[Torrentz] :: [1d34bcb] Request failed: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.

**Comment by smorison** [comment]
getting the same error still.,.. version details below

root@ca8e16272d84:/$ pip show cfscrape                                                                              
Name: cfscrape                                                                                                      
Version: 1.9.5                                                                                                      
Summary: A simple Python module to bypass Cloudflare's anti-bot page. See https://github.com/Anorov/cloudflare-scrap
e for more information.                                                                                             
Home-page: https://github.com/Anorov/cloudflare-scrape                                                              
Author: Anorov                                                                                                      
Author-email: anorov.vorona@gmail.com                                                                               
License: UNKNOWN                                                                                                    
Location: /usr/lib/python2.7/site-packages                                                                          
Requires: requests

**Comment by cyaris** [comment]
I'm also getting the same error. Here's mine.

Name: cfscrape
Version: 1.9.7
Summary: A simple Python module to bypass Cloudflare's anti-bot page. See https://github.com/Anorov/cloudflare-scrape for more information.
Home-page: https://github.com/Anorov/cloudflare-scrape
Author: Anorov
Author-email: anorov.vorona@gmail.com
License: UNKNOWN
Location: /home/cyaris/.local/lib/python3.7/site-packages
Requires: requests
