### ISSUE TITLE
CloudFlare Issue (via SickRage)

### ISSUE THREAD

**Issue by daraghfi** [Anorov/cloudflare-scrape#148]
2018-04-07 14:44:10 SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: [1d34bcb] Request failed: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.

FYI  - thanks for posting open source!

**Comment by jrevillas** [comment]
Same here, using latest version.

**Comment by smorison** [comment]
i'm still having issues in SR as well... error and version below 

2018-04-08 17:58:07 SEARCHQUEUE-MANUAL-270261 :: [Torrent9] :: [1d34bcb] Request failed: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.


Name: cfscrape                                                                                                      
Version: 1.9.5                                                                                                      
Summary: A simple Python module to bypass Cloudflare's anti-bot page. See https://github.com/Anorov/cloudflare-scrap
e for more information.                                                                                             
Home-page: https://github.com/Anorov/cloudflare-scrape                                                              
Author: Anorov                                                                                                      
Author-email: anorov.vorona@gmail.com                                                                               
License: UNKNOWN                                                                                                    
Location: /usr/lib/python2.7/site-packages                                                                          
Requires: requests

**Comment by iliamihai** [comment]
ImportError: No module named requests.sessions
Anyone?

**Comment by Dohnerd** [comment]
Still getting the error after cfscrape update

2018-04-06 11:37:23 SEARCHQUEUE-DAILY-SEARCH :: [Torrentz] :: [1d34bcb] Request failed: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.

[/] # pip show cfscrape
Name: cfscrape
Version: 1.9.5

**Comment by VeNoMouS** [comment]
@Dohnerd you do realise, that sickrage uses its own packed cfscrape... https://github.com/SickRage/SickRage/blob/master/lib/cfscrape/__init__.py

And that version being 1.9.4... hardly see how its @Anorov's issue, im a dev for sickbeard torrent providers edition and i upgraded our version fine ...

**Comment by Anorov** [comment]
You will need to contact SickRage's developers. They have a hardcoded version of cfscrape in their requirements.txt, and that version is out of date: https://github.com/SickRage/SickRage/blob/1d34bcb48c1e03d568a8fdc08f60df8fa7f2d5d4/requirements/requirements.txt#L10

**Comment by Dohnerd** [comment]
@VeNoMouS don't really see where you are going with that? I followed https://github.com/Anorov/cloudflare-scrape#dependencies and updated as the original issue with cloudflare in SR suggested, but still have the error, there are no pending updates avail at SR, so I'm declaring that i still have the issue?

**Comment by skaynl** [comment]
It seems Sickrage had some updates today that fixed it. At least I haven’t had the error for an hour now, bit soon to tell but just saying.

**Comment by VeNoMouS** [comment]
@skaynl yea hence why i tagged @miigotu and hes got the power to authorize commits on sickrage :P

re @Dohnerd you do realize pip upgrading your pwned installed version of cfscrape isn't going to matter... as sickrage has cfscrape packaged under its own lib directory and that was 1.9.4 i did paste that... guess you just failed to understand what i meant... 

anyway you guys are back up and running so you guys should be happy, i was simply pointing out it was sickrage that was at fault (due to out dated package) as the fix was released a couple days ago for cfscape.

**Comment by Dohnerd** [comment]
Yes that was actually why i deleted my post, I realised you guys didnt have anything to do with SR :)

**Comment by daraghfi** [comment]
Thanks to all. 

To avoid confusion going forward, might I suggest that if SR is using custom code, they might also customize the error message? Just an idea @miigotu

Cheers,

Daragh

**Comment by miigotu** [comment]
SickRage is not using custom code. We provide a vanilla copy of cfscrape with the source, to save you time. The fix was put into SickRage right after it was released here, it was just in our develop branch going through the vetting process. Let the maintainers maintain. When you have an issue using SR report it on SR.

**Comment by daraghfi** [comment]
@miigotu thanks for the response and clarification. 
I found myself at this site because the error directed me here, just FYI.
Please see below. Thanks again for contributing to opensource.

2018-04-08 21:49:07 ERROR SEARCHQUEUE-BACKLOG-183411 :: [Torrent9] :: [a760263] Request failed: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.
**AA Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues."**
AA ValueError: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.
AA raise requests_exception
AA File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1525, in handle_requests_exception
AA Traceback (most recent call last):
AA Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues."

**Comment by VeNoMouS** [comment]
LOL ^^ , yea i took that out on my version :P
