### ISSUE TITLE
Problem bypassing CF

### ISSUE THREAD

**Issue by AmaziinqCop** [Anorov/cloudflare-scrape#152]
Error:
Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.

**Comment by veteranbv** [comment]
Please refer to the readme for guidelines on information needed when filing an issue

**Comment by Anorov** [comment]
Please ensure you're using the latest version of cloudflare-scrape and that all libraries you're using are importing/including the latest version of cloudflare-scrape. If you're still experiencing problems, please follow [these instructions](https://github.com/Anorov/cloudflare-scrape#updates) and create a new issue.
