### ISSUE TITLE
Request failed: 403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by Jamyz** [Anorov/cloudflare-scrape#153]
Hi!!
I use Sickrage and we have this error.
Cloudflare change the system ?
Thanks

**Comment by Anorov** [comment]
Please ensure you're using the latest version of cloudflare-scrape and that all libraries you're using are importing/including the latest version of cloudflare-scrape. If you're still experiencing problems, please follow [these instructions](https://github.com/Anorov/cloudflare-scrape#updates) and create a new issue.
