### ISSUE TITLE
issues using on xbmc platform

### ISSUE THREAD

**Issue by teamuniversal** [Anorov/cloudflare-scrape#155]
hi i was wondering if you had time to take a look at something for me. i have been using your previous versions of cf-scrape within a xbmc project but im struggling to update it to the new version any help would be greatly appreciated

**Comment by Anorov** [comment]
Please ensure you're using the latest version of cloudflare-scrape and that all libraries you're using are importing/including the latest version of cloudflare-scrape. If you're still experiencing problems, please follow [these instructions](https://github.com/Anorov/cloudflare-scrape#updates) and create a new issue.
