### ISSUE TITLE
Async feature

### ISSUE THREAD

**Issue by lucasgadams** [Anorov/cloudflare-scrape#156]
Hi, just wondering if you were planning on creating an async version of the library using aiohttp? If thats interesting to you I can help out.

**Comment by lucasgadams** [comment]
Hello, i set up a PR with basic async functionality  https://github.com/Anorov/cloudflare-scrape/pull/157 . There is still some implementation and cleanup work to be done but the basic requests work. @Anorov

**Comment by slazarov** [comment]
There is an asyncio version based on Anorov's cfscrape: https://github.com/pavlodvornikov/aiocfscrape

Adding async and non-async compatibility in the same library is a bit troublesome.

**Comment by slazarov** [comment]
@dteh great! Try contacting him via email so he can push it. Anyways I reckon @Anorov should close this issue.

**Comment by Anorov** [comment]
As @slazarov said, this should be a separate repo.
