### ISSUE TITLE
bypass ssl check

### ISSUE THREAD

**Issue by djoey123** [Anorov/cloudflare-scrape#159]
Hi
i want to disable the ssl check, because some website's fail to check. i already got this but it isnt working

import cfscrape
import sys
import requests
from requests_toolbelt.adapters.source import SourceAddressAdapter

url = sys.argv[1]

#scraper = cfscrape.create_scraper()  # returns a CloudflareScraper instance
scraper = cfscrape.create_scraper(delay=20)
scraper.mount('http://', SourceAddressAdapter(('my2endIP')))
scraper.mount('https://', SourceAddressAdapter(('my2endIP')))
scraper.verify = False 
status_code = scraper.get(url).content

print (status_code)

**Comment by Anorov** [comment]
Try `scraper.verify = False`. `scraper.get(url, verify=False` also works if you want to disable SSL verification for a single request. Please consult Requests' documentation.

**Comment by djoey123** [comment]
Tried your second option it still doesn't work for me.

Error:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "codechecker.py", line 13, in <module>
    status_code = scraper.get(url,verify=False).content
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cfscrape/__init__.py", line 64, in request
    resp = super(CloudflareScraper, self).request(method, url, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='*****.nl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert protocol version')],)",),))

**Comment by Anorov** [comment]
This is an SSL handshake error, not an SSL verification error. It's not
possible to bypass this because you can't connect at all if the SSL
handshake fails. Please take this issue up with Requests.
