### ISSUE TITLE
CF change

### ISSUE THREAD

**Issue by ppanther1000** [Anorov/cloudflare-scrape#16]
Code stopped working today.

Thank you for your great work, anorov!

**Comment by j4m** [comment]
I can confirm that. It doesn't work anymore.

**Comment by ne0ark** [comment]
Could you provide an example website, and also preferably a Pastebin of the HTML source?

**Comment by beepworld** [comment]
Example can be found here: http://pastebin.com/JUKiwW00

**Comment by ppanther1000** [comment]
Example can be found here: http://pastebin.com/JUKiwW00

**Comment by Anorov** [comment]
Cloudflare is now enforcing the 5 second wait before getting past the challenge. Previously they never actually checked for it. Unfortunately, this means any script using cloudflare-scrape will have to sleep for 5 seconds the first time they visit any Cloudflare-protected site.

I've pushed a new commit. Please verify that everything works now.

**Comment by erikbos** [comment]
Issue is fixed, thx!

**Comment by ppanther1000** [comment]
Fixed. Great job!
