### ISSUE TITLE
Think cloudflare changed their code...

### ISSUE THREAD

**Issue by rdlou** [Anorov/cloudflare-scrape#163]
This doesn't seem to be working anymore @Anorov.

Trying it with https://www.bboxx.workable.com and get numerous errors:

ssl.CertificateError: hostname 'www.bboxx.workable.com' doesn't match either of 'ssl859201.cloudflaressl.com', '*.workable.com', 'workable.com'

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.bboxx.workable.com', port=443): Max retries exceeded with url: / (Caused by SSLError(CertificateError("hostname 'www.bboxx.workable.com' doesn't match either of 'ssl859201.cloudflaressl.com', '*.workable.com', 'workable.com'",),))

Thanks in advance!

**Comment by bato3** [comment]
@rdlou free version cloudflare don't allows fo 2-level supbpage, so correct url is https://bboxx.workable.com

**Comment by Anorov** [comment]
Not an issue with the library. Closing.
