### ISSUE TITLE
Cloudflare challenge not solved anymore ...

### ISSUE THREAD

**Issue by marcfrancis961** [Anorov/cloudflare-scrape#165]
I've used cf_scrape to scrape a website with srcapy. Created a middleware to add cf tokens to all my requests. Used to work like a charm untill this morning,... I get blocked on the first request I make.

Url I want to scrape is: https://www.machinerytrader.com/listings/construction-equipment/for-sale/category/1033/excavators-mini-up-to-12000-lbs 

HTML copied from browser https://pastebin.com/dYYWJmx0

Here is the tokens I get from the get_tokens method: {'cf_clearance': '', '__cfduid': 'd2e6daea1a3307313159f1e079bd1d83a1531904831'} 

I wonder why the cf_clearance token is empty .. 

pip show cfscrape --> 1.9.5

@Anorov, @veteranbv  or anyone using cf-scrape ... any idea how I should proceed ?

Thx

**Comment by Anorov** [comment]
Can you please include the HTML of the Cloudflare challenge page?
