### ISSUE TITLE
Make `solve_challenge` public

### ISSUE THREAD

**Issue by bato3** [Anorov/cloudflare-scrape#166]
Great work! 

But integration with a project that does not use `requests.Session` is annoying ...

That's why I am asking for make public `solve_challenge` or even better separating and making public the prepared js. [#L113-L128](https://github.com/Anorov/cloudflare-scrape/blob/master/cfscrape/__init__.py#L113-L128)

**Comment by Mattwmaster58** [comment]
The JS (as I understand) is *dynamically* served to you from cloudflare. In the lines you mentioned, it's simply using a few regex patterns to get that javascript, and then, after executing that JS in node and looking at the result to generate the cookie.

In fact, taking a quick look at `solve_challenge` reveals that it if you spend a few minutes refactoring it out of the class, it would easily work on it's own.

**Comment by bato3** [comment]
Yes, you are right, but the JS challenge code is changed from time to time, and as you use cloudflare-scrape as a package, it's less work with the upgrade.

**Comment by Anorov** [comment]
There are no plans to do that at this time.
