### ISSUE TITLE
Solve recaptcha

### ISSUE THREAD

**Issue by AidasK** [Anorov/cloudflare-scrape#167]
Have you tried adding https://anti-captcha.com to the tool?

**Comment by Mattwmaster58** [comment]
I think that's really beyond the scope of this project. Besides, the user a adoption rate for a method that costs money would be extremely low and likely not worth the effort IMHO.

**Comment by Anorov** [comment]
Exceptions are now raised for captchas, but there are no plans to provide a way to solve captchas.
