### ISSUE TITLE
no token retrieval

### ISSUE THREAD

**Issue by quancore** [Anorov/cloudflare-scrape#171]
I am trying to retrieve file from website protected by cloudflare.However, I am getting:
![image](https://user-images.githubusercontent.com/15036825/46160304-a08e0880-c282-11e8-8dc3-233c8d6adb27.png)
The code:
![image](https://user-images.githubusercontent.com/15036825/46160603-71c46200-c283-11e8-87fe-cfb23b1825d8.png)
![image](https://user-images.githubusercontent.com/15036825/46160636-928cb780-c283-11e8-8697-ebd3153a7bd0.png)
When I got to one of the link, I am getting:
![image](https://user-images.githubusercontent.com/15036825/46160709-b8b25780-c283-11e8-9e3e-a5e5108b2562.png)

**Comment by vxtto** [comment]
You are banned, just do everything through a proxy.

**Comment by Anorov** [comment]
See @vxtto's answer.
