### ISSUE TITLE
proxy is not working

### ISSUE THREAD

**Issue by quancore** [Anorov/cloudflare-scrape#174]
**code:**
```
# get cookie string for bypassing cloudflare protection
def get_cookie_token(url, user_agent, proxy=None):
    if proxy:
        proxy = 'http://'+ proxy
        cookie_arg, user_agent = cfscrape.get_tokens(url, user_agent=user_agent, proxies={'https': proxy, 'http': proxy})
    else:
        cookie_arg, user_agent = cfscrape.get_tokens(url, user_agent=user_agent)

    return cookie_arg

```
```
proxy = ProxyManager.getInstance(user_agent_str, session).get_proxy()
token = get_cookie_token(url, user_agent_str, proxy=proxy)
r = session.get(url, stream=True, headers=headers, timeout=constants.timeout,
cookies={'__cfduid': token['__cfduid'], 'cf_clearance': token['cf_clearance']}, proxies={'https': proxy})
```

> proxy format ---> 188.112.53.89:50360  I already check that proxy is working from several website and checkers.

**error:**
![image](https://user-images.githubusercontent.com/15036825/47444123-10c27800-d7b6-11e8-9107-253c4c4cfac6.png)

**Comment by quancore** [comment]
up

**Comment by quancore** [comment]
up

**Comment by quancore** [comment]
waiting a response

**Comment by quancore** [comment]
still an issue

**Comment by quancore** [comment]
up to date ...

**Comment by Anorov** [comment]
I am currently on vacation and will be able to take a look at this in a few
weeks.

**Comment by Mattwmaster58** [comment]
Can you connect with a regular proxy with requests? I'm doubtful cfscrape is the issue.

**Comment by Anorov** [comment]
Can you please try upgrading cloudflare-scrape with `pip install -U cfscrape` and see if you continue to experience this problem? If so, please re-open this issue.
