### ISSUE TITLE
Parsing timeout value from js for more effecient timeout.

### ISSUE THREAD

**Issue by Mattwmaster58** [Anorov/cloudflare-scrape#181]
Perhaps we could parse the timeout value with regex (ex `r'}, (\d{4,5})\);'`) to accurately wait the least possible time. I'm not sure is cloudflare dynamically adjusts this timeout value based on the server load, but if it does, this will also mitigate problems related to not waiting long enough.

Example:

     try:
          delay  = re.search(r'}, (\d{4,5})\);', body) .group(1)
     except AttributeError:
          delay = self._delay_fallback

I wouldn't mind submitting a PR if you think this is a good idea.

**Comment by kittenswolf** [comment]
Sounds like a good idea!
