### ISSUE TITLE
seems broken

### ISSUE THREAD

**Issue by TH3MA5K** [Anorov/cloudflare-scrape#185]
` scraper = cfscrape.create_scraper()`
`scraper.get('https://hdfilme.net/').content`

is not returning anything. 'https://google.de' is working without any problems.

any suggestions?

Best Regards

TH3MA5K

**Comment by quancore** [comment]
Need verification of it is still working.

**Comment by TH3MA5K** [comment]
I manged to chanche some part of the code, now it is working.
