### ISSUE TITLE
Set outgoing IP

### ISSUE THREAD

**Issue by iron-udjin** [Anorov/cloudflare-scrape#187]
Hello,

Is there way to set IP address (both types, ipv4 and ipv6) for outgoing connections? Something similar to curl's "--interface" together with "-4" and "-6" variables.

Thank you!

**Comment by Mattwmaster58** [comment]
You can't set or spoof an public IP address to use for a request. What you can do is route your requests through a proxy. As for specifying a specific interface, the requests library for which this library uses is not really suited for that purpose, so you have to do some digging by googling. In both cases, you'd most likely achieve your results by setting up a `requests.Session` object and passing it in the `cfscrape.create_scraper` or by passing in the relevant keyword args to required cfscrape methods. Read the docs if you're unsure of how to do this. This library is definitely not the place to implement these kinds of low-level features, and to some extent it looks like what you're looking for has already been implemented.

**Comment by iron-udjin** [comment]
Thank you for detailed answer. I don't need to spoof public IP address. There are a few IPs on the server in the same subnet. When I initialize connection it goes from the fist one IP. All that I need is to define other IP from existing IP range of the server for outgoing connection. Nothing more.

I need it because I have strange issue when I use proxy. I sucessfully receive `__cfduid` and `cf_clearance` cookies via proxy use `cfscrape.get_cookie_string()`. But when I call CURL via the same proxy with `_cfduid` and `cf_clearanc` which I got, CF perform browser check again and I can't get website page.

Unfortunatelly I'm not so expirianced in python programming. Is there any example how to use `requests.Session` together with `cfscrape.create_scraper()`?

Thank you.

**Comment by Mattwmaster58** [comment]
`cfscrape.create_scraper(sess=session)` where `session` is a `requests.Session` object. Or, you can create a object which inherits everything from a requests.Session object: `cfscrape.create_scraper()`. The first example is what you'd use if you had an existing session. The second is used in the case where you don't have session already created. Since you mentioned cURL, you may be interested in the [PycURL library](http://pycurl.io/).

**Comment by iron-udjin** [comment]
Thank you for explanation.
