### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Simpfally** [Anorov/cloudflare-scrape#19]
cloudflare page : http://pastebin.com/Jd9uHBtS (no idea why it's so long)
Traceback (most recent call last):
  File "cloudflarescrap.py", line 8, in <module>
    raise ValueError("'%s' returned error %d, could not collect tokens." % (url, resp.status_code))
ValueError: 'http://csgo.steamanalyst.com' returned error 503, could not collect tokens.

For some reason, sometimes it gives this error, but more often it only gives the cfduid cookie (cfclerance empty). Edit: just tried the same script 50times.. 0.99/2 error 0.99/2 cfduid only, and only got both cookies twice edit: just got both cookies 5times in a row, but now it's back to errors for 20 or so tries.

I've got it working on another site, but for some reason it doesn't on this site.

**Comment by Anorov** [comment]
Interesting, I'm not sure why that's happening. I'm not able to reproduce it no matter how many times I run it in a row.

The source code is large because they set up a custom Cloudflare loading page. If you upgrade above the free tier, you get that option. That should not affect cloudflare-scrape, though.

Can you try changing the sleep time here from 5 to 15 seconds? https://github.com/Anorov/cloudflare-scrape/blob/master/cfscrape/__init__.py#L50

**Comment by Simpfally** [comment]
I thought of changing the time to sleep (as when random things happen, timing may be related) but..
I can't reproduce it today either. Damn it, I'm 100% sure I've not changed the script that call cloudflarescrap, so..
Anyway I'm sorry I had to bother you with a non-issue. I'll take the opportunity to say thank you for coding this! I'll try to learn how did you get those cookies once I learn python a bit, but for now this python script is vital for me haha.

**Comment by Anorov** [comment]
Cloudflare goes through a lot of effort to detect bots, so it's not too surprising they would occasionally flag your bot as... a bot. It is odd that it was only happening intermittently though. If you see it happening again, try changing the sleep time.

**Comment by Simpfally** [comment]
Oh I don't think so, it happened with the first request I ever made with the site.
Yup if it breaks again I'll increase the time.

**Comment by Simpfally** [comment]
The script returned 503 randomly but very often again today on different sites, I've checked the site in my browser and they indeed returned 503 to the first request. Sometimes it works, sometimes it don't, quite annoying.

So I reinstalled cloudflare to change the sleep time, tested everything from 1 to 20, didn't change behaviour at all (doesn't work as expected under 5 through). But after getting the last update it didn't work because of the print statement that was in python 2.7 style. And a bunch of other things I couldn't change didn't work.

I re-did everything with python2.7 and it's working flawlessly for now. I've got no idea what changed, why it couldn't get the cookies before.. But now it's working. So use 2.7.

**Comment by Simpfally** [comment]
$ python2.7 cloudflarescrap.py 
'http://csgo.steamanalyst.com' returned error 503, could not collect tokens.

Traceback (most recent call last):
  File "cloudflarescrap.py", line 7, in <module>
    tokens, user_agent = cfscrape.get_tokens(url, "Mozilla/5.0 (X11; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0")
  File "build/bdist.linux-x86_64/egg/cfscrape/__init__.py", line 105, in get_tokens
  File "/usr/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Temporarily Unavailable

And it's here again.. No idea how to replicate, but it's always the 503 error. And visiting the site in a browser also show a 503 error, but it redirects after it.

**Comment by Simpfally** [comment]
(Phone lags too much to be used, so still investigating this issue)
(Remember, sometimes it works completely, so the program itself shouldn't be the problem) I found that if I refresh the target page in a browser at the same time I run your script, it works. It gives the cookies to my program, but once a request is made, I'm still welcomed by the cloudflare page despite having the correct cookies. (tested them on the browser).

Why on earth does the hotel wifi and its wifipass mess with my request but not my browser? And only 'sometimes'?

**Comment by Anorov** [comment]
I made some recent changes with the `get_tokens` function. It now returns the user agent, and you must use that exact same user agent when making requests with those cookies.

Are you using the latest version of the code and making sure the requests you make use the user agent returned by that function?

If so, try what I said before and increase the sleep time at https://github.com/Anorov/cloudflare-scrape/blob/2c9934ad071ffff3333db6153b3083227c65b01c/cfscrape/__init__.py#L48

**Comment by Simpfally** [comment]
I've got the latest function and matched user-agent, your script even manage to get the good cookies 1/2 of the time, but then my request fail. So yeah, my very simple GET request gets caught by CF even with the right cookies, because of the wifi network I'm currently in.
So the wifi's messing with me but I see almost none of that in my browser. It loads the CF bot page more often than before.

To get the CF bot page, the wifi must change my useragent.. randomly.. or what else can it be?

**Comment by Anorov** [comment]
There is probably something else about your network connection or device that Cloudflare is flagging as suspicious. It would probably take quite a bit of work to figure out what it is. They are definitely looking at more than just user agent, and I doubt the wifi connection is doing anything to the user agent. It could be adding or changing some other header though, or it could be part of a network that Cloudflare thinks has a bad reputation.

There isn't much more I can do here, unfortunately, since I'm pretty sure the problems are not being caused by the module.

**Comment by Simpfally** [comment]
Wasted so much time on this issue, now back to my home wifi, the module's working perfectly.
