### ISSUE TITLE
get_cookies

### ISSUE THREAD

**Issue by ololoe** [Anorov/cloudflare-scrape#20]
As far as my experiments showed, CF cookies are bound to user agent string. In that case you should return cookies together with user agent, otherwise they are useless.

**Comment by Anorov** [comment]
Excellent point.

The token functions now return a tuple of `(cookies, user_agent_string)`. You can also optionally pass a custom user-agent to those functions.

The API is a little bit ugly, but I don't think it's worth abstracting it any more than that.

**Comment by ololoe** [comment]
I would rather return namedtuple for the case you change something in the future.
