### ISSUE TITLE
Error parsing Cloudflare IUAM Javascript challenge

### ISSUE THREAD

**Issue by rsarkhani** [Anorov/cloudflare-scrape#202]
i tried to update Cloudflare via `pip install -U cfscrape` command to 1.9.5 and it updated the package in `c:\python27\lib\site-packages`, however, and im not sure, but it seems like SickChill is using `c:\SickChill\python\`. Now i dont know if the update affected SickChill at all or not?

This is the error im getting
`2019-03-21 09:21:32 SEARCHQUEUE-DAILY-SEARCH :: [f7a113a] Request failed: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.`

**Comment by pro-src** [comment]
@rsarkhani 

Change the version of cfscrape in `C:\SickChill\requirements\requirements.txt` and run `C:\SickChill\python\python.exe C:\SickChill\setup.py install` to update it.

You probably should `cd C:\SickChill` prior to do any of the above. 

The python path should be correct but you'll need to find `requirements.txt` and `setup.py` yourself if the paths that I've provided aren't accurate.

If all else fails, delete Lamedows and install a linux distro!

**Comment by rsarkhani** [comment]
Thanks for the comment, i updated the version number fine with your instruction but it seems like the error still exists.

**Comment by pro-src** [comment]
@rsarkhani Do you have nodejs installed? Can you provide logs from SickChill in a pastebin?

**Comment by pro-src** [comment]
@rsarkhani https://github.com/SickChill/SickChill/wiki/FAQ%27s-and-Fixes#how-do-i-enable-debug-logs-to-get-more-detailed-information-in-my-logs

**Comment by rsarkhani** [comment]
Yes i have Node.js installed.
This is what i have from error.log which i added to `nssm`

`11:36:12 INFO::SEARCHQUEUE-MANUAL-279121 :: Downloading The.Flash.2014.S05E16.HDTV.x264-BATV[rartv] from Rarbg
11:36:12 INFO::SEARCHQUEUE-MANUAL-279121 :: Downloading a result from Rarbg at http://thetorrent.org/torrent/140632E67852C594C3CE8584B887FFBC58C9616D.torrent
11:36:13 INFO::SEARCHQUEUE-MANUAL-279121 :: Request failed: 404 Client Error: Not Found for url: http://thetorrent.org/torrent/140632E67852C594C3CE8584B887FFBC58C9616D.torrent (<type 'str'>)
11:36:13 INFO::SEARCHQUEUE-MANUAL-279121 :: Downloading a result from Rarbg at http://itorrents.org/torrent/140632E67852C594C3CE8584B887FFBC58C9616D.torrent
11:36:21 ERROR::SEARCHQUEUE-MANUAL-279121 :: [f7a113a] Request failed: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1526, in handle_requests_exception
    raise requests_exception
ValueError: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues."`

**Comment by pro-src** [comment]
You're getting a 404 Not Found error :smile: The remote resource doesn't exist: http://thetorrent.org/torrent/140632E67852C594C3CE8584B887FFBC58C9616D.torrent

**Comment by rsarkhani** [comment]
11:36:13 INFO::SEARCHQUEUE-MANUAL-279121 :: Downloading a result from Rarbg at http://itorrents.org/torrent/140632E67852C594C3CE8584B887FFBC58C9616D.torrent

how come this link works fine then?

**Comment by pro-src** [comment]
Because the second link points to a resource on a different server where it happens to exists? If it's working with that second link then cfscrape is working properly and is no longer the problem.

**Comment by pro-src** [comment]
@rsarkhani This was never a problem with cfscrape but with SickChill. I'm just trying to be helpful. You can read their comment about cfscrape on their requirements readme: https://github.com/SickChill/SickChill/blob/master/requirements/readme.md

I would open an issue at https://github.com/SickChill/SickChill and close this one. It's not something that cloudflare-scrape can/should fix.

**Comment by pro-src** [comment]
I've never even heard of SickChill before this issue but I do watch the flash :+1:

**Comment by pro-src** [comment]
@rsarkhani BTW you're failing to update to the latest version: https://pypi.org/project/cfscrape/#history

It's 1.9.7

**Comment by pro-src** [comment]
That's all :rofl:

**Comment by rsarkhani** [comment]
Thanks @pro-src .

i will open an issue in their site.

Thanks for the help to get this versions updated.
