### ISSUE TITLE
redirect url after cf challenge loses query part

### ISSUE THREAD

**Issue by vosime** [Anorov/cloudflare-scrape#204]
Hi,

first of all thanks for providing us such a lifesaving library. :-)

I have a question, suddenly (after last updates), it starts to behave differently.  Let's assume that the link is http://scene-rls.net/?s=sherlock&submit=Find
after sending it to cfscrape and successfully passed the challenge, now, the library redirects to page http://scene-rls.net

is it possible again to redirect it to the address with query part?

thanks in advance,
kind regards

**Comment by EdmundMartin** [comment]
```python3
if not redirect_location.netloc:
    redirect_url = "%s://%s%s" % (parsed_url.scheme, domain, redirect_location.path)
    return self.request(method, redirect_url, **original_kwargs)
```
This is cause by how the redirect_url is created with only the path being passed along. You have to options, you could either patch the library to change the redirect behaviour. Or someone could make a pull request which gives users more control over how the redirect is handled.

**Comment by vosime** [comment]
Hi Edmund,

i changed "redirect_url" with "resp.url".  Now it is working as expected. 

Thanks for the tip. :-)
BR

**Comment by quancore** [comment]
Can you share the relevant code for me as well @vosime ?

**Comment by vosime** [comment]
here is my code Edmund,

        if not redirect_location.netloc:
            # redirect_url = "%s://%s%s" % (parsed_url.scheme, domain, redirect_location.path)
            # return self.request(method, redirect_url, **original_kwargs)
            return self.request(method, resp.url, **original_kwargs)
