### ISSUE TITLE
Apidoc

### ISSUE THREAD

**Issue by ololoe** [Anorov/cloudflare-scrape#21]
Unfortunately, it's not that common that 3rd party python code contains apidoc, but it would be very helpful.

**Comment by ololoe** [comment]
Readme and code examples **do not** replace apidoc.

**Comment by Anorov** [comment]
If someone else wants to do this, I'd definitely accept a pull request. However, this module has so little functionality that I don't think it's worth my time to create a full API documentation page for it.

**Comment by int3l** [comment]
@ololoe what exactly do you mean by "apidoc"?
a.k.a, which tool/format for documentation do you mean?

**Comment by ololoe** [comment]
@int3l doesn't matter much.

**Comment by obskyr** [comment]
In this case, I actually think readme and code examples *do* replace an API reference. Pretty much all you need to keep track of is `cfscrape.create_scraper()` and beyond that it's pretty much just a normal requests `Session` - albeit with a few special cookies. An API reference would add little to nothing.

**Comment by ololoe** [comment]
Do you write your code in notepad++? Any IDE is able to show api docs.

**Comment by obskyr** [comment]
@ololoe It's a library with a single function you need to know, with only a literal couple of special properties, and it's got an API identical to requests.
