### ISSUE TITLE
Getting 302-Found without Set-Cookie

### ISSUE THREAD

**Issue by OmerBenGera** [Anorov/cloudflare-scrape#210]
When trying to bypass cloudflare, I am getting forwarded to the 302-Found page, but I don't receive the cf_clearance cookie.

I cannot use the get_tokens nor the get_cookie_string methods, as I must solve a recaptcha before it (which is done on my side and solves it without any problem)

Can you help me with this?

**Comment by OmerBenGera** [comment]
https://pastebin.com/cBjzcRN1
Here is my code - please, can anyone help me?

**Comment by Anorov** [comment]
If you upgrade cloudflare-scrape with `pip install -U cfscrape`, do you still experience this issue?
