### ISSUE TITLE
Problem with scrapy if cloudflare challenge occurred in the middle of crawling

### ISSUE THREAD

**Issue by partyspy** [Anorov/cloudflare-scrape#211]
I am trying to integrate this lib with scrapy. `cfscrape.get_tokens` works great when crawler starts but while crawling cloudflare challenge (503) may occur from time to time. Therefore I try to implement a middleware to handle the process, e.g. update the new cookies, but it seems that the 503 challenge can't be handled the right way and 503 keeps popping subsequently after the first one.

I don't know if it's just me doing this wrong. Might need some help I guess.
Here attached my code snippets.

```
    #spider snippet

    custom_settings = {
        'RETRY_HTTP_CODES': [500, 502, 504, 520, 400, 403, 404, 408], #remove 503
        'CONCURRENT_REQUESTS_PER_DOMAIN': 1,
        'AUTOTHROTTLE_ENABLED' : True,
        'AUTOTHROTTLE_TARGET_CONCURRENCY' : 1,
        'AUTOTHROTTLE_DEBUG': True,
    }

    def start_requests(self):
        for url in self.start_urls:
            # here works good
            token, self.user_agent = cfscrape.get_tokens(url)
            yield scrapy.Request(url=url, cookies=token, headers={'User-Agent': self.user_agent}, callback=self.parse_item)
```

If cloudflare 503 happened while crawling I try to deal with it in a middleware:

```
class CloudflareMiddleware(object):
    def __init__(self):
        self.logger = logging.getLogger('CloudflareMiddleware')
        self.tokens = None
        self.user_agent = None

    @staticmethod
    def is_cloudflare_challenge(response):
        """Test if the given response contains the cloudflare's anti-bot protection"""

        return (
            response.status == 503
            and response.headers.get('Server', '').startswith(b'cloudflare')
            and 'jschl_vc' in response.text
            and 'jschl_answer' in response.text
        )
    
    def process_response(self, request, response, spider):
        """Handle the a Scrapy response"""

        if not self.is_cloudflare_challenge(response):
            return response

        self.logger.info(
            'Cloudflare protection detected on %s, trying to bypass...',
            response.url
        )

        self.tokens, self.user_agent = cfscrape.get_tokens(request.url, user_agent=spider.user_agent)

        self.logger.info(
            'Successfully bypassed the protection for %s, re-scheduling the request',
            response.url
        )

        request.cookies.update(self.tokens)
        request.headers['User-Agent'] = self.user_agent
        request.priority = 900

        self.logger.debug('Re-schedule %s\n>>>New cookies: %s', request.url, self.tokens)

        return request

   # I tried to update the new cookies from cloudflare upon the consequent requests
    def process_request(self, request, spider):
        if self.tokens and self.user_agent:
            # if cloudflare 503 was met requests in queue should be updated
            self.logger.debug('>>>>>Update queued request Cookies')
            request.cookies.update(self.tokens)
            request.headers['User-Agent'] = self.user_agent
            request.priority = 900
            self.logger.debug('Re-schedule %s\n>>>New cookies: %s', request.url, self.tokens)

```
I set `'MyBot.middlewares.CloudflareMiddleware': 999,` in settings Downloader_Middleware.

In the middleware part if challenge occur, cfscrape.get_tokens() will start a new auth against cloudflare challenge instead of using the set-cookie returned by the 503 response. Subsequent requests after the 503 error one would continue to get 503 responses.

**Comment by pro-src** [comment]
Hi @partyspy , are you sure that the result of solving previous challenges is tested as a part of subsequent challenges???

`get_tokens` calls `create_scraper` to instantiate a `CloudflareScraper` class instant.
https://github.com/Anorov/cloudflare-scrape/blob/master/cfscrape/__init__.py#L176
But the keyword arguments are not passed to `create_scraper` so `cookies=<whatever>` is always dropped regardless of it's value.

You could call `create_scraper` directly with your arguments. The `CloudflareScraper` class is derived from `requests.Session`, it's base class. Whatever arguments you pass to `create_scraper` will be passed to `requests.Session` so at least that works as expected. Create a request with your new scraper (refer to this repo's markdown) to bypass the initial challenge and use the following snippet from `get_tokens` as a guideline for extracting the UA and cookies:

```py
        return ({
                    "__cfduid": scraper.cookies.get("__cfduid", "", domain=cookie_domain),
                    "cf_clearance": scraper.cookies.get("cf_clearance", "", domain=cookie_domain)
                },
```

Maybe you could just retain the scraper/session instance. I'd point to `requests` docs for any other information that you need to extract from the session/scraper instance.

**Comment by Anorov** [comment]
Can you try upgrading cloudflare-scrape with `pip install -U cfscrape` and see if you still experience this issue?
