### ISSUE TITLE
No connection adapters were found for '://www.google.com/' after 1.9.7 update

### ISSUE THREAD

**Issue by BarryThrill** [Anorov/cloudflare-scrape#214]
Hello guys!

I am using the latest version of 1.9.7 and I found an issue where I send a requests it ignores the https (Somehow gets removed and tries to do a request on ''://www.google.com/' instead). I have tried to use 'https://www.google.com/' and also other sites that contains https in the beginning and it still removes the https everytime it tries to solve a normal cloudflare (the one that you have to wait up to 5 sec.) 

I believe there has been an issue with the update that somehow deletes the https when doing a requests through cf_scrape. Is anyone having this issue aswell?

**Comment by lukastribus** [comment]
Post the code.

**Comment by Anorov** [comment]
Can you please try updating to the latest version (`pip install -U cfscrape`) and tell me if you're still experiencing this issue?
