### ISSUE TITLE
CloudFlare Updated!

### ISSUE THREAD

**Issue by 1trackprojects1** [Anorov/cloudflare-scrape#217]
Please update the code i think cloudflare updated their bot page.

**Comment by 1trackprojects1** [comment]
the module is not bypassing the page and giving the please wait html code from cloudflare

**Comment by Krylanc3lo** [comment]
Can you copy your error message ?

**Comment by 1trackprojects1** [comment]
there is no error when I request a cf page it gives me the cloudflare not html code and doesn't bypass it

**Comment by MrJohnSmith12** [comment]
Hey, just can confirm that CF updated it JS check again...

**Comment by pawliczka** [comment]
fixed #215

**Comment by 1trackprojects1** [comment]
> fixed #215

its not giving any error its just displaying the html of the anit-bot cf page and not bypassing

**Comment by pro-src** [comment]
@1trackprojects1 Somebody wrote another version of this library in #215 that should be working properly if you add the required request headers. TBH, I don't Anorov has the time to properly maintain this repository but he does merge PR's if they're decent. So that's your options. Send a PR to fix it or make use of the alternative in #215 that uses js2py. Good luck

**Comment by pawliczka** [comment]
#206 and you only have to add headers

**Comment by VeNoMouS** [comment]
#215 now finished using original js2py... all fixed and working , drop in replacement for the library , dont need to change any of your own project code.

**Comment by 1trackprojects1** [comment]
Can also send me the working source code? My while project depends on this module and also I don't understand where to put the #215 code in as I'm not getting any errors it's just not bypassing

**Comment by 1trackprojects1** [comment]
If someone wants to work with me on my project and knows how to make this module working then please message me mentioning me

**Comment by 1trackprojects1** [comment]
My project is in python and nodejs

**Comment by 1trackprojects1** [comment]
I'm also thinking of moving on to https://github.com/codemanki/cloudscraper/ as Anorov can't maintain a repo fml. If you have an other module that bypasses suggestions are welcomed

**Comment by pro-src** [comment]
@1trackprojects1 Once https://github.com/codemanki/cloudscraper/issues/80 is resolved, I plan on releasing my fork of cloudflare-scrape. It will depend on cloudscraper and bring the two projects to together. I haven't done any work on yet since https://github.com/codemanki/cloudscraper/issues/80 is blocking but for reference: https://github.com/pro-src/cloudscraper.py 

The API will remain the same but cloudscraper will do the heavy lifting.

**Comment by Fran008** [comment]
It's great to know that your project will keep the best things from Anorov's API and the best things from a well-mantained fork in codemanki.

I will be waiting for your combined work to be released. Thank you very much!

**Comment by 1trackprojects1** [comment]
I'll also be waiting I'll try to contribute too

**Comment by newt-sc** [comment]
@VeNoMouS @pro-src I've tried both solutions from
https://github.com/VeNoMouS/cloudflare-scrape-js2py and https://github.com/codemanki/cloudscraper
but they seem to fail for the following sites:
http://scene-rls.net , https://search.rlsbb.ru ,  https://movcr.cc
any ideas?

**Comment by pro-src** [comment]
@newt-sc I just tried all 3 of them with cloudscraper and bypassed them all. I got a captcha on first attempt for https://movcr.cc/ but second attempt yielded the desired content.

The version of cloudscraper that I'm using is of my PR https://github.com/codemanki/cloudscraper/pull/175 which adds the Accept-Encoding header.

You can add that header to cloudscraper v3.50 with the following which should cause the header to be added automatically.
```js
cloudscraper.defaultParams.gzip = true;
```

But for good measure, you might want to set the header explicitly:
```js
cloudscraper.defaultParams.gzip = true;
cloudscraper.defaultParams.headers['Accept-Encoding'] = 'gzip, deflate';
```

I'll take a more in-depth look at this later. If you find that there is an issue with cloudscraper that hasn't been addressed please open an issue at https://github.com/codemanki/cloudscraper

~Thanks

**Comment by newt-sc** [comment]
10x @pro-src adding:
```
cloudscraper.defaultParams.gzip = true;
cloudscraper.defaultParams.headers['Accept-Encoding'] = 'gzip, deflate';
```
fixed http://scene-rls.net , https://search.rlsbb.ru for me
but https://movcr.cc continues to fail with captcha after 5 attempts

**Comment by pro-src** [comment]
@newt-sc It's hit and miss when I test this. Since the PR is based on the master branch, the UA is randomized when the library is first loaded. I'm going to bet that the `Accept` header is inconsistent with the UA being used and Cloudflare is detecting that. 

```js
cloudscraper.defaultParams.headers['User-Agent'] = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36';
```

Even with :point_up: there's a chance that you'll get a CAPTCHA. This could be due to custom firewall configuration that the webmaster of https://movcr.cc has setup. If you don't mind, lets continue this discussion in a cloudscraper issue.

**Comment by VeNoMouS** [comment]
interesting... yea... can confirm "https://movcr.cc" does randomly break... will need to investigate this some more for my code.

**Comment by ebs111222** [comment]
@pro-src 
the code here solves it just fine
https://github.com/Anorov/cloudflare-scrape/issues/218

**Comment by lapwat** [comment]
@ebs111222 Which code ? There is code everywhere.
@VeNoMouS I have tested your version on coinmarketcap.com and it fails to pass the 5 seconds waiting page.

**Comment by VeNoMouS** [comment]
@lapwat did you test the dev branch, you know the algo changed again today right?

**Comment by VeNoMouS** [comment]
also "coinmarketcap.com" isnt behind cf...

**Comment by pro-src** [comment]
@VeNoMouS I don't think the index page is but iirc there are resources on that domain that will return a cloudflare challenge.

**Comment by pro-src** [comment]
@VeNoMouS https://github.com/codemanki/cloudscraper/issues/164

**Comment by lapwat** [comment]
This one for example :
https://coinmarketcap.com/currencies/bitcoin/historical-data/

**Comment by VeNoMouS** [comment]
@lapwat the example you posted then removed... is not behind cf..

**Comment by VeNoMouS** [comment]
well... it is... but not DDOS protection... you can access that with curl or lynx from cmd line ...

**Comment by VeNoMouS** [comment]
There is no challenge response...

**Comment by pro-src** [comment]
@VeNoMouS I remember now. The 100 URLs from the issue that I linked would return HTTP `429 - Too Many Requests` with a challenge response if you made serial requests.

**Comment by VeNoMouS** [comment]
anyway... going sleep... night.

**Comment by pro-src** [comment]
Gn, Cloudflare is going to update while you're asleep. lol

**Comment by lapwat** [comment]
https://coinmarketcap.com/currencies/bitcoin/historical-data/ is protected, try to call it 100 times and it will challenge
Good night

**Comment by doko-desuka** [comment]
@lapwat if you look at that page there's a Tools tab, and in there there's [a widget that shows the data](https://coinmarketcap.com/widget/?c=bitcoin).
You don't need to scrape the website, use the code from the widget, it's a JSON response:

`https://widgets.coinmarketcap.com/v2/ticker/1/?ref=widget&convert=USD`

```
{
    "data": {
        "id": 1, 
        "name": "Bitcoin", 
        "symbol": "BTC", 
        "website_slug": "bitcoin", 
        "rank": 1, 
        "circulating_supply": 17627062.0, 
        "total_supply": 17627062.0, 
        "max_supply": 21000000.0, 
        "quotes": {
            "USD": {
                "price": 5011.24700498, 
                "volume_24h": 21603768947.1024, 
                "market_cap": 88333561654.0, 
                "percent_change_1h": 0.72, 
                "percent_change_24h": 0.25, 
                "percent_change_7d": 22.8
            }, 
            "BTC": {
                "price": 1.0
            }
        }, 
        "last_updated": 1554381630
    }, 
    "metadata": {
        "timestamp": 1554380526, 
        "error": null
    }
}
```

Response is 1KB vs 75KB of the full page..

**Comment by lapwat** [comment]
@doko-desuka Thanks for the tip. I am actually looking for a way to grab the close price of a currency for a certain day, not the price in real time.

**Comment by pawliczka** [comment]
I recommend @VeNoMouS 's https://github.com/VeNoMouS/cloudflare-scrape-js2py . His fork is always up to date with cloudflare. He is doing a good job. I am very grateful!

**Comment by VeNoMouS** [comment]
Try out my new project ["cloudscraper"](https://pypi.org/project/cloudscraper/) the new git repo can be found [here](https://github.com/VeNoMouS/cloudscraper).
