### ISSUE TITLE
syntax error at importing

### ISSUE THREAD

**Issue by Der-Eddy** [Anorov/cloudflare-scrape#22]
After upgrading cfscrape with pip, now I'm unable to import cfscrape
![Screenshot](http://abload.de/img/2015-07-20144555i9oj7.png)
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\tools\python\lib\site-packages\cfscrape\__init__.py", line 107
    print "'%s' returned error %d, could not collect tokens.\n" % (url, resp.status_code)
                                                              ^
SyntaxError: invalid syntax
```

I get the same error on my windows (8.1) and linux (Ubuntu 14.04) machine and both running Python 3.4.2

Am I doing something wrong? I tried to uninstall cfscrape and installed it again  
also PyExecJS and requests are the latest version

**Comment by Newman101** [comment]
Looks like it's working on Python 2.7 and iPython. How ever, there are some changes on print. They have replaced print statement with print function.

https://docs.python.org/3.3/library/functions.html?highlight=print#print

Looks like __init__.py tries to print out the error message using print statement, so this is why it happens. I can fix and send a PR if needed.

**Comment by Newman101** [comment]
Done, please see pull request #23.
