### ISSUE TITLE
New CF update

### ISSUE THREAD

**Issue by hypnotd** [Anorov/cloudflare-scrape#220]
Error encountered: https://pastebin.com/Hs43FNLm

Happening every time I send a request to a site with CF challenge.

**Comment by armin884** [comment]
same error here....

**Comment by aidanngill** [comment]
Got this as well

**Comment by mickae1** [comment]
@wintermutt  @0xdkay any news on the fix ?

**Comment by lukele** [comment]
@mickae1 You can use my working branch:
https://github.com/lukele/cloudflare-scrape/tree/update-challenge-solver/cfscrape

**Comment by 0xdkay** [comment]
@mickae1 you can use my commit temporarily. I don't know when this issue is fixed as I'm not one of the contributors.

**Comment by iain-benson** [comment]
> @mickae1 You can use my working branch:
> https://github.com/lukele/cloudflare-scrape/tree/update-challenge-solver/cfscrape

Thanks ... that seems to fix it!

**Comment by zrahman001** [comment]
@lukele using your branch but getting the following error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "cfscrape.py", line 84, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "cfscrape.py", line 134, in solve_cf_challenge
    redirect_location = urlparse(redirect.headers["Location"])
  File "/usr/local/lib/python2.7/dist-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'

**Comment by lukele** [comment]
@zrahman001 This might mean that Cloudflare is sending you a page with captcha. If you add a print(redirect.text) before line 134 and post the output this might help debug this. (best use some kind of pastebin to paste the output. Or a gist)

**Comment by zunjae** [comment]
A temporarily solution without modifying too much code is to add this file to your project https://raw.githubusercontent.com/lukele/cloudflare-scrape/update-challenge-solver/cfscrape/__init__.py and import it like `import cfscrape_fork as cfscrape`

**Comment by lukastribus** [comment]
@zunjae just safe the file as cfscrape.py and you don't have to modify a single digit of your code.

**Comment by zunjae** [comment]
@lukastribus you mean line instead of digit, right? Anyway. That's bad practice cause it means I got a dependency that can't get updated automatically. I don't want to rely on you

**Comment by lukastribus** [comment]
I mean you don't have to change anything.

It's not a fork, its the PR branch from #206, its a workaround until that PR is merged and a new release is published. 

Everyone is fully aware that this is a temporary workaround.

**Comment by zunjae** [comment]
No matter how you see it there's still a dependency to a non (official) main branch (like you call it, a PR branch). I don't like that.

**Comment by lukastribus** [comment]
Nobody does.

**Comment by zrahman001** [comment]
> @zrahman001 This might mean that Cloudflare is sending you a page with captcha. If you add a print(redirect.text) before line 134 and post the output this might help debug this. (best use some kind of pastebin to paste the output. Or a gist)

@lukele - here you go https://pastebin.com/XgFG0Ji6
hope this helps

**Comment by lukele** [comment]
@zrahman001 can you share the code leading to this problem? Is the first call a POST call? Cloudflare shows the captcha site for various reasons, one is that your IP is blocked, but could also be a POST call before a GET call.

**Comment by bato3** [comment]
I'm thinking, that  it is this last string: `.toFixed(10); '; 121'
`

**Comment by Hyperz** [comment]
> 
> 
> @zrahman001 can you share the code leading to this problem? Is the first call a POST call? Cloudflare shows the captcha site for various reasons, one is that your IP is blocked, but could also be a POST call before a GET call.

Not him but I'm running into the same problem.  It's indeed returning a 403 page with a captcha challenge after submitting the initial challenge answer. The thing though is that when I load the same page in Firefox it just gives me the normal challenge without a captcha. So it seems something is causing CF to be suspicious when solving it with cfscrape.

**Comment by VeNoMouS** [comment]
Try out my new project ["cloudscraper"](https://pypi.org/project/cloudscraper/) the new git repo can be found [here](https://github.com/VeNoMouS/cloudscraper).

**Comment by hallwayorchard** [comment]
> @zunjae just save the file as `cfscrape.py` and you don't have to modify a single digit of your code.

Apologies as I'm a bit new to this... I'm having trouble knowing where to place this workaround cfscrape.py on my system. Any advice?

**Comment by dci2112** [comment]
> Try out my new project ["cloudscraper"](https://pypi.org/project/cloudscraper/) the new git repo can be found [here](https://github.com/VeNoMouS/cloudscraper).

How can cloudscraper be integrated into SickChill to replace cfscrape?

**Comment by VeNoMouS** [comment]
it's almost a drop in replacement, check the readme for the slight changes...

**Comment by dci2112** [comment]
I'm on a QNAP NAS, and can't get setup.py to run--it is indeterminate which python package QSickChill (https://www.qnapclub.eu/en/qpkg/647) is using. I installed python from the same repo(https://www.qnapclub.eu/en/qpkg/647). Neither the system python in /usr/local/bin (2.7.5) nor the python included in the QSickChill package can run the setup.py due to missing modules or undefined symbols. I guess I'll have to wait till there's a formalized fix for the QSickChill package.

**Comment by dci2112** [comment]
OK, I got the QNAP installation of cloudscraper figured out:

(You need Entware installed to get the ca certificates installed so SSL will not complain about connections to HTTPS)

`opkg install ca-certificates `

Then we can install the python packages using the python included with the QSickChill package:

`
ln -s /share/CACHEDEV1_DATA/.qpkg/QSickChill /opt/SickChill
export PATH=/opt/SickChill/bin:$PATH
pip install --upgrade pip
pip install setuptools --upgrade
pip install cloudscraper
`

Then we can modify the calls to cfscrape to replace those with cloudscraper. [instructions to be edited later]

**Comment by VeNoMouS** [comment]
disable_pyimport is from the default interprerter `js2py`

**Comment by VeNoMouS** [comment]
@dci2112 if you're wanting to use node... as per the documentation
```
 session.interpreter = 'nodejs'
```

**Comment by VeNoMouS** [comment]
Also want to raise this issue in my repo rather than Anorov's as its related to my project.

**Comment by dci2112** [comment]
> disable_pyimport is from the default interprerter `js2py` , perhaps your js2py package doesn't have `disable_pyimport` , it should though... what is the `pip freeze` for js2py?


```
[/share/CACHEDEV1_DATA/.qpkg/QSickChill] # pip freeze js2py                                           
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
asn1crypto==0.24.0
Brotli==1.0.7
certifi==2019.3.9
cffi==1.11.5
chardet==3.0.4
cloudscraper==1.1.2
cryptography==2.3.1
enum34==1.1.6
idna==2.7
ipaddress==1.0.22
Js2Py==0.63
lxml==4.2.5
netifaces==0.10.7
pycparser==2.19
pycrypto==2.6.1
pycurl==7.43.0.2
pyjsparser==2.7.1
pyOpenSSL==18.0.0
pytz==2019.1
requests==2.21.0
requests-toolbelt==0.9.1
six==1.11.0
tzlocal==1.5.1
urllib3==1.24.2
```

**Comment by frozenpandaman** [comment]
> You can use my working branch:
> https://github.com/lukele/cloudflare-scrape/tree/update-challenge-solver/cfscrape

@lukele Seems this version is now broken as well.
