### ISSUE TITLE
JAVASCRIPT CLOUDFARE PROTECTED WEB SERVERS

### ISSUE THREAD

**Issue by micahunder** [Anorov/cloudflare-scrape#225]
I was Testing Evilginx2, which is supposed to help me bypass 2FA on web servers by using the MITM proxy phishing attack.
I run the test on couple of web servers 
I decided to try this project out with web servers using Cloud fare based JavaScript security to mitigate MITM proxy phishing techniques such Evilginx2.
Been facing problems for a while now.

This leaves my phishing domain hanging on cloud fare's DDOS protection page with the text below.

Checking your browser before accessing cloudflare-protected.site.
This process is automatic. Your browser will redirect to your requested content shortly.
Please allow up to 5 seconds…
DDoS protection by Cloud flare
Ray ID:

Anyway I can address this issue? Thank you.

**Comment by giacomoferretti** [comment]
You have a problem with this library? Can you send some logs? Thanks.

**Comment by Karmel0x** [comment]
Related to [this issue](https://github.com/Karmel0x/cloudflare-js-bypass/issues/2).
