### ISSUE TITLE
Html response 403

### ISSUE THREAD

**Issue by MartenM** [Anorov/cloudflare-scrape#226]
Hey there,

I am currently using this branch: https://raw.githubusercontent.com/lukele/cloudflare-scrape/update-challenge-solver/cfscrape/__init__.py. It seems to be the same as this one so that's why I put the issue here.

The code I try to execute:
```
import cfscrape

with cfscrape.create_scraper() as session:
    page = session.get("https://www.leet.ws/s4d6")

    print(page.text)
```

The error: 
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    page = session.get("https://www.leet.ws/s4d6")
  File "C:\Users\Marten\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "D:\development\py3\leet\badges\cfscrape.py", line 84, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "D:\development\py3\leet\badges\cfscrape.py", line 134, in solve_cf_challenge
    redirect_location = urlparse(redirect.headers["Location"])
  File "C:\Users\Marten\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
```

I printed the header and it seems to come from the fact that the response code is a 403, acces forbidden. Now, this is very weird because I can acces the page normally using my browser. 
Any help would be appreciated.

**Comment by MartenM** [comment]
Seems that I get a captcha in return. That's not going to get fixed anytime soon sadly.

**Comment by Hyperz** [comment]
> 
> 
> Seems that I get a captcha in return. That's not going to get fixed anytime soon sadly.

Do you get a captcha in your browser as well? Because I have at least one site where I get a 403 (with captcha) with cfscrape, but only a normal check in my browser. So my guess is they are doing some kind of fingerprinting or some difference in behavior is causing it to be more suspicious of cfscrape/requests calls.

**Comment by MartenM** [comment]
> Do you get a captcha in your browser as well?

Nope. I have seen some approaches that spoof cloud flare using your own browsers user agent and cookies but I am not too sure if that works. (So you could manually do the captcha)

Luckily for me, the issue dissapeard for some reason and I am back at having 'normal' cf challenges.

**Comment by MartenM** [comment]
Considering the fact that it was a captcha that was the issue here I am closing this issue.
