### ISSUE TITLE
Error while scrapping cloudflare page

### ISSUE THREAD

**Issue by milansen** [Anorov/cloudflare-scrape#228]
Getting error 503 server not available while trying to connect an Uri protected by CloudFlare.
I am trying to get the content of the url 👍 
https://adviserinfo.sec.gov/IAPD/InvestmentAdviserData.aspx
When I am trying to get the content of that page using 
scraper.get("https://adviserinfo.sec.gov/IAPD/InvestmentAdviserData.aspx").content in python after importing cfscrape package its still showing the content of the 5 second waiting page from CloudFlare but if we hit the url in browser after waiting a while original content of the page is showing.
Please suggest how we can skip the CloudFlare page to download file from that url or get the content of the page.

**Comment by giacomoferretti** [comment]
You can't skip the CloudFlare page as all the requests made to your target site pass through their servers. You need to complete the challenge first to get the real page. The challenge has been updated since the last commit to this repo, so you have to wait for someone to fix it.

**Comment by devgianlu** [comment]
Check https://github.com/Anorov/cloudflare-scrape/issues/220#issuecomment-482972962

**Comment by giacomoferretti** [comment]
Thanks, didn't see it.

**Comment by milansen** [comment]
Thanks  for the help. The Python code #220 comment is working. 
Is there a C# code version to handle this CloudFlare issue, as we were scrapping the site using C# console application.

**Comment by devgianlu** [comment]
Not that I know of. I can put my Java implementation in a gist if you need it.

**Comment by milansen** [comment]
please, that will be helpful.

**Comment by devgianlu** [comment]
https://gist.github.com/devgianlu/54211220f5b4e44bc3b5e052031dc391

**Comment by VeNoMouS** [comment]
Try out my new project ["cloudscraper"](https://pypi.org/project/cloudscraper/) the new git repo can be found [here](https://github.com/VeNoMouS/cloudscraper).
