### ISSUE TITLE
What is the status of this project

### ISSUE THREAD

**Issue by pro-src** [Anorov/cloudflare-scrape#233]
@Anorov Nobody has heard from you. While some work has been done elsewhere to keeps things working in your absence, I can appreciate the single file and minimal solution that you have here. I can send a PR that makes the least possible amount of changes (same single file, minimal design) to return cloudflare-scrape to working order. If you are still willing to maintain this project, I'll send it.

Thanks

**Comment by pro-src** [comment]
@Anorov Ping.

**Comment by Anorov** [comment]
The project's not dead yet. I plan to get it functional again. Do you believe your proposed changes are better or more comprehensive than https://github.com/Anorov/cloudflare-scrape/pull/206?

**Comment by pro-src** [comment]
@Anorov That's great news!

> Do you believe your proposed changes are better or more comprehensive than #206?

Yes, although that PR can solve the current challenges if a CAPTCHA isn't sent. I will send you a PR for you to review sometime this evening and elaborate more on those changes.

**Comment by Anorov** [comment]
That would be great, thank you. I'll almost definitely defer to your PR. I was planning to dig into this and make the appropriate updates, but I don't have very much time lately and a lot of people have already done a lot of research into this, so I appreciate the contribution.
