### ISSUE TITLE
Breaking things up

### ISSUE THREAD

**Issue by pro-src** [Anorov/cloudflare-scrape#248]
As fixes and features are added to this library things can quickly become bloated.
This library is still small but to aid future contributors and preserve code manageability, I propose restructuring the library now rather than later. I recommend modeling after `requests`.

For a quick comparison of what I aim to avoid, consider another extremely popular request library.

Bloated: https://github.com/request/request/blob/master/request.js
It took the poor guy quite a bit of time to refactor the library: https://gist.github.com/simov/552bee6ce6001205393e
It hasn't happened yet: https://github.com/request/request/issues/1982 :cry: 

This is what I imagine the `__init__.py` would initially look like.
```py
from .adapters import CloudflareAdapter, DEFAULT_CIPHERS
from .exceptions import CloudflareError, CloudflareCaptchaError
from .api import request, get, head, post, patch, put, delete, options

from .scraper import CloudflareScraper, user_agents, \
    DEFAULT_USER_AGENT, DEFAULT_HEADERS  

__version__ = "2.0.4"

create_scraper = CloudflareScraper.create_scraper
get_tokens = CloudflareScraper.get_tokens
get_cookie_string = CloudflareScraper.get_cookie_string
```

Modeled after `requests`, you could perform the following:
```py
import cfscrape
cfscrape.get(url)
```

This idea also makes for better tests.

**Comment by Anorov** [comment]
👍

**Comment by pro-src** [comment]
@Anorov 

Before I send a PR for this, I was wondering about the api module. It would ideally be a slightly modified version of `requests/api.py` which means we'd need to comply with the Apache2 license. I'm not exactly sure how/if it would affect the project's license by bundling a partially Apache2 licensed source file. If we did that, we'd also want to include a NOTICE file. I know how to create the appropriate source file header but do we want to include the Apache2 LICENSE in a separate file or dual license, etc. etc..

This may have been the reason why it wasn't included in the first place? I've looked at monkey-patching a separately loaded copy of the api module and getting that to work on python 2 and 3....Too hacky but it would resolve the above issues.

If the source is guaranteed to be available, the following seems safe enough:
```py
from inspect import getsource
from requests.api import *
from . import CloudflareScraper


def request(method, url, **kwargs):
    with CloudflareScraper() as scraper:
        return scraper.request(method=method, url=url, **kwargs)


for x in (get, head, post, patch, put, delete, options):
    # getsource is not very efficient when being called for the same file multiple times
    # So this could be optimized
    exec(getsource(x))
del x
```
I'm not sure if tools like pyInstaller would break it or not though...
So, I'm out of ideas. Do you want to include a modified version of `requests/api.py` and if so, how should we handle the license issues? It's very possible that I'm over thinking this, please correct me if I'm wrong.

**Comment by pro-src** [comment]
https://github.com/pro-src/cloudflare-scrape/tree/248_refactor/cfscrape

**Comment by Anorov** [comment]
Should we persist a session for multiple invocations of `cfscrape.{request,get,post,...}`, so that the challenge handling will only happen once if someone calls `cfscrape.request` against the same domain twice? This would break some compatibility with requests, but I can't think of potential pitfalls at the moment. Alternatively, we could just have some logic to re-add the cookies in the `request` method, but using a shared session might be simpler.

I'm not sure what the licensing implications might be, but if you think this is a good approach, could we create our own api.py which follows requests' public API but uses this different shared session implementation? If so, would that maybe prevent licensing issues?

**Comment by pro-src** [comment]
Yes on all counts. I think that I've over thought it and that this is really a functional and fair-use case.
