### ISSUE TITLE
Post request - Connection website

### ISSUE THREAD

**Issue by tjukoela** [Anorov/cloudflare-scrape#25]
Hi,

When i try to connect at this website : http://ascalion.eu i'm not connected.

Username : fortest1
password : fortest1

My code : http://paste.isomorphis.me/EmB&ln

Steps are : 
- post requests with data to ascalion.eu/connexion
- get requests to check if my connection is etablished, but in response content i havent "connected as fortest1", normally it was printed when i'm connected (via web browser)

I dont know why it doesnt work..

Is this a bug ?

Ps : the username and password are for testing, you can use them without any problems.

Regards,

**Comment by Anorov** [comment]
It appears this site is requiring a captcha to visit it.

cloudflare-scrape is unable to bypass Cloudflare's captchas. It only bypasses Cloudflare's default anti-bot/anti-scraping protection.

**Comment by tjukoela** [comment]
When i made a classical visit in this website with my browser, i never put any captcha, what do you say for "all cookies", do you speak about first post response headers ? (if yes, there are 2 set cookies and i dont know why).

Can you be more explicit to solve my problems ?
