### ISSUE TITLE
Problem with scraper

### ISSUE THREAD

**Issue by zakhavan** [Anorov/cloudflare-scrape#254]
Before creating an issue, first upgrade cfscrape with `pip install -U cfscrape` and see if you're still experiencing the problem.

## Version number

Run `pip show cfscrape` and paste the output below:

Name: cfscrape
Version: 2.0.5
Summary: A simple Python module to bypass Cloudflare's anti-bot page. See https://github.com/Anorov/cloudflare-scrape for more information.
Home-page: https://github.com/Anorov/cloudflare-scrape
Author: Anorov
Author-email: anorov.vorona@gmail.com
License: UNKNOWN
Location: /home/zeinab/.local/lib/python2.7/site-packages
Requires: requests
Required-by: 
You are using pip version 18.0, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

## Code snippet experiencing the issue

import cfscrape

scraper = cfscrape.create_scraper()  # returns a CloudflareScraper instance
# Or: scraper = cfscrape.CloudflareScraper()  # CloudflareScraper inherits from requests.Session
print scraper.get("https://forum.bitcoin.com/ico-announcements-f120/").content  # => "<!DOCTYPE html><html><head>..."

## Complete exception and traceback

(*If the problem doesn't involve an exception being raised, leave this blank*)

Traceback (most recent call last):
  File "scrape.py", line 6, in <module>
    print scraper.get("https://forum.bitcoin.com/ico-announcements-f120/").content  # => "<!DOCTYPE html><html><head>..."
  File "/home/zeinab/.local/lib/python2.7/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/home/zeinab/.local/lib/python2.7/site-packages/cfscrape/__init__.py", line 132, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/home/zeinab/.local/lib/python2.7/site-packages/cfscrape/__init__.py", line 185, in solve_cf_challenge
    answer, delay = self.solve_challenge(body, domain)
  File "/home/zeinab/.local/lib/python2.7/site-packages/cfscrape/__init__.py", line 284, in solve_challenge
    ["node", "-e", js], stdin=subprocess.PIPE, stderr=subprocess.PIPE
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

## URL of the Cloudflare-protected page

[https://forum.bitcoin.com/ico-announcements-f120/]

## URL of Pastebin/Gist with HTML source of protected page

[view-source:https://forum.bitcoin.com/ico-announcements-f120/]

**Comment by pro-src** [comment]
Hi @zakhavan,

Unfortunately this is an OS related permission error that has nothing to do with cfscrape or even Python.
I would make sure that you have proper file permissions in place that allow Python to read and execute "node".

**Comment by zakhavan** [comment]
Thank you for your reply. Do you know how I can fix it?

**Comment by pro-src** [comment]
You're welcome.

I don't use Windows so I can't tell you exactly how to fix it off the top of my head but it shouldn't be hard to fix. All you really have to do is correct the permissions on the Node.js executable. Finding that executable file and changing those permissions is where you might struggle.

Just google it. I don't recommend running cfscrape as an administrator but here is a random StackOverflow Question & Answer: https://stackoverflow.com/questions/36434764/permissionerror-errno-13-permission-denied

If you can't figure this out. Ask on https://stackoverflow.com
I'm guessing that this has been asked many,many,many times so please take the time to research the problem properly. It is a file permissions problem.

I hope you get it working soon! :smiley:

**Comment by zakhavan** [comment]
I'm using linux. Thank you very much for the links. I will look into them.

**Comment by pro-src** [comment]
@zakhavan 

I'm giving you a few pointers as a courtesy but I can't help any further.
Start `cmd.exe` as an Administrator.  You should be able to do that by searching for `cmd.exe` from the start menu and right clicking to spawn the content menu which has a "Run as Administrator" option.

Find the executable: `where.exe node*`
Give users full control over the file: `icacls "PATH" /grant Users:F` <-- Replace `PATH` with the path found.

**Comment by pro-src** [comment]
@zakhavan 

Oh... Duhh... Okay `chmod a+x $(which node)`

**Comment by zakhavan** [comment]
Thank you so much.
