### ISSUE TITLE
Node.js version exception

### ISSUE THREAD

**Issue by Anorov** [Anorov/cloudflare-scrape#255]
We should generate an exception for Node versions lower than 4.5, with instructions to upgrade to a newer version.

Related:

https://github.com/Anorov/cloudflare-scrape/issues/241
https://github.com/Anorov/cloudflare-scrape/issues/253

**Comment by pro-src** [comment]
I see a few ways of doing this:
* Generating the error from python by checking `node --version`.
* Generating the error from node by checking `process.version` or `process.versions.node`.
* Generating the error from node by performing a feature test.

The feature test option seems to be the easiest and most efficient way of doing this.

```js
if (typeof Buffer.from !== 'function') {
    throw new Error('Old Node.js version detected: ' + process.version);
}
```
