### ISSUE TITLE
Captcha issues on ww1.torrent9.nz

### ISSUE THREAD

**Issue by pro-src** [Anorov/cloudflare-scrape#259]
Related #235 

The error is occurring on version 2.0.5,  at least when using older openssl versions. Currently unable to reproduce on my own system.

Steps to reproduce outside of SickChill:
<details><summary>Code snippet</summary>

```py
import uuid
import platform
import cfscrape

INSTANCE_ID = str(uuid.uuid1())
USER_AGENT = ('SickChill.CE.1/(' + platform.system() + '; ' + platform.release() + '; ' + INSTANCE_ID + ')')

scraper = cfscrape.create_scraper()
scraper.headers.update({'User-Agent': USER_AGENT, 'Accept-Encoding': 'gzip,deflate'})
scraper.get('https://ww1.torrent9.nz')
```
</details>

First reported here: https://github.com/SickChill/SickChill/issues/5512 and here: https://github.com/SickChill/SickChill/issues/5515
 
Please generate a report with this [script](https://gist.github.com/pro-src/17654ec3f949b0b17bd1a4aa1b4136b9).

*This must be ran from within the cloned cloudflare-scrape repo if you haven't pip installed cfscrape*
```sh
git clone https://gist.github.com/pro-src/17654ec3f949b0b17bd1a4aa1b4136b9 temp
cp temp/report.py report.py
python report.py
```

Report: http://dpaste.com/0FEE3BX

**Comment by pro-src** [comment]
@janusn,

Please let me know if you have any problems or questions about running the report generator. Depending on the results I'll be able to narrow down the problem and/or determine whether there is a workaround for you. As of date, this never happens when using TLSv1.1 but that is a security trade-off so I don't want to recommend it right away.

**Comment by janusn** [comment]
@pro-src,

I would like to help but I have problem installing cloudflare-scrape.

I am not familiar with python or pip. As the sickchill is running on a Synology NAS, I don't know how to install pip. Hence, I tried to install cloudflare-scrap from github clone.

It returned the following errors:
`~/git$ git clone https://github.com/Anorov/cloudflare-scrape.git cloudflare-scrape
Cloning into 'cloudflare-scrape'...
remote: Enumerating objects: 511, done.
remote: Total 511 (delta 0), reused 0 (delta 0), pack-reused 511
Receiving objects: 100% (511/511), 431.66 KiB | 517.00 KiB/s, done.
Resolving deltas: 100% (221/221), done.
~/git$ cd cloudflare-scrape
~/git/cloudflare-scrape$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup
ImportError: No module named setuptools`

Could you help me out?
Thank you!

**Comment by pro-src** [comment]
This [stackoverflow article](https://stackoverflow.com/a/24733673) details how to install pip on Windows. The pip installer will install setuptools as well so this should resolve all of the errors.

**Comment by pro-src** [comment]
On Linux: `sudo apt install python-pip -qfy`

**Comment by janusn** [comment]
@pro-src,

Thanks for your reply. Though apt and apt-get are not included in DSM, I understand installing pip is a must. I installed it by other means from searching the web.

Here is the output of the report.py:

> ~/git$ python report.py 
> 
> Please test with Python >= 3.5 not Python 2.7.12 (default, Apr 25 2019, 14:50:28) 
> [GCC 4.9.3 20150311 (prerelease)]
> Checking GET request for https://ww1.torrent9.nz DEFAULT
> Checking GET request for https://ww1.torrent9.nz DEFAULT
> No CAPTCHA encountered under normal conditions.
> Checking to see which ciphers are shared as reported by https://howsmyssl.com v1
> Checking to see which ciphers are shared as reported by https://howsmyssl.com v2
> Checking to see which ciphers are shared as reported by ssllabs v1
> The protocols details reported by ssllabs are not unique. v1
> Unique signature algorithms were detected by ssllabs. v1
> Uniquely named groups were detected by ssllabs. v1
> Checking to see which ciphers are shared as reported by ssllabs v2
> The protocols details reported by ssllabs are not unique. v2
> Unique signature algorithms were detected by ssllabs. v2
> Uniquely named groups were detected by ssllabs. v2
> Checking GET request for https://ww1.torrent9.nz TLSv1.1 v1
> Checking GET request for https://ww1.torrent9.nz TLSv1.1 v1
> No CAPTCHA encountered when using TLSv1.1 v1
> Checking GET request for https://ww1.torrent9.nz DEFAULT :!ECDHE+SHA:!AES128-SHA v1
> Checking GET request for https://ww1.torrent9.nz DEFAULT :!ECDHE+SHA:!AES128-SHA v1
> No CAPTCHA encountered when using :!ECDHE+SHA:!AES128-SHA v1
> Checking GET request for https://ww1.torrent9.nz TLSv1.1 v2
> Checking GET request for https://ww1.torrent9.nz TLSv1.1 v2
> No CAPTCHA encountered when using TLSv1.1 v2
> Checking GET request for https://ww1.torrent9.nz DEFAULT :!ECDHE+SHA:!AES128-SHA v2
> Checking GET request for https://ww1.torrent9.nz DEFAULT :!ECDHE+SHA:!AES128-SHA v2
> Checking GET request for https://ww1.torrent9.nz DEFAULT :!ECDHE+SHA:!AES128-SHA v2
> No CAPTCHA encountered when using :!ECDHE+SHA:!AES128-SHA v2
> The report was saved locally as "report.md"
> The report is valid Github flavored markdown, you may copy and paste it.
> The dpaste link (Expires in 10 days): http://dpaste.com/2B0NM2D

Is python 2.7 incompatible with sickchill with cloudscrape?

**Comment by pro-src** [comment]
Interesting... The report seems to indicate that the ciphers aren't responsible. There can be a difference in ciphers between python versions but cloudflare-scrape works with both. Probably should re-run with python 3 just to make sure there isn't a problem there either.

Are you still experiencing the problem in SickChill?
Please execute this minimal test case to see if you can reproduce the error.
```py
import uuid
import platform
import cfscrape

INSTANCE_ID = str(uuid.uuid1())
USER_AGENT = ('SickChill.CE.1/(' + platform.system() + '; ' + platform.release() + '; ' + INSTANCE_ID + ')')

scraper = cfscrape.create_scraper()
scraper.headers.update({'User-Agent': USER_AGENT, 'Accept-Encoding': 'gzip,deflate'})
scraper.get('https://ww1.torrent9.nz')
```
If you do get a CAPTCHA error when using this snippet then perhaps it's the headers...

**Comment by pro-src** [comment]
@jansun,

I've determined the problem. The CacheControl adapter used by SickChill is replacing the adapter used by cloudflare-scrape. https://github.com/SickChill/SickChill/blob/master/lib/cachecontrol/wrapper.py

I'll send a PR downstream to fix this up.
Thanks for your patience and troubleshooting!

**Comment by janusn** [comment]
@pro-src 

Thanks for your effort! I really appreciate!

By the way running your script output nothing.

> ~$ cat cloudflare-scrape-test-captcha.py 
> import uuid
> import platform
> import cfscrape
> 
> INSTANCE_ID = str(uuid.uuid1())
> USER_AGENT = ('SickChill.CE.1/(' + platform.system() + '; ' + platform.release() + '; ' + INSTANCE_ID + ')')
> 
> scraper = cfscrape.create_scraper()
> scraper.headers.update({'User-Agent': USER_AGENT, 'Accept-Encoding': 'gzip,deflate'})
> scraper.get('https://ww1.torrent9.nz')
> 
> ~$ python cloudflare-scrape-test-captcha.py 
> ~$ 
>

**Comment by pro-src** [comment]
> Thanks for your effort! I really appreciate!

You're welcome, I appreciate yours as well.

> By the way running your script output nothing.

No CAPTCHA :wink:
I'll let you know as soon as this has been fixed.

**Comment by pro-src** [comment]
@janusn https://github.com/SickChill/SickChill/pull/5516
