### ISSUE TITLE
Support sending Cookies back to the Website

### ISSUE THREAD

**Issue by scrimpy** [Anorov/cloudflare-scrape#26]
Hi, your script is really nice, i like it and got it to work.
Iam trying to open a website with it, that asks for an extra cookie code to be send back.

The response after the Cloudflare message is:

eval(function(p,a,c,k,e,r){e=function(c){return c.toString(a)};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('1 6(){2.3=\'4=5; 0-7=8; 9=/\';a.b.c()}',13,13,'max|function|document|cookie|cookie|11a33cdf483ad2022a0da8abd2eac2a7d9015fb6|challenge|age|1600|path|window|location|reload'.split('|'),0,{}))

the cookie=11a33cdf483ad2022a0da8abd2eac2a7d9015fb6 needs to be send back
i tried many ways, with scraper.get etc
but nothing, do you know the trick?

**Comment by Anorov** [comment]
This does not appear to be related to Cloudflare or cloudflare-scrape. I'd recommend consulting the documentation for the Requests library.
