### ISSUE TITLE
Proxy not working

### ISSUE THREAD

**Issue by Xonshiz** [Anorov/cloudflare-scrape#260]
## Issue :
I can't get the proxies to work. I'm passing them, as suggested in the Read Me. And I've cross checked the REQUESTS module as well (I mean, how to pass proxy in it). But, it just won't work. The proxy gateway itself is working fine, as curl fetches the pages with that IP just fine.

## Version number
2.0.7

Run `pip show cfscrape` and paste the output below:
```
Name: cfscrape
Version: 2.0.7
Summary: A simple Python module to bypass Cloudflare's anti-bot page. See https://github.com/Anorov/cloudflare-scrape for more information.
Home-page: https://github.com/Anorov/cloudflare-scrape
Author: Anorov
Author-email: anorov.vorona@gmail.com
License: UNKNOWN
Location: /Library/Python/2.7/site-packages
Requires: requests
Required-by: 
```

## Code snippet experiencing the issue

```
url = "https://www.crunchyroll.com/black-clover"
sess = session()
sess = create_scraper(sess, delay=scrapper_delay)
connection = sess.get(url, headers=headers, cookies=cookies_received, proxies={"http": "95.179.230.213:4000"})
```

and I've tried :
```
url = "https://www.crunchyroll.com/black-clover"
sess = session()
sess = create_scraper(sess, delay=scrapper_delay)
connection = sess.get(url, headers=headers, cookies=cookies_received, proxies={"http": "http://95.179.230.213:4000"})
```

## URL of the Cloudflare-protected page

https://www.crunchyroll.com/black-clover

## URL of Pastebin/Gist with HTML source of protected page

https://pastebin.com/XdynDgXd

**Comment by sharkykh** [comment]
You're trying to get an `https` URL but defined a proxy only for `http` URLs.
I think you need to define a proxy for `https` as well
https://2.python-requests.org/en/master/user/advanced/#id10

So with your code:
```py
url = "https://www.crunchyroll.com/black-clover"
sess = session()
sess = create_scraper(sess, delay=scrapper_delay)
proxies = {
    "http": "http://95.179.230.213:4000",
    "https": "http://95.179.230.213:4000",
}
connection = sess.get(url, headers=headers, cookies=cookies_received, proxies=proxies)
```

**Comment by Xonshiz** [comment]
Thanks, made sense and worked. Nice.
