### ISSUE TITLE
[HELP] '<Response [200]>' Text

### ISSUE THREAD

**Issue by s1ntaxerror** [Anorov/cloudflare-scrape#262]
I tried CloudFlare-Scrape but if I print out the website, I just get this text (error?):

<Response [200]>

Thanks in advance.

**Comment by s1ntaxerror** [comment]
I forgot .text

But I have another question:

I can enter a website like 10-12 times in a while loop with time.sleep(1) and after that the program needs 30sec-2min for entering the website again.
That should be the Ddos Protection but I tought this library would bypass that in some way? Thanks!

**Comment by pro-src** [comment]
Hi @s1ntaxerror,

cfscrape uses the `requests` library under the hood. If you become familiar with the [README](https://github.com/kennethreitz/requests#readme) of both projects, I'm sure you'll figure it out.

Cheers
