### ISSUE TITLE
challenge not solved

### ISSUE THREAD

**Issue by issues420** [Anorov/cloudflare-scrape#263]
have updated to latest Version: 2.0.7.  and I have added a delay of 15 sec to the scraper but still fail the challenge.  the site is ustvgo.tv and the last lines in the print results are: 

 var options = {                filename: "iuam-challenge.js",                contextOrigin: "cloudflare:iuam-challenge.js",                contextCodeGeneration: { strings: true, wasm: false },                timeout: 5000            };            process.stdout.write(String(                require("vm").runInNewContext(challenge, context, options)            ));        ']' returned non-zero exit status 8

any help would be great,  Thanks

**Comment by pro-src** [comment]
Please ensure that you're using a supported version of Node.js: https://github.com/Anorov/cloudflare-scrape#nodejs-dependency

**Comment by issues420** [comment]
Great,  Thanks!
