### ISSUE TITLE
OpenSSL 1.1.1 message

### ISSUE THREAD

**Issue by FrancHR** [Anorov/cloudflare-scrape#264]
Trying to scrape http://spacemov.top
Until yesterday all was fine, but today i'm getting messages about captcha.
Will upgrade to 1.1.1 solve this issue?
Now i have 1.0.2q.

Output:
> CloudflareCaptchaError: Cloudflare captcha challenge presented for spacemov.top (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL
>  library and recompile Python.

-----

```
from fnccfscrapenodejs import CloudflareCaptchaError, create_scraper
scraper = create_scraper()
try:
    scraper.get('https://spacemov.top/')
except CloudflareCaptchaError as e:
    print(e.response.request.url)
    print(e.response.content)
```

Output here:
https://paste.ofcode.org/wgUgx2AyPd5xwS7L3UDxuC

**Comment by pro-src** [comment]
Hi FrancHR,

I would upgrade to the latest version (1.1.1c) https://www.openssl.org/news/vulnerabilities-1.0.2.html
If that doesn't resolve the issue, I'd be very interested.

Feel free to generate a report with this [script](https://gist.github.com/pro-src/17654ec3f949b0b17bd1a4aa1b4136b9).

*This must be ran from within the cloned cloudflare-scrape repo if you haven't pip installed cfscrape*
```sh
git clone https://gist.github.com/pro-src/17654ec3f949b0b17bd1a4aa1b4136b9 temp
cp temp/report.py report.py
python report.py
```

**Comment by FrancHR** [comment]
This is return with SSL 1.0.2q. But will try with 1.1.1 as well later.
Python 3 is not option for me, only 2.7.

`Please test with Python >= 3.5 not Python 2.7.15 (default, May 11 2019, 05:02:50)
[GCC 8.2.0]
Checking GET request for https://spacemov.top DEFAULT
Traceback (most recent call last):
  File "report.py", line 171, in <module>
    scraper.get('https://spacemov.top')
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 537, in get
  File "/var/volatile/tmp/cfscrape.py", line 120, in request
    resp = super(CloudflareScraper, self).request(method, url, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 634, in send
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 445, in send
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
  File "/usr/lib/python2.7/site-packages/urllib3/connection.py", line 356, in connect
  File "/usr/lib/python2.7/site-packages/urllib3/util/ssl_.py", line 359, in ssl_wrap_socket
  File "report.py", line 139, in wrap_socket
    if 'DEFAULT' in request_id and cipher != ('TLS_AES_256_GCM_SHA384', 'TLSv1.3', 256):
UnboundLocalError: local variable 'cipher' referenced before assignment`

**Comment by pro-src** [comment]
Hmm... The error is more than likely due to `pyopenssl`.

Perform the following: `pip uninstall pyopenssl` aka `pip2 uninstall pyopenssl`

I'd also check to see if removing `pyopenssl` has any effect on whether you receive a CAPTCHA or not.

**Comment by pro-src** [comment]
The script has been updated to ignore errors caused by `pyopenssl`. It should still be removed to generate a full report.

**Comment by FrancHR** [comment]
Ok.
This is report without pyopenssl

http://dpaste.com/0DPQCZX

**Comment by FrancHR** [comment]
With updated script:
http://dpaste.com/174TR9W

**Comment by pro-src** [comment]
Thanks for the reports. I think the problem is caused by SHA1 in the signature algorithms extension.

Signature algorithms hash: b10ec48d6fb7b3b35c76dfd53b3529bb
<details><summary>Signature algorithms as reported by ssllabs v1</summary>

```py
(u'SHA512/RSA',
 u'SHA512/DSA',
 u'SHA512/ECDSA',
 u'SHA384/RSA',
 u'SHA384/DSA',
 u'SHA384/ECDSA',
 u'SHA256/RSA',
 u'SHA256/DSA',
 u'SHA256/ECDSA',
 u'SHA224/RSA',
 u'SHA224/DSA',
 u'SHA224/ECDSA',
 u'SHA1/RSA',
 u'SHA1/DSA',
 u'SHA1/ECDSA')
```
</details>

```
 u'SHA1/RSA',
 u'SHA1/DSA',
 u'SHA1/ECDSA'
```

I'm not sure that we can completely disable the use of SHA1 in the signature algorithms extension ***only***. The only way to accomplish this from python is by indirectly passing a cipher list control string to [SSL_CTX_set_cipher_list](https://www.openssl.org/docs/man1.0.2/man3/SSL_CTX_set_cipher_list.html). When I attempt to do so it results in breakage...

Hopefully, updating openssl will resolve this problem for you.

**Comment by pro-src** [comment]
If not, you may elect to use TLSv1.1 at the cost of security. I do not recommend it but this is how you would do it.

```py
import cfscrape
import ssl

from requests.adapters import HTTPAdapter
from urllib3.util.ssl_ import create_urllib3_context

# Using TLSv1.1 - non-modified ciphers list
class CustomAdapter(HTTPAdapter):
    def init_poolmanager(self, *args, **kwargs):
        try:
            ctx = create_urllib3_context(ssl.PROTOCOL_TLSv1)
            ctx.options &= ~ssl.OP_NO_TLSv1
            ctx.options &= ~ssl.OP_NO_TLSv1_1
        except Exception:
            log_error()
            ctx = None
        super(CustomAdapter, self).init_poolmanager(*args, ssl_context=ctx, **kwargs)

scraper = cfscrape.create_scraper()
scraper.mount('https://', CustomAdapter())

# Note that I use HTTPS here to avoid a redirect (HTTPS is forced regardless)
scraper.get('https://spacemov.top/')
