### ISSUE TITLE
ImportError: cannot import name DEFAULT_CIPHERS

### ISSUE THREAD

**Issue by masneg** [Anorov/cloudflare-scrape#265]
I get the error below recently.
Traceback (most recent call last):
  File "cloudflare.py", line 12, in <module>
    import cfscrape
  File "/usr/lib/python2.7/site-packages/cfscrape/__init__.py", line 19, in <module>
    from urllib3.util.ssl_ import create_urllib3_context, DEFAULT_CIPHERS
ImportError: cannot import name DEFAULT_CIPHERS
please help me.
thanks for your code.

**Comment by pro-src** [comment]
Hi @masneg,

It looks like you're using a very old version `urllib3 <= 1.10.2`.
What is the output of the `pip2 freeze` and `python2 -c 'import urllib3; print(urllib3.__version__)'` commands?

All you should have to do is run: `pip2 install -U cfscrape`
Alternatively: `pip2 install -U cfscrape 'requests>=2.0.0' 'urllib3<=1.24,>=1.21.1'`

**Comment by pro-src** [comment]
Minimum `requests` version should be `2.6.1` not `2.0.0`.
https://github.com/Anorov/cloudflare-scrape/blob/e34895c75aec455179b9edefbd1e2c40c1697a0d/setup.py#L29
Temporary fix: `pip2 install -U cfscrape 'requests>=2.6.1'

**Comment by pro-src** [comment]
Fixed in https://github.com/Anorov/cloudflare-scrape/commit/e382d51fcb34733075d5365ca25198e3348a45dc
