### ISSUE TITLE
OpenSSL 1.1.1 message only when i am with python 3.6

### ISSUE THREAD

**Issue by marsarem** [Anorov/cloudflare-scrape#266]
I have a script and when I run that script with python 3.7.0 I don't have any issue but when I run it with python 3.6.5, I see the message : 
"cfscrape.CloudflareCaptchaError: Cloudflare captcha challenge presented for www.japscan.to (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python."
I only change the version of python, I have the same version of cfscrape and requests.

**Comment by bakugo** [comment]
Python 3.6 has an old openssl version, 3.7 does not. So use 3.7. What's the problem?

**Comment by marsarem** [comment]
I need to use python 3.6

**Comment by marsarem** [comment]
How can I upgrade openssl of python 3.6 on windows and linux (raspberry pi) ?

**Comment by bakugo** [comment]
I don't really see why you'd be stuck on 3.6, but if you really are, you'll need to build python yourself with a more recent version of openssl.

https://github.com/python/cpython#build-instructions

**Comment by marsarem** [comment]
ok thank you. I will try to move on python 3.7 but if I can't I will build python with a recent version of openssl
