### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by nico202** [Anorov/cloudflare-scrape#27]
Ok, I'm sorry for the bad bug report I'm going to do, but it seems that they introduced another obfuscation that prevent this from working, I'm I right? I had success using this:
```
S = "cD0iZSIgKyAgJycgKyJiIiArICAnJyArIAoiMyIgKyAiNHN1Ii5zbGljZSgwLDEpICsgICcnICsnJysiNXNlYyIuc3Vic3RyKDAsMSkgKyAiYiIgKyAgJycgKycnKyJhdCIuY2hhckF0KDApICsgICcnICsgCiIzIiA$
L = len(S)
U = 0
A = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
s={}
for u in xrange(64):
   s[A[u]] = u

l=0
r = ""
for i in xrange(L):
   c = s[S[i]];
   U = (U << 6) + c;
   l += 6;
   while l >= 8:
      l -= 8
      a = ( U >> l & 0xff ) or ( i < (L-2))
      r += ''.join(map(unichr, [a]))


print r

```
(you only need to extract "S") and passing this to execjs

EDIT: sorry for the quick & dirty report, but really I'm out of time and needed to bypass this the fastest way I found

**Comment by nico202** [comment]
Just for completeness:
```
import execjs
import re

def get_js(page):
    S = re.search("S='(\w+)", page).group(1)
    L = len(S)
    U = 0
    A = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
    s = {}
    for u in xrange(64):
       s[A[u]] = u

    l = 0
    r = ""
    for i in xrange(L):
       c = s[S[i]];
       U = (U << 6) + c;
       l += 6;
       while l >= 8:
          l -= 8
          a = ( U >> l & 0xff ) or ( i < (L-2))
          r += ''.join(map(unichr, [a]))
    a, b = r.split(";")[0], r.split(";")[1]
    return js_eval((a, b))

def js_eval(js):
    a, b = js
    val = execjs.eval(a)
    key = execjs.eval(b[9:-4])[:-1]
    return key, val
```
key, val = get_js(session.get(url, headers = {"User-agent": "Mozilla"}).content)

**Comment by llpinokio** [comment]
Nice, thank you, though is working fine here :)

**Comment by Anorov** [comment]
The Cloudflare JS challenge pages I'm looking at do not appear to have changed at all. The page looks exactly the same and my code still appears to be working.

Could you link the site you're experiencing issues with? Are you sure it's using Cloudflare, and not another CDN/web firewall?

**Comment by nico202** [comment]
Ok I'm sorry, my fault. It's Sucuri. Sorry to have bothered you :)
