### ISSUE TITLE
Problem with version 2.0.7

### ISSUE THREAD

**Issue by tcdude** [Anorov/cloudflare-scrape#272]
## Version number

Run `pip show cfscrape` and paste the output below:

```
2.0.7
```

## Code snippet experiencing the issue

```
scraper = cfscrape.create_scraper(delay=10)
source = scraper.get(url).content
```

## Complete exception and traceback

(*If the problem doesn't involve an exception being raised, leave this blank*)

```
Cloudflare IUAM challenge returned unexpected answer. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues."
Traceback (most recent call last):
  File "/home/tc/Apps/AutoTorrent/helper.py", line 659, in get_torrentz_search_results
    source = browser.get(url).content
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cfscrape/__init__.py", line 128, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cfscrape/__init__.py", line 181, in solve_cf_challenge
    answer, delay = self.solve_challenge(body, domain)
  File "/usr/local/lib/python2.7/dist-packages/cfscrape/__init__.py", line 297, in solve_challenge
    "Cloudflare IUAM challenge returned unexpected answer. %s" % BUG_REPORT
ValueError: Cloudflare IUAM challenge returned unexpected answer. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues."
```

## URL of the Cloudflare-protected page

https://www.torrentz2.eu

## URL of Pastebin/Gist with HTML source of protected page

https://pastebin.com/rMCd53GY

**Comment by pro-src** [comment]
Please see https://github.com/Anorov/cloudflare-scrape/issues/271 and similar issues. You're most likely running an outdated version of Node.js

**Comment by k12007** [comment]
Hmm I think the cloudflare might have change the challenge? I have the latest node (v10.16.0) and all my parsing script fail at the same time this morning

**Comment by pro-src** [comment]
> Never mind, @pro-src is right, updated to the latest node version fix it, sorry if anyone wasted their time and get confuse by what I said earlier.

I have some code to analyze such snippets for me so no worries. :)
If ya'll need any further assistance, lmk

I'm going to go ahead and close this now.

**Comment by tcdude** [comment]
Which version of Node.js should I be running? I'm on `v4.2.6` right now.

Thanks
