### ISSUE TITLE
Trouble installing.

### ISSUE THREAD

**Issue by Ordval** [Anorov/cloudflare-scrape#274]
I've come so far as installed Python and Pip, (Phew; using Streamlink's Python is obviously no option) moved cfscrape to its own directory `[C:\Program Files\cfscrape\cloudflare-scrape-master]` (Windows 10).      Still it won't install:
```
C:\Users\Ordval>Python C:\Program Files\cfscrape\cloudflare-scrape-master\setup.py install  Python: can't open file 'C:\Program': [Errno 2] No such file or directory
```
The files are exactly in the same order as they got extracted from the .zip.
A few text-files got installed in `C:\Windows\System32\cfscrape.egg-info` by the 
`pip install cfscrape`.

Tried moving them to `C:\Python27\Lib`, where I suppose the rest of it
must have been installed ? by `pip install cfscrape`:  
```
Requirement already satisfied: cfscrape in c:\python27\lib\site-packages (2.0.7)
Requirement already satisfied: requests>=2.0.0 in c:\python27\lib\site-packages (from cfscrape) (2.22.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\python27\lib\site-packages (from requests>=2.0.0->cfscrape) (2019.6.16)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\python27\lib\site-packages (from requests>=2.0.0->cfscrape) (1.25.3)
Requirement already satisfied: idna<2.9,>=2.5 in c:\python27\lib\site-packages (from requests>=2.0.0->cfscrape) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\python27\lib\site-packages (from requests>=2.0.0->cfscrape) (3.0.4)
```

 ```
C:\WINDOWS\system32>Python C:\Python27\Lib\setup.py install
running install
running bdist_egg
running egg_info
writing requirements to cfscrape.egg-info\requires.txt
writing cfscrape.egg-info\PKG-INFO
writing top-level names to cfscrape.egg-info\top_level.txt
writing dependency_links to cfscrape.egg-info\dependency_links.txt
error: package directory 'cfscrape' does not exist
```
My intention is to be able to open a TV channel via Streamlink with the aid of **[back-to](https://github.com/back-to)**'s plugin "Generic". This used to work fine until the site started blocking with Cloudflare and **[back-to](https://github.com/back-to)**'s recommendation is your module. There is no mentioning on his part of a special command to use in the c. line with Streamlink, so for the moment I'm assuming that not all have been properly installed.
What do I do next ? 

> Download the file for your platform. If you're not sure which to choose, learn more about installing packages.   [pip install](https://pypi.org/project/cfscrape/#files)

I must come across as quite a noob; 
not with the intent of being unkind in any way, 
but surely you must know that some of us are just 
your regular Plug-and-play users ? 
Not like many of the semi-experts and 
in-depth connoisseurs that posts on the github.com pages.
I don't even understand what `"clone this repository..."` 
mean ("How to..." and what should happen).

**Comment by pro-src** [comment]
Most build/package tools need to be ran from the project's directory, not from system folders. Start over from scratch and follow some good tutorials.

Python 3: https://docs.python-guide.org/starting/install3/win/
Python 2: https://docs.python-guide.org/starting/install/win/
Or: https://realpython.com/installing-python/#windows

Pip: https://pip.pypa.io/en/stable/installing/

Packages: https://packaging.python.org/tutorials/installing-packages/

**Comment by pro-src** [comment]
Also, the number of so called `regular Plug-and-play users` greatly out number real developers and we don't have time to teach you. It's like 1 to a million or something :rofl: 

Seriously though, not everything it's meant to be done by such users, sometimes you need to just take the time to learn these things for yourself or leave it alone.

Good luck 2 you!
