### ISSUE TITLE
unable to scrape steamdb.info

### ISSUE THREAD

**Issue by jobsfan** [Anorov/cloudflare-scrape#275]
Before creating an issue, first upgrade cfscrape with `pip install -U cfscrape` and see if you're still experiencing the problem.

## Version number

Run `pip show cfscrape` and paste the output below:

```
2.0.7
```

## Code snippet experiencing the issue

```
SSL/TLS error
curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed
```

## Complete exception and traceback

(*If the problem doesn't involve an exception being raised, leave this blank*)

```

```

## URL of the Cloudflare-protected page

https://steamdb.info/app/896960/graphs/
https://steamdb.info/api/GetGraph/?type=concurrent_week&appid=896960

## URL of Pastebin/Gist with HTML source of protected page

[LINK GOES HERE]

**Comment by pro-src** [comment]
The error is from Curl and is not related to python or this project.
