### ISSUE TITLE
Cloudflare captcha challenge presented (but it isn't a captcha)

### ISSUE THREAD

**Issue by SDXC** [Anorov/cloudflare-scrape#279]
## Version number

Run `pip show cfscrape` and paste the output below:

```
Name: cfscrape
Version: 2.0.7
Summary: A simple Python module to bypass Cloudflare's anti-bot page. See https://github.com/Anorov/cloudflare-scrape for more information.
Home-page: https://github.com/Anorov/cloudflare-scrape
Author: Anorov
Author-email: anorov.vorona@gmail.com
License: UNKNOWN
Location: c:\program files\python37\lib\site-packages
Requires: requests
Required-by:
```

## Code snippet experiencing the issue

```
import cfscrape, sys, traceback

try:
	url = sys.argv[1]
	websitename = sys.argv[2]
	filename = 'cf_bypass.txt'
	
	if "http://" not in url and "https://" not in url:
		url = "http://" + url
	
	if websitename != "":
		filename = "cf_bypass-" + websitename + ".txt"
	
	scraper = cfscrape.create_scraper()
	print(scraper.get(url).content)	
except Exception as e:
	traceback.print_exc()
```

## Complete exception and traceback

(*If the problem doesn't involve an exception being raised, leave this blank*)

```
Traceback (most recent call last):
  File "cf_bypass.py", line 17, in <module>
  File "site-packages\requests\sessions.py", line 546, in get
  File "cfscrape\__init__.py", line 128, in request
  File "cfscrape\__init__.py", line 194, in solve_cf_challenge
  File "cfscrape\__init__.py", line 124, in request
  File "cfscrape\__init__.py", line 147, in handle_captcha_challenge
cfscrape.CloudflareCaptchaError: Cloudflare captcha challenge presented for oneshotscans.com (cfscrape cannot solve captchas)
```

## URL of the Cloudflare-protected page

https://oneshotscans.com/comics/the-great-ruler/1/109

## Additional Info:
Python: 3.7.4
PyInstaller: 3.5.0
Node.js: 12.8.0

I use PyInstaller for the script. In most cases it works fine, it's just some websites that don't work.

**Comment by pro-src** [comment]
Hi @SDXC,

I ran your snippet.

<details><summary>Snippet</summary>

```py
import cfscrape, sys, traceback

try:
	url = sys.argv[1]
	websitename = sys.argv[2]
	filename = 'cf_bypass.txt'
	
	if "http://" not in url and "https://" not in url:
		url = "http://" + url
	
	if websitename != "":
		filename = "cf_bypass-" + websitename + ".txt"
	
	scraper = cfscrape.create_scraper()
	print(scraper.get(url).content)	
except Exception as e:
	traceback.print_exc()
```
</details>

> python issue-279.py 'https://oneshotscans.com/comics/the-great-ruler/1/109' oneshotscans

Works just fine without pyinstaller.

If it does happen to be a CAPTCHA, consider these notes (For a different project, mind you): https://github.com/codemanki/cloudscraper#recaptcha
I've yet to PR a docs update for cfscrape but you could try that or the following to see if it helps:
```py
import cfscrape
cfscrape.DEFAULT_CIPHERS += ':!AESCCM:!DHE:!ARIA'
```

Cheers

**Comment by SDXC** [comment]
Hi @pro-src 

You know what, with the additional ciphers it worked in the PyInstaller compiled script as well.
Really, thank you!

But it's funny that the behavior is so different between interpreter and compiled bin...
