### ISSUE TITLE
Using cookies for cloudflare

### ISSUE THREAD

**Issue by dheerajbred** [Anorov/cloudflare-scrape#286]
This is not an issue. I have a question. 
Let's say I am scraping content from https://www12.animeultima.eu/ and I get the HTML and the cookies
`__cfduid=d2fab15349a424677ac9b56555ed6968f1567171908; cf_clearance=c802abd132d7915f50f92eb5644f9fee3fea15c8-1567171913-604800-150`

How to use these cookies to continue the session? I mean it takes 4-5secs for cfscrape to scrape data from a URL. But how to use the cookies so that there is no need for cloudflare bypassing again?

I tried http.get(url) with headers: {set-cookie/Cookie = cfscrapecookies} but I still getting the cloudflare protection 503 response

Any help is really appreciated.

**Comment by pro-src** [comment]
Hi @dheerajbred,

There usually isn't any need to handle the cookies manually.

The scraper is an instance of [requests.Session](https://github.com/psf/requests/blob/3d968ff34dd9945f2a86396001408ba69c1ab3fd/requests/sessions.py#L342-L345) which automatically parses the `Set-Cookie` response header and stores the cookies in a [requests.RequestsCookieJar](https://github.com/psf/requests/blob/3d968ff34dd9945f2a86396001408ba69c1ab3fd/requests/cookies.py#L171-L187). The `Cookie` header will be added to subsequent requests automatically and the jar is exposed as the [cookies](https://github.com/psf/requests/blob/3d968ff34dd9945f2a86396001408ba69c1ab3fd/requests/sessions.py#L415) attribute on session instances.

```py
import requests
import cfscrape

scraper = scraper.create_scraper()

assert isinstance(scraper, requests.Session) # True
assert isinstance(scraper, cfscrape.CloudflareScraper) # True
```
```sh
>>> print(scraper.cookies)
<RequestsCookieJar[]>
```

For more information please read the *requests* [docs.](https://2.python-requests.org/en/master/) and links in this comments.

Cheers

**Comment by dheerajbred** [comment]
Understood. Thanks a lot @pro-src :)

One more question; is there a way we can check if the cookies are valid or not?
I am making an app and I want to show users a long loading screen when the cookies are not there/not valid.

Cheers

**Comment by pro-src** [comment]
@dheerajbred, you're welcome :)

There is a scraper instance method that may be used:
https://github.com/Anorov/cloudflare-scrape/blob/b8892558251f25afd24ed8bbff953173a4c93168/cfscrape/__init__.py#L132-L137

It looks the method above should be using `urlparse(url).hostname` instead of `urlparse(url).netloc`. 
The latter will include the port e.g. `{hostname}:{port}`.
I've added an extra [example](#example-3) in case that is an issue.

### Example 1
```py
import cfscrape
scraper = cfscrape.create_scraper()

resp = scraper.get(url)
resp.raise_for_status()

cf_clearance = scraper.cloudflare_is_bypassed(url)
assert cf_clearance is not None
print("cf_clearance: %s" % cf_clearance)
```

### Example 2
```py
import cfscrape

cookie_dict, user_agent = cfscrape.get_tokens()
cf_clearance = cookie_dict.get("cf_clearance")
assert cf_clearance is not None
print("cf_clearance: %s" % cf_clearance)
```

### Example 3
```py
import cfscrape

resp = scraper.get(url)
resp.raise_for_status()

cf_clearance = scraper.cookies.get("cf_clearance", None, domain=".%s" % hostname)
assert cf_clearance is not None
print("cf_clearance: %s" % cf_clearance)
```
