### ISSUE TITLE
How bypass cloudflare with webdriver selenium python

### ISSUE THREAD

**Issue by AlexSavichev** [Anorov/cloudflare-scrape#289]
Dear Anorov, help solve the problem. After pressing the button 'Input', appear protection CloudFlare. how can I bypass it to continue to use selenium python. Here is a sample code. 
        
driver = webdriver.Firefox(executable_path=geckodriver)
driver.get('https://example.com')
time.sleep(random.uniform(9,13)) 
source_element = driver.find_element_by_partial_link_text('Input').click()
time.sleep(random.uniform(8,14))

source_element = driver.find_element_by_xpath("//input[@name='username']")
source_element.send_keys("username")
time.sleep(random.uniform(3,4))

source_element = driver.find_element_by_xpath("//input[@name='passwd']")
source_element.send_keys("passwd")
time.sleep(random.uniform(3,4))

source_element = driver.find_element_by_xpath("//button[contains(text(),'OK')]").click()
driver.get('https://example.com?login=1')

**Comment by pro-src** [comment]
Hi @AlexSavichev,

It should not be necessary to use both cfscrape and selenium to bypass the Cloudflare interstitial. If you have a question specific to cfscrape, update your issue to reflect that. As it stands, this question is best suited for https://stackoverflow.com or selenium related forums/github issues.

Cheers
