### ISSUE TITLE
Cloudfare acces denied

### ISSUE THREAD

**Issue by HiImNatsu** [Anorov/cloudflare-scrape#293]
Before creating an issue, first upgrade cfscrape with `pip install -U cfscrape` and see if you're still experiencing the problem. Please also confirm your Node version (`node --version` or `nodejs --version`) is version 10 or higher.

Make sure the website you're having issues with is actually using anti-bot protection by Cloudflare and not a competitor like Imperva Incapsula or Sucuri. And if you're using an anonymizing proxy, a VPN, or Tor, Cloudflare often flags those IPs and may block you or present you with a captcha as a result.

Please **confirm the following statements and check the boxes** before creating an issue:

- [ ] I've upgraded cfscrape with `pip install -U cfscrape`
- [ ] I'm using Node version 10 or higher
- [ ] The site protection I'm having issues with is from Cloudflare
- [ ] I'm not using Tor, a VPN, or an anonymizing proxy

## Python version number

Run `python --version` and paste the output below:

```
C:\Users\ASUS\Downloads>python --version
Python 3.7.4
```

## cfscrape version number

Run `pip show cfscrape` and paste the output below:

```
C:\Users\ASUS\Downloads>pip show cfscrape
Name: cfscrape
Version: 2.0.8
Summary: A simple Python module to bypass Cloudflare's anti-bot page. See https://github.com/Anorov/cloudflare-scrape for more information.
Home-page: https://github.com/Anorov/cloudflare-scrape
Author: Anorov
Author-email: anorov.vorona@gmail.com
License: UNKNOWN
Location: c:\python37\lib\site-packages
Requires: requests
Required-by:
```

## Code snippet involved with the issue

```

```

## Complete exception and traceback

(*If the problem doesn't involve an exception being raised, leave this blank*)

```

```

## URL of the Cloudflare-protected page

https://haapi.ankama.com/json/Ankama/v2/Account/CreateGuest?game=18&lang=en&captcha_token=

## URL of Pastebin/Gist with HTML source of protected page

https://pastebin.com/iQ03BAGM

**Comment by pro-src** [comment]
@HiImNatsu 

Check the boxes and provide a working code snippet that reproduces the problem so we can determine whether this is actually a problem with cfscrape.

**Comment by pro-src** [comment]
It's clearly not a problem with cfscrape. Closing...

**Comment by HiImNatsu** [comment]
It is actually , i can send you the code in private if you want

**Comment by pro-src** [comment]
It isn't actually. Try https://stackoverflow.com or continue your tech support session with the fake cloudscraper project.

**Comment by HiImNatsu** [comment]
Why the hate ?

**Comment by HiImNatsu** [comment]
i'm just looking for a solution that's all

**Comment by pro-src** [comment]
> Please confirm the following statements and check the boxes before creating an issue

The problem your experiencing isn't a cfscrape bug, inability to follow simple instructions :point_up:, and the cloudscraper project that you're using was ripped off from me personally. So, there's bad history there. I think you'd have better luck using something like freelancer.com or upwork.com.

Anyways, this isn't the place for that. Btw, that plagiarizing fork has security vulnerabilities.

Good luck
