### ISSUE TITLE
NodeJs runtime when running on AWS Lambda

### ISSUE THREAD

**Issue by lapwat** [Anorov/cloudflare-scrape#300]
I cannot run cfscrape in a Python AWS Lambda function. I have an error telling me I am missing Node.js runtime.

Do you have ideas on how to make it work?

Possible solutions I have though of:
- Running a lambda function with several runtimes (Python+Node.js), not sure if it is possible
- Embedding a Node.js binary that cfscrape would use

**Comment by xavier-niu** [comment]
Yes, I have that problem too. In my solution, I clone this project add some system environment information for dependencies, at `cfscrape/__init__.py` line 287 around.
```python
# ...
stderr = ''
        try:
            node = subprocess.Popen(
                ["node", "-e", js], stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                universal_newlines=True, 
                env={ # This is what you need append.
                    "PATH": "YOUR PATH"
                }
            )
# ...
```
I think it should provide a method to specify a custom path.

**Comment by marcolussetti** [comment]
Same approach I took. Bundle or fetch the nodejs binary and override the path.

**Comment by marcolussetti** [comment]
Forgot to mention this: I believe Azure Cloud Functions include a nodejs runtime even with Python functions so if your workload fits that product that's an option for you too.
