### ISSUE TITLE
SSLv3 handshake failure

### ISSUE THREAD

**Issue by C0rn3j** [Anorov/cloudflare-scrape#310]
```
openssl 1.1.1.d
python 3.8.0
cfscrape 2.0.8
```

If using `DEFAULT_CIPHERS` as a suggested workaround for `cfscrape cannot solve captchas` (#309), I get an SSLv3 error. Downloading the file via `requests` works fine.

```
HTTPSConnectionPool(host='edge.forgecdn.net', port=443): Max retries exceeded with url: /files/2819/400/AbyssalCraft-1.12.2-1.9.13.1.jar (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')])")))
```

Example code:
```
#!/bin/python
import os, requests, cfscrape

cfscrape.DEFAULT_CIPHERS = 'TLS_AES_256_GCM_SHA384:ECDHE-ECDSA-AES256-SHA384'
scraper = cfscrape.create_scraper()

response = requests.get("https://edge.forgecdn.net/files/2819/400/AbyssalCraft-1.12.2-1.9.13.1.jar")
print(response)

response = scraper.get("https://edge.forgecdn.net/files/2819/400/AbyssalCraft-1.12.2-1.9.13.1.jar")
print(response)
```

**Comment by arderyp** [comment]
>  using DEFAULT_CIPHERS as a suggested workaround for cfscrape cannot solve captchas (#309)

@C0rn3j, where exactly is that a suggested workaround?  Is there documentation on this that I'm missing?

**Comment by C0rn3j** [comment]
https://github.com/Anorov/cloudflare-scrape/issues/268

**Comment by ilu33** [comment]
I'm having the exact same problem using https://github.com/ephraim/lcurse. We are probably trying to access the same website @C0rn3j . Strange that it still works under debian9.

**Comment by C0rn3j** [comment]
Whatever the issue is, `cloudscraper` which is a project that I use now as a drop-in replacement got it right, so would be worth to look there

**Comment by arderyp** [comment]
hmm, interesting @C0rn3j, thanks for the input

**Comment by ilu33** [comment]
I solved the issue for me with using
```
cfscrape.DEFAULT_CIPHERS = 'TLS_AES_256_GCM_SHA384:kECDHE'
```
kECDHE is the relevant cipher for edge.forgecdn.net.

**Comment by Anorov** [comment]
This should be fixed in the latest version. Please update with `pip install -U cfscrape`.
