### ISSUE TITLE
Location header missing from redirect call due to 404 being returned

### ISSUE THREAD

**Issue by CodyWoolaver** [Anorov/cloudflare-scrape#317]
- [x] I've upgraded cfscrape with `pip install -U cfscrape`
- [x] The site protection I'm having issues with is from Cloudflare
- [x] I'm not using Tor, a VPN, or an anonymizing proxy

## Python version number
```
root@b25b6051556a:/# python --version
Python 2.7.16
```

## cfscrape version number

Run `pip show cfscrape` and paste the output below:

```
root@b25b6051556a:/# cat "/app/sickrage/lib/cfscrape/__init__.py" | grep __version__
__version__ = "2.0.8"
```

## Code snippet involved with the issue

I stuck a debugger here https://github.com/Anorov/cloudflare-scrape/blob/master/cfscrape/__init__.py#L195
```
Here are the contents of locals()
{'answer': '145.0625366270',
 'body': <See GIST>,
 'cloudflare_kwargs': {'allow_redirects': False,
                       'cookies': None,
                       'data': {},
                       'headers': {'Referer': u'https://iptorrents.eu/take_login.php',
                                   u'User-Agent': u'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1944.0 Safari/537.36'},
                       'hooks': {u'response': <function get_url_hook at 0x153f69682b18>},
                       'params': OrderedDict([(u'jschl_vc', u'3a27bb45d92a5f8c67dd2df12d093234'), (u'pass', u'1575235157.691-t8ISrQU82I'), ('jschl_answer', '145.0625366270')]),
                       'proxies': None,
                       'stream': False,
                       'timeout': 30,
                       'verify': '/app/sickrage/lib/certifi/cacert.pem'},
 'delay': 4.0,
 'domain': u'iptorrents.eu',
 'headers': {'Referer': u'https://iptorrents.eu/take_login.php',
             u'User-Agent': u'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1944.0 Safari/537.36'},
 'ipdb': <module 'ipdb' from '/usr/lib/python2.7/site-packages/ipdb/__init__.pyc'>,
 'k': 'pass',
 'method': 'GET',
 'original_kwargs': {'allow_redirects': True,
                     'cookies': None,
                     'data': {},
                     'headers': {u'User-Agent': u'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1944.0 Safari/537.36'},
                     'hooks': {u'response': <function get_url_hook at 0x153f69682b18>},
                     'params': {},
                     'proxies': None,
                     'stream': False,
                     'timeout': 30,
                     'verify': '/app/sickrage/lib/certifi/cacert.pem'},
 'params': OrderedDict([(u'jschl_vc', u'3a27bb45d92a5f8c67dd2df12d093234'), (u'pass', u'1575235157.691-t8ISrQU82I'), ('jschl_answer', '145.0625366270')]),
 'parsed_url': ParseResult(scheme=u'https', netloc=u'iptorrents.eu', path=u'/take_login.php', params='', query='', fragment=''),
 'redirect': <Response [404]>,
 'resp': <Response [503]>,
 'self': <cfscrape.CloudflareScraper object at 0x153f695db290>,
 'start_time': 1575235153.700175,
 'submit_url': u'https://iptorrents.eu/cdn-cgi/l/chk_jschl'}
```
Seems that the url that is set here is incorrect for this particular webpage: https://github.com/Anorov/cloudflare-scrape/blob/master/cfscrape/__init__.py#L155

A check may need to happen to verify that `redirect` had a successful response and it is not a 404. That is why there is a missing Location headers.

## Complete exception and traceback
```
Traceback (most recent call last):
  File "/app/sickrage/sickbeard/helpers.py", line 1461, in getURL
    headers=headers, cookies=cookies, proxies=proxies, verify=verify
  File "/app/sickrage/lib/cfscrape/__init__.py", line 128, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/app/sickrage/lib/cfscrape/__init__.py", line 195, in solve_cf_challenge
    redirect_location = urlparse(redirect.headers["Location"])
  File "/app/sickrage/lib/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
```

## URL of the Cloudflare-protected page
https://iptorrents.eu/take_login.php

## URL of Pastebin/Gist with HTML source of protected page
https://gist.github.com/CodyWoolaver/7965aba28c44f5f1345aef8838944be1

**Comment by mcronce** [comment]
Same issue here, same website, different end user software using cfscrape.  I dug in a little bit when I had a bit of time and in `solve_challenge()`, this regex:

```python
re.search(r"<div(?: [^<>]*)? id=\"cf-dn.*?\">([^<>]*)", body)
```

may no longer be correct.  I printed out the whole body that `solve_cf_challenge()` receives from the server and passes into `solve_challenge()`, and `cf-dn` does not exist anywhere in it.  Unfortunately I don't know _what_ cfscrape is looking for in that `div`, so I'm not sure if it's just a matter of looking for a different element, or a huge rework.

**Comment by mcronce** [comment]
Just saw #315, that looks promising, going to try my software with it

**Comment by mcronce** [comment]
Yep, #315 fixes it for me.  Thanks @alzamer2 :)

**Comment by CodyWoolaver** [comment]
Can confirm #315 also fixes my software.

**Comment by alzamer2** [comment]
hmm, better close this issue then

**Comment by CodyWoolaver** [comment]
If we can close this issue, can we merge in the code?

**Comment by zxsdklfhskyrvk** [comment]
I've tried this replacement of the init script from #315 ,  but it didn't solve all my problems.  It just moved onto a new one.  Any ideas if the new error is related?

`Traceback (most recent call last):
  File "script.py", line 178, in <module>
    scrape_1(value1)
  File "script.py", line 76, in scrape_1
    page = scraper.get(url)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\cfscrape\__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\cfscrape\__init__.py", line 236, in solve_cf_challenge
    elif 'cf_clearance' in redirect.headers['Set-Cookie']:
  File "C:\Users\user1\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'set-cookie'`

**Comment by lord8266** [comment]
which site? @zxsdklfhskyrvk

**Comment by Anorov** [comment]
This should be fixed in the latest version. Please update with `pip install -U cfscrape`.
