### ISSUE TITLE
my error

### ISSUE THREAD

**Issue by Fatosy** [Anorov/cloudflare-scrape#319]
Name: cfscrape
Version: 2.0.8

**code :**
url='https://explorer.ravencoin.world'

scraper = cfscrape.create_scraper(delay=5)
data=scraper.get(url).content
print(data)

**status:**
no return,always wait for it ,no stop

**Comment by Andrew-L1** [comment]
Hi! I have this error too. It has begun start a ~10 day ago, when cloudflare launched a new protection method.

**Comment by pl77** [comment]
For those of you who can't wait for a new version to get published to pypi, you can patch it yourself. There is a fix from @alzamer2 in the pull requests:

https://github.com/Anorov/cloudflare-scrape/pull/315

To find where your `cfscrape` module is stored, the easiest way is with the python interpreter from the environment you want to fix.  Type `python` to open up the interpreter and you'll be greeted with a similar prompt as the one below:

```
Python 3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
Type the following two commands:
```python
import importlib
importlib.util.find_spec('cfscrape').origin
```
...which will give you a string path location (similar to the one below): 

`'/home/user/anaconda/lib/python3.7/site-packages/cfscrape/__init__.py'`

Open that `__init__.py` file in an editor and replace all the contents with the raw contents from the pull request:

[raw text from pull request 115](https://raw.githubusercontent.com/Anorov/cloudflare-scrape/713e3b4017442d87ad0d638f7991cc330abeee5e/cfscrape/__init__.py)

Save it and your cfscrape should work again.  

Once the pull request is pushed to pypi just update as normal and the contents will be replaced.

**Comment by Anorov** [comment]
This should be fixed in the latest version. Please update with `pip install -U cfscrape`.
