### ISSUE TITLE
It doesn't work, the latest version.

### ISSUE THREAD

**Issue by Dreamcatcher9009** [Anorov/cloudflare-scrape#320]
My test code:
import cfscrape
scraper = cfscrape.create_scraper()

# 获取网页源代码
web_data = scraper.get("https://wallhere.com/").content
print(web_data)

but it is blocking and not return response, I don't know why.
It doesn't work for another site too, https://www.haypost.am/en/track-and-trace!
I try to use other version, but it still doesn't work

**Comment by dr-nyt** [comment]
Cloudflare updated and this module needs to be updated as well. I have another program that uses javascript to bypass Cloudflare and it didn't work until I updated that module. Hopefully, this module is updated soon.

**Comment by Dreamcatcher9009** [comment]
Look&nbsp;forward&nbsp;to&nbsp;good&nbsp;news!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shehryar"<notifications@github.com&gt;; 
发送时间: 2019年12月18日(星期三) 下午2:59
收件人: "Anorov/cloudflare-scrape"<cloudflare-scrape@noreply.github.com&gt;; 
抄送: "追梦人"<630589959@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Anorov/cloudflare-scrape] It doesn&#39;t work, the latest version. (#320)




Cloudflare updated and this module needs to be updated as well. I have another program that uses javascript to bypass Cloudflare and it didn't work until I updated that module. Hopefully, this module is updated soon.

**Comment by dr-nyt** [comment]
You could try doing:
pip install cloudscraper
```
import cloudscraper
scraper = cloudscraper.create_scraper()
# and so on
```
That module works almost the same as this one but is more upto date and can easily be swapped into ur code.

**Comment by pl77** [comment]
If you want to patch this module until it gets properly updated, there is a fix in the pull requests:

https://github.com/Anorov/cloudflare-scrape/pull/315

To find where your `cfscrape` module is stored, the easiest way is with the python interpreter from the environment you want to fix.  Type `python` to open up the interpreter and you'll be greeted with a similar prompt as the one below:

```
Python 3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
Type the following two commands:
```python
import importlib
importlib.util.find_spec('cfscrape').origin
```
...which will give you a string path location (similar to the one below): 

`'/home/user/anaconda/lib/python3.7/site-packages/cfscrape/__init__.py'`

Open that file in an editor and replace all the contents with the raw contents from the pull request:

`https://raw.githubusercontent.com/Anorov/cloudflare-scrape/713e3b4017442d87ad0d638f7991cc330abeee5e/cfscrape/__init__.py`

Save it and your cfscrape should work again.  

Once the pull request is pushed to pypi just update as normal and the contents will be replaced.

**Comment by Dreamcatcher9009** [comment]
Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "pl77"<notifications@github.com&gt;; 
发送时间: 2019年12月20日(星期五) 晚上11:33
收件人: "Anorov/cloudflare-scrape"<cloudflare-scrape@noreply.github.com&gt;; 
抄送: "追梦人"<630589959@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Anorov/cloudflare-scrape] It doesn&#39;t work, the latest version. (#320)




If you want to patch this module until it gets properly updated, there is a fix in the pull requests:
 
#315
 
To find where your cfscrape module is stored, the easiest way is with the python interpreter from the environment you want to fix.  Type python to open up the interpreter and you'll be greeted with a similar prompt as the one below:
 Python 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0] :: Anaconda, Inc. on linux Type "help", "copyright", "credits" or "license" for more information. &gt;&gt;&gt;  
Type the following two commands:
 import importlib importlib.util.find_spec('cfscrape').origin
 
...which will give you a string path location (similar to the one below):
 
'/home/user/anaconda/lib/python3.7/site-packages/cfscrape/__init__.py'
 
Open that file in an editor and replace all the contents with the raw contents from the pull request:
 
https://raw.githubusercontent.com/Anorov/cloudflare-scrape/713e3b4017442d87ad0d638f7991cc330abeee5e/cfscrape/__init__.py
 
Save it and your cfscrape should work again.
 
Once the pull request is pushed to pypi just update as normal and the contents will be replaced.

**Comment by overorions** [comment]
> You could try doing:
> pip install cloudscraper
> 
> ```
> import cloudscraper
> scraper = cloudscraper.create_scraper()
> # and so on
> ```
> 
> That module works almost the same as this one but is more upto date and can easily be swapped into ur code.

This looks like a fork but is not labeled as such - even the read me is nearly copied verbatim. That seems dodgy?

**Comment by dr-nyt** [comment]
> > You could try doing:
> > pip install cloudscraper
> > ```
> > import cloudscraper
> > scraper = cloudscraper.create_scraper()
> > # and so on
> > ```
> > 
> > 
> > That module works almost the same as this one but is more upto date and can easily be swapped into ur code.
> 
> This looks like a fork but is not labeled as such - even the read me is nearly copied verbatim. That seems dodgy?

Oh, I didn't notice that before, thanks for the heads up.

**Comment by bitspill** [comment]
> > > You could try doing:
> > > pip install cloudscraper
> > > ```
> > > import cloudscraper
> > > scraper = cloudscraper.create_scraper()
> > > # and so on
> > > ```
> > > 
> > > 
> > > That module works almost the same as this one but is more upto date and can easily be swapped into ur code.
> > 
> > 
> > This looks like a fork but is not labeled as such - even the read me is nearly copied verbatim. That seems dodgy?
> 
> Oh, I didn't notice that before, thanks for the heads up.

It is a fork, you can see Anarov credited in the MIT License file
https://github.com/VeNoMouS/cloudscraper/blob/master/LICENSE#L4

> Copyright (c) 2019 VeNoMouS
> Copyright (c) 2015 Anorov

**Comment by Dreamcatcher9009** [comment]
Nice job! Thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"bitspill"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月14日(星期二) 凌晨3:04
收件人:&nbsp;"Anorov/cloudflare-scrape"<cloudflare-scrape@noreply.github.com&gt;;
抄送:&nbsp;"追梦人"<630589959@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Anorov/cloudflare-scrape] It doesn't work, the latest version. (#320)



   
You could try doing:
 pip install cloudscraper
 import cloudscraper scraper = cloudscraper.create_scraper() # and so on  
That module works almost the same as this one but is more upto date and can easily be swapped into ur code.
  
This looks like a fork but is not labeled as such - even the read me is nearly copied verbatim. That seems dodgy?
  
Oh, I didn't notice that before, thanks for the heads up.
  
It is a fork, you can see Anarov credited in the MIT License file
 https://github.com/VeNoMouS/cloudscraper/blob/master/LICENSE#L4
  
Copyright (c) 2019 VeNoMouS
 Copyright (c) 2015 Anorov

**Comment by Anorov** [comment]
This should be fixed in the latest version. Please update with `pip install -U cfscrape`.
