### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'ssl_context'

### ISSUE THREAD

**Issue by mittal1787** [Anorov/cloudflare-scrape#321]
I am getting this error when I am trying to scrape a website:

![code](https://user-images.githubusercontent.com/33040186/71564133-6d2bc200-2a61-11ea-93d6-2d73df0535bc.png)

![error](https://user-images.githubusercontent.com/33040186/71564132-67ce7780-2a61-11ea-9b66-4f91b5396868.png)

**Comment by alzamer2** [comment]
this error with #315 patch?

**Comment by mtalhagaoglu** [comment]
hi, i'm getting same error. is there any solution?

**Comment by Anorov** [comment]
This should be fixed in the latest version. Please update with `pip install -U cfscrape`.

**Comment by hi2rashid** [comment]
`pip3 install -U requests` Worked
