### ISSUE TITLE
cloudflare ddos

### ISSUE THREAD

**Issue by sk27677** [Anorov/cloudflare-scrape#323]
Here is the code that will bypass cloudflare ddos 100%. Anyway to integrate it with mechanize?

**Comment by lord8266** [comment]
You can try using [MechanicalSoup](https://mechanicalsoup.readthedocs.io/en/stable/) which internally uses BeautifulSoup and Requests
```py
import mechanicalsoup
import cfscrape
sess =cfscrape.create_scraper()
browser = mechanicalsoup.StatefulBrowser(session=sess)
`

**Comment by Anorov** [comment]
I'd recommend @lord8266's answer.
