### ISSUE TITLE
KeyError: 'location'  (line 195 in solve_cf_challenge)

### ISSUE THREAD

**Issue by technetium** [Anorov/cloudflare-scrape#325]
Before creating an issue, first upgrade cfscrape with `pip install -U cfscrape` and see if you're still experiencing the problem. Please also confirm your Node version (`node --version` or `nodejs --version`) is version 10 or higher.

$ node -v
v12.14.1

Make sure the website you're having issues with is actually using anti-bot protection by Cloudflare and not a competitor like Imperva Incapsula or Sucuri. And if you're using an anonymizing proxy, a VPN, or Tor, Cloudflare often flags those IPs and may block you or present you with a captcha as a result.

Please **confirm the following statements and check the boxes** before creating an issue:

- [x] I've upgraded cfscrape with `pip install -U cfscrape`
- [x] I'm using Node version 10 or higher
- [x] The site protection I'm having issues with is from Cloudflare
- [x] I'm not using Tor, a VPN, or an anonymizing proxy

## Python version number

Run `python --version` and paste the output below:

```
$ python --version
Python 3.7.4
```

## cfscrape version number

Run `pip show cfscrape` and paste the output below:

```
$ pip show cfscrape
Name: cfscrape
Version: 2.0.8
Summary: A simple Python module to bypass Cloudflare's anti-bot page. See https://github.com/Anorov/cloudflare-scrape for more information.
```

## Code snippet involved with the issue

```
import cfscrape

url_login = 'https://www.geldvoorelkaar.nl/mijn'
headers = {
    'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'accept-encoding': 'gzip, deflate',
    'accept-language': 'en-US,en;q=0.9,nl;q=0.8',
    'cache-control': 'max-age=0',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'upgrade-insecure-requests': '1',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
}
session = cfscrape.create_scraper()
res = session.get(url_login, headers=headers)

```

## Complete exception and traceback

```
$ py cfscrape-test.py
Traceback (most recent call last):
  File "cfscrape-test.py", line 15, in <module>
    res = session.get(url_login, headers=headers)
  File "C:\Users\Win\Anaconda3\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Win\Anaconda3\lib\site-packages\cfscrape\__init__.py", line 128, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "C:\Users\Win\Anaconda3\lib\site-packages\cfscrape\__init__.py", line 195, in solve_cf_challenge
    redirect_location = urlparse(redirect.headers["Location"])
  File "C:\Users\Win\Anaconda3\lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'

```

## URL of the Cloudflare-protected page
https://www.geldvoorelkaar.nl/mijn

## URL of Pastebin/Gist with HTML source of protected page
https://gist.github.com/technetium/07c45dec55fec126072fe9c0da996498
[cloudflare.txt](https://github.com/Anorov/cloudflare-scrape/files/4102330/cloudflare.txt)

**Comment by technetium** [comment]
This looks a lot like issue #313 
I can confirm pull #315 fixes the problem.

**Comment by amiradib** [comment]
i have this issue, and see #313 issue also
my module is update
how fix it?
