### ISSUE TITLE
Error with cloudscraper

### ISSUE THREAD

**Issue by hugogva** [Anorov/cloudflare-scrape#327]
Before creating an issue, first upgrade cfscrape with `pip install -U cfscrape` and see if you're still experiencing the problem. Please also confirm your Node version (`node --version` or `nodejs --version`) is version 10 or higher.

Make sure the website you're having issues with is actually using anti-bot protection by Cloudflare and not a competitor like Imperva Incapsula or Sucuri. And if you're using an anonymizing proxy, a VPN, or Tor, Cloudflare often flags those IPs and may block you or present you with a captcha as a result.

Please **confirm the following statements and check the boxes** before creating an issue:

- [x] I've upgraded cfscrape with `pip install -U cfscrape`
- [x] I'm using Node version 10 or higher
- [x] The site protection I'm having issues with is from Cloudflare
- [x] I'm not using Tor, a VPN, or an anonymizing proxy

## Python version number

Run `python --version` and paste the output below:

```

```

## cfscrape version number

Run `pip show cfscrape` and paste the output below:

```

```

## Code snippet involved with the issue

```

```

## Complete exception and traceback

(*If the problem doesn't involve an exception being raised, leave this blank*)

```

```

## URL of the Cloudflare-protected page

https://www.sneakers76.com/en/authentication?back=my-account

## URL of Pastebin/Gist with HTML source of protected page

https://pastebin.com/QLv2Ddiu

**Comment by Anorov** [comment]
This should be fixed in the latest version. Please update with `pip install -U cfscrape`.
