### ISSUE TITLE
Implement same for sockets

### ISSUE THREAD

**Issue by Izakun** [Anorov/cloudflare-scrape#329]
That's a cool lib. It's possible to implement the same think on a sockets connection to a server protected by CloudFlare ?

**Comment by Anorov** [comment]
Not sure what you mean. Cloudflare is a reverse proxy for HTTP/HTTPS traffic, so it only makes sense in the context of HTTP communication. cfscrape builds on requests, which builds on urllib3, which builds on the standard library's http.client.HTTPConnection, which uses sockets.

If you'd prefer to not use the underlying requests API, you could try swapping it out for a different library, but you'd have to rewrite almost everything.

**Comment by Izakun** [comment]
I create a request on my server to know its status (something very similar to a ping). This request uses sockets but each time falls in error due to the system set up by couldflare.
`
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.settimeout(4)
    if args.https:
        s = ssl.wrap_socket(s)

    s.connect((ip, port))
    return s`
I know my english suck
