### ISSUE TITLE
No exception or traceback when cloudscraper doesn't work

### ISSUE THREAD

**Issue by YuKangYin1997** [Anorov/cloudflare-scrape#337]
I can get html text from a cloudflare protected website successfully sometimes, but in other cases I cannot get html text from the same website, and there are no error or exception messages in the terminal even if I try to catch exceptions by ```try exception``` .  I mean although this problem doesn't appear every time I run my code, it does appear sometimes with no reasons. Since I request this website very often, I don't know if it is because my IP has been blocked by the website?

Please **confirm the following statements and check the boxes** before creating an issue:

- [x] I've upgraded cfscrape with `pip install -U cfscrape`
- [x] I'm using Node version 10 or higher
- [x] The site protection I'm having issues with is from Cloudflare
- [x] I'm not using Tor, a VPN, or an anonymizing proxy

## Python version number

Run `python --version` and paste the output below:

```
Python 3.7.0
```

## cfscrape version number

Run `pip show cfscrape` and paste the output below:

```
Name: cfscrape
Version: 2.1.1
Summary: A simple Python module to bypass Cloudflare's anti-bot page. See https://github.com/Anorov/cloudflare-scrape for more information.
Home-page: https://github.com/Anorov/cloudflare-scrape
Author: Anorov
Author-email: anorov.vorona@gmail.com
License: UNKNOWN
Location: /root/anaconda3/envs/Py37Django/lib/python3.7/site-packages
Requires: requests
Required-by: 
```

## Code snippet involved with the issue

```
def get_html_text(url):
    scraper = cloudscraper.create_scraper()  # returns a CloudScraper instance
    header = {
        'user_agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36',
    }
    try:
        html_text = scraper.get(url, headers=header).content.decode('utf-8')
        return html_text
    except Exception as e:
        print(str(e))
        return None

def main():
    url = 'https://www.biovision.com/'
    return get_html_text(url)

main()
```

## Complete exception and traceback

(*If the problem doesn't involve an exception being raised, leave this blank*)

```
The problem is there are no exception or traceback...
```

## URL of the Cloudflare-protected page

["https://www.biovision.com/"]

## URL of Pastebin/Gist with HTML source of protected page

[LINK GOES HERE]

**Comment by lord8266** [comment]
looks like you are using cloudscraper?
post the issue [here](https://github.com/VeNoMouS/cloudscraper/issues)
