### ISSUE TITLE
response returns 403 Forbidden today trying cfscrape

### ISSUE THREAD

**Issue by deltaformation** [Anorov/cloudflare-scrape#34]
Tried in python3 doesn't work, python2.7 works fine tho O_O

>#!/usr/bin/env python
>import cfscrape

>scraper = cfscrape.create_scraper() # returns a requests.Session object
>print (scraper.get("https://testsite.com").text)

Response text 

>`Desktop$ python3 testcf.py
><html>
><head><title>403 Forbidden</title></head>
><body bgcolor="white">
><center><h1>403 Forbidden</h1></center>
><hr><center>nginx</center>
></body>
></html>`

Any reason why it's being blocked ?

**Comment by Anorov** [comment]
I've just released an update. Please check and see if the issue is resolved now.
