### ISSUE TITLE
Emails obfuscated

### ISSUE THREAD

**Issue by rubix1138** [Anorov/cloudflare-scrape#38]
I am scraping a CF site and for the email field, I am getting:

    u'/cdn-cgi/l/email-protection#8fe6e1e9e0cfe2e0eeede7eee3e9e2eefdeefbe7e0e1a1ece0e2'

Googling around, this looks like a Cloudflare feature called "E-mail address obfuscation".  Source: https://sendy.co/forum/discussion/4956/email-addresses-in-email-body-converted-to-email-protected/p1

I found this solution and wanted to share in case you wanted to add it add it as a function.  http://www.saltycrane.com/blog/2015/07/calling-javascript-python-de-cloudflare-scraped-content/

**Comment by Anorov** [comment]
Hmmm, I'm not sure I want to add this feature. The primary use case for it would be to aid spammers with harvesting email addresses to send spam to, which I don't condone. There exist some valid use-cases for doing this, but I think the majority of people who scrape email addresses don't have good intentions in mind. Sorry.

**Comment by gkesaev** [comment]
Hey, it is pretty easy to fix here is original post:
https://www.saltycrane.com/blog/2015/07/calling-javascript-python-de-cloudflare-scraped-content/

I took me a couple of minutes to translate the code into python, unfortunately cannot share it.
