### ISSUE TITLE
A POST request can not be performed without first performing a GET.

### ISSUE THREAD

**Issue by obskyr** [Anorov/cloudflare-scrape#39]
Trying to perform a POST with a freshly-`create_scraper()`ed scraper times out with the classic `requests.exceptions.ConnectionError: ('Connection aborted.', error(10054, '[locale dependent]'))` error. Performing a GET with the scraper first, and then the POST, works just fine.

I haven't tested this on a lot of sites, so it may not be generalizable this way, but it sure does seem like it.

**Comment by Anorov** [comment]
I've just released an update. Can you tell me if this problem is fixed? I am not able to reproduce it.

**Comment by obskyr** [comment]
It's not fixed, still, as it turns out. The `ConnectionError` was site-specific, though: what really happens is performing anything other than a GET as the first request actually *transforms* the request into a GET anyway.

If the server has no GET endpoint for that location, a `ConnectionError` might occur, or the wrong page might be returned. So... this is still an issue.

I've managed to fix it, however - pull request incoming shortly. I guess you'll get to open and close this issue real fast. ;)
