### ISSUE TITLE
Cookie expire?

### ISSUE THREAD

**Issue by NitroXenon** [Anorov/cloudflare-scrape#40]
I am running a online private web server which can help me bypass cloudflare. After running for about a month, the scraper did not bypass cloudflare. Instead, it return the original browser checking page. So is it the problem of cookie expiration? How to fix it as well?

**Comment by Anorov** [comment]
There is no good way to fix this. The best way is by adding some code to detect whether a cookie is expired, and to re-run cloudflare-scrape when this happens.
