### ISSUE TITLE
Cant remote upload the picture

### ISSUE THREAD

**Issue by capsload** [Anorov/cloudflare-scrape#43]
Hello.

im trying to remote upload pictures from 4fuckr.com to my host.

Now the problem: 4fuckr.com set the 5 seconds anti ddos protection by cloudflare. well fine, we just grab the cookies and done.

Its still not remote upload them to my host :<

Here's what i've done so far:

(remote upload script.php):
http://hastebin.com/raw/ufikasiqob

(getting cookies from 4fuckr website)
http://hastebin.com/raw/udoqotixog

(this is how cookies.txt looks like)
Cookie: cf_clearance=410e1a48ad9474304d7936c965373cbfdbf1f77d-1458209645-14400; __cfduid=d93afdc905b7cb5ca3f3bc9cd60a263dc1458209640

and thats how i "catch" images from 4fuckr.com

http://weserv.capsload.it/push_nolog.php?p=https://images.4fuckr.com/cf57da1df454/6/c/8/d/6/6c8d67c209.jpg

Problem: PICTURES ARE WHITE (0KB) 

Its just from that website. :(

**Comment by Anorov** [comment]
I believe you may not be using curl's cookie functionality correctly. Check out curl's documentation.
