### ISSUE TITLE
Extend the Session object?

### ISSUE THREAD

**Issue by cvium** [Anorov/cloudflare-scrape#46]
Would it be possible to have it extend the Session object in https://github.com/Anorov/cloudflare-scrape/blob/master/cfscrape/__init__.py#L106 instead of replacing it?

We currently use cloudflare-scrape in https://github.com/Flexget/Flexget, but we extend the requests Session object to better suit our needs, which means we can't use `create_scraper` without losing functionality.

**Comment by Anorov** [comment]
Previous versions of this project used transport adapters, which effectively do extend session objects. But adapters really aren't designed for these purposes, and it was getting too ugly to maintain.

Would you not being able to have a class extend the `CloudflareScraper` class in some way?

**Comment by cvium** [comment]
I have some things in mind that I'll try, I just wanted to know if it was possible to fix it upstream rather than me trying to hack it to fit our needs.

I'll give it a whirl. Thanks.

**Comment by Anorov** [comment]
I'd be willing to fix it if there were an easy way. I do a very light form of extension here, copying some of the session's instance variables, but I imagine that's not sufficient for this case: https://github.com/Anorov/cloudflare-scrape/blob/master/cfscrape/__init__.py#L124

If you are aware of a fairly simple way to do it here (without reverting back to a transport adapter), or were willing to contribute a PR, I'd certainly be interested.

**Comment by cvium** [comment]
Can't think of anything that isn't a complete hack. I'm probably just gonna create a wrapper.
