### ISSUE TITLE
New CF technique: cvId 2, non-interactive

### ISSUE THREAD

**Issue by AltayAkkus** [Anorov/cloudflare-scrape#461]
So a lot of issues have been stacking up for the challenge type, and I have looked into it:
https://gist.github.com/AltayAkkus/591dbef9872c9148d6effb06bcc5417b
The html returned has a huge array that stores user-specific options, the website, the time started, a random nonce, how long the delay should be etc.

This is deposited into window._cf_chl_opt and read by the javascript that is imported via the cpo element.
Looking at it, it is randomly generating, reads the clouflare challenge options, and generates a hash which is appended to the URI.
The js changes for different rayIds, so yeah well fuck.

**Comment by PaulinBenoit** [comment]
Hi, I was looking at your repo because I have the same problem as you are mentionning here. I havn't been able to find any solution to resolve this challenge yet. Were you able to work on it ? Do you think that cfscrape could be adapted to bypass this challenge ?

**Comment by AltayAkkus** [comment]
if you add a whole javascript environment which simulates your browser and passes the checks, yes.

**Comment by lord8266** [comment]
@AltayAkkus And if you exceed some rate limit and trigger captcha then you will need to use a captcha solver service (which is usually paid)

**Comment by AltayAkkus** [comment]
yea they have essentially won.

**Comment by AltayAkkus** [comment]
closing because they won

**Comment by phantie** [comment]
> closing because they won

headless browser + good proxy, cheers.
