### ISSUE TITLE
Licence ? Package ?

### ISSUE THREAD

**Issue by xfouloux** [Anorov/cloudflare-scrape#5]
Hi,

I find your tool very usefull, is there a licence for the code ?
I would like to include your code into flexget (http://flexget.com/) so I prefer MIT so they can include it

Or else, you could maybe pack it as a pypi package ?

Regards.

**Comment by Anorov** [comment]
License added.

Will also upload to PyPI soon.

**Comment by Anorov** [comment]
Now on PyPI as `cfscrape`. Installation is a `pip install cfscrape` away.
