### ISSUE TITLE
Start a new session once it expires

### ISSUE THREAD

**Issue by zacharydenton** [Anorov/cloudflare-scrape#50]
CloudFlare only lets you perform a certain number of requests until the session expires. Can we use [response hooks](http://docs.python-requests.org/en/master/user/advanced/#event-hooks) to check if the page is the challenge page, and if so, start a new session?

Or is there another reason why this isn't possible (I see this has been [asked before](https://github.com/Anorov/cloudflare-scrape/issues/40))?

**Comment by Anorov** [comment]
I'll look into this.

**Comment by Anorov** [comment]
I changed the code to just constantly re-check for the challenge page headers, rather than checking if we have a cookie set. I believe my initial reason for not doing so was potential performance impact, but the overhead should be so minuscule that it really doesn't matter.

Can you try now?
