### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by 5vbz3r0** [Anorov/cloudflare-scrape#60]
For a few days now (last it worked was on 5/6/16), the module isn't working properly.
No exception is thrown, but there is utterly no sort of response. When I stop my program with a `ctrl+c`, I get the following:
`Traceback (most recent call last):`
`File "E:\Kissanime-dl\kissanime-dl.py", line 188, in <module>`
`return bs(cfscraper.create_scraper().get(url).content, 'lxml')`
  followed by an endless loop of
`File "C:\Tools\Anaconda\lib\site-packages\requests\sessions.py", line 487, in get  
return self.request('GET', url, **kwargs)`
`File "C:\Tools\Anaconda\lib\site-packages\cfscrape\__init__.py", line 30, in request  
return self.solve_cf_challenge(resp, **kwargs)`
`File "C:\Tools\Anaconda\lib\site-packages\cfscrape\__init__.py", line 69, in solve_cf_challenge  
return self.get(submit_url, **kwargs)`  
and finally,  
`File "C:\Tools\Anaconda\lib\site-packages\cfscrape\__init__.py", line 36, in solve_cf_challenge  
  time.sleep(5)   #Cloudflare requires a delay before solving the challenge`  

The page I'm trying to scrape is [KissAnime](www.kissanime.to).  
And [here](http://pastebin.com/Tq1UKXy3) is the source code of the page.  

I just noticed that somebody else had an issue with the same page, but that issue was marked closed. And my Traceback seems to be different.

**Comment by jQwotos** [comment]
Can confirm that it's stuck on an infinite loop when trying to scrape from KissAnime.to Was working yesterday (June 8)

**Comment by berdt** [comment]
Same issue.

**Comment by js19707** [comment]
same issue, different site (flightXXXradar24.com, remove XXX), was working yesterday

**Comment by matoro** [comment]
Seems to be a recursion issue.  If you let it run for long enough you eventually end up with the following at the end of the run:

```
File "/usr/lib/python3.5/site-packages/cfscrape/__init__.py", line 25, in request
    resp = super(CloudflareScraper, self).request(method, url, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 606, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 606, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 179, in resolve_redirects
    **adapter_kwargs
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 483, in send
    return self.build_response(request, resp)
  File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 234, in build_response
    response = Response()
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 554, in __init__
    self.headers = CaseInsensitiveDict()
  File "/usr/lib/python3.5/site-packages/requests/structures.py", line 48, in __init__
    self.update(data, **kwargs)
  File "/usr/lib/python3.5/_collections_abc.py", line 771, in update
    if isinstance(other, Mapping):
  File "/usr/lib/python3.5/abc.py", line 182, in __instancecheck__
    if subclass in cls._abc_cache:
  File "/usr/lib/python3.5/_weakrefset.py", line 72, in __contains__
    wr = ref(item)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by js19707** [comment]
i see the same thing:

RuntimeError: maximum recursion depth exceeded
(Python 2.7)

**Comment by matoro** [comment]
Actually now that I think about it this probably is related to the way Cloudflare does its redirects.  I have a ton of security-related stuff on my browser such that all but the most simple of sites will break and after passing the JS check, it gets stuck in a redirect loop and I have to go back a page to actually see it.  So this probably has something to do with ```cfscrape``` getting stuck in a redirect loop.

**Comment by Anorov** [comment]
Yes, I'm actually getting the redirect-loop problem occasionally with my regular browser on some Cloudflare sites. They must have pushed a change yesterday that tries to more aggressively detect script-like behavior.

Currently investigating it.

**Comment by platedodev** [comment]
Same here

**Comment by platedodev** [comment]
This is the new change pushed:
```
            <![CDATA[
  (function(){
    var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },
    b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};
    b(function(){
      var a = document.getElementById('cf-content');a.style.display = 'block';
      setTimeout(function(){
        var s,t,o,p,b,r,e,a,k,i,n,g,f, JfkfEkM={"RYwbsG":+((!+[]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]))};
        t = document.createElement('div');
        t.innerHTML="<a href='/'>x</a>";
        t = t.firstChild.href;r = t.match(/https?:\/\//)[0];
        t = t.substr(r.length); t = t.substr(0,t.length-1);
        a = document.getElementById('jschl-answer');
        f = document.getElementById('challenge-form');
        ;JfkfEkM.RYwbsG-=+((!+[]+!![]+!![]+[])+(!+[]+!![]+!![]));JfkfEkM.RYwbsG+=+((+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));JfkfEkM.RYwbsG*=+((!+[]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));JfkfEkM.RYwbsG-=!+[]+!![];JfkfEkM.RYwbsG*=+((!+[]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));JfkfEkM.RYwbsG+=+((!+[]+!![]+!![]+[])+(!+[]+!![]));JfkfEkM.RYwbsG-=+((!+[]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));a.value = parseInt(JfkfEkM.RYwbsG, 10) + t.length; '; 121'
        f.submit();
      }, 4000);
    }, false);
  })();
  //]]>
```

**Comment by Anorov** [comment]
It looks like they may actually have pushed this change specifically to confuse cloudflare-scrape, due to how we're pulling the JS challenge with regex.

Please tell me if the most recent commit resolves the issue.

**Comment by platedodev** [comment]
It works! :+1: :dancers:

**Comment by Anorov** [comment]
:ok_hand:

**Comment by platedodev** [comment]
Just a parseInt?

**Comment by matoro** [comment]
Awesome! When can we expect this on pypi?  I've got a few friends using the script I wrote and it's much easier to just give them a command to update a package.  Much thanks for your hard work!

**Comment by 5vbz3r0** [comment]
Its on pypi already.

**Comment by matoro** [comment]
Hmm, that's weird, I'm still getting the same error despite not having made any changes to my script.  Will investigate further.  If it still doesn't work I'll post full source code.

**Comment by Anorov** [comment]
Make sure you're doing a pip upgrade, so that it's actually replacing the package. It's still working in my tests.

@platedodev No, they added a "'; [randomnumber]'" at the end to confuse any scripts using a regex to grab everything past a certain point.

    a.value = parseInt(JfkfEkM.RYwbsG, 10) + t.length; '; 121'

This was making cloudflare-scrape effectively see:

    a.value = 121;

**Comment by matoro** [comment]
Still cannot seem to get this to work.  Most definitely on the latest version of cfscrape.  Full source code is here:  https://ghostbin.com/paste/3fu2g/raw
Be warned, it does install several things including nodejs, python, pip, cfscrape, and html-xml-utils if you don't already have them installed on your system, so you can install them via your package manager of choice if you don't want them to be built from source.

I would appreciate anyone giving this a try to see what the problem is.  See https://github.com/Anorov/cloudflare-scrape/issues/55 for a little bit more detail on how cfscrape integration is implemented.

**Comment by Anorov** [comment]
@matoro Note that the default user agent has been changed. You should pass the user agent you're using in `downloadlist()` into `get_cookie_string()`.

Given the current code, you'd do something like:

    echo "import cfscrape; cookie_arg, user_agent = cfscrape.get_cookie_string(\"https://kissanime.to\", user_agent=\"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0\"); print (cookie_arg)" > "$RUNDIR/aniwatch-getcookies.py"
