### ISSUE TITLE
cloudflare header changes

### ISSUE THREAD

**Issue by Twoure** [Anorov/cloudflare-scrape#64]
`Refresh` header value is now missing for initial scrape of page, resulting in `cfscrape` failing to know to solve for a challenge.

Line [37](https://github.com/Anorov/cloudflare-scrape/blob/master/cfscrape/__init__.py#L37) needs to be updated to reflect current changes.  I did a quick patch by replacing line 37 with a HTTP 503 error check and left line 38 the same ([example](https://github.com/Twoure/KissNetwork.bundle/commit/5dc5fbaabd1035357f4bf8e9f691f286a4965303)).  Not sure if the best option for a fix, but don't see any other values within the headers that would be an anti-bot indicator.

**Comment by Anorov** [comment]
Thanks. I've made appropriate changes and uploaded to PyPI.
