### ISSUE TITLE
I want to contribute by building this in node.js

### ISSUE THREAD

**Issue by irfaan008** [Anorov/cloudflare-scrape#68]
By seeing the popularity of node.js I believe that we should convert your precious work into some kind of npm module. If you can help me on this then I could be a contributor on this. Let me know your thought on this.
What I need from you : 

1. Basic flow of process
2. Things to keep in mind

PS : I am not comfortable in python

**Comment by int3l** [comment]
There is such module already: [cloudscraper](https://github.com/codemanki/cloudscraper)
It is almost the same implementation but in JS.
