### ISSUE TITLE
Unable to Bypass on URLs with Permanent Redirection(301)

### ISSUE THREAD

**Issue by kryptodev** [Anorov/cloudflare-scrape#71]
What I did:

I got cookies and useragent that was provided by the module, then I used that information to enter the home page which results in complete bypass with status code 200.

HOWEVER, when I used the same information on a page that has 301 redirection, I got the interstitial page from cloudflare.

I wonder what's the root cause for this.

Kindly assist.

**Comment by Coriou** [comment]
Do you have an example this could be tested against ?

**Comment by Anorov** [comment]
I believe this should have been fixed in one of the recent updates.
