### ISSUE TITLE
js2py setup errors on CentOS 6

### ISSUE THREAD

**Issue by ZizzyZizzy** [Anorov/cloudflare-scrape#73]
Errors during setup, but installs it anyway.
# rpm -qa | grep -i ^python | sort -V
python-2.6.6-64.el6.x86_64
python-argparse-1.2.1-2.1.el6.noarch
python-ethtool-0.6-5.el6.x86_64
python-iniparse-0.3.1-2.1.el6.noarch
python-inotify-0.9.1-1.el6.noarch
python-iwlib-0.1-1.2.el6.x86_64
python-libs-2.6.6-64.el6.x86_64
python-pycurl-7.19.0-8.el6.x86_64
python-setuptools-0.6.10-3.el6.noarch
python-urlgrabber-3.9.1-9.el6.noarch

# python setup.py install
(snipped successful output for cfscrape)

Processing dependencies for cfscrape==1.6.6
Searching for Js2Py==0.37
Reading http://pypi.python.org/simple/Js2Py/
Best match: Js2Py 0.37
Downloading https://pypi.python.org/packages/8c/81/586fc7316d3e93b1b69a8fd56bfa559a441c7b5eb466d82cfe43f31350ec/Js2Py-0.37.tar.gz#md5=915b81ddeee6dafcd019737eaf7e8ae7
Processing Js2Py-0.37.tar.gz
Running Js2Py-0.37/setup.py -q bdist_egg --dist-dir /tmp/easy_install-3cOcXQ/Js2Py-0.37/egg-dist-tmp-vwi_JX
SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/js2py/host/jsfunctions.py', 13, 36, "    if string and string[0] in {'+', '-'}:\n"))

SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/js2py/constructors/jsobject.py', 21, 35, "        elif val.TYPE in {'Number', 'String', 'Boolean'}:\n"))

SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/js2py/translators/translating_nodes.py', 255, 45, "        if argument['type'] in {'Identifier', 'MemberExpression'}:\n"))

SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/js2py/translators/pyjsparserdata.py', 46, 20, 'TokenName = {v:k for k,v in token.items()}\n'))

SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/js2py/translators/friendly_nodes.py', 76, 28, "        if e[0] not in {'(', '[', '{'}:\n"))

SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/js2py/translators/jsregexps.py', 3, 30, "REGEXP_SPECIAL_SINGLE = {'\\\\', '^', '$', '*', '+', '?', '.'}\n"))

SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/js2py/translators/pyjsparser.py', 25, 30, "REGEXP_SPECIAL_SINGLE = {'\\\\', '^', '$', '*', '+', '?', '.', '[', ']', '(', ')', '{', '{
', '|', '-'}\n"))

SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/js2py/translators/std_nodes.py', 528, 37, '        return {k:node_to_dict(v) for k,v in six.iteritems(node)}\n'))

SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/js2py/pyjs.py', 50, 22, 'JS_BUILTINS = {k:v for k,v in scope.items()}\n'))

SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/js2py/prototypes/jsjson.py', 46, 44, "                    if v.Class in {'String', 'Number'}:\n"))

SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/js2py/prototypes/jsarray.py', 154, 38, "        if not this.Class in {'Array', 'Arguments'}:\n"))

SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/js2py/base.py', 205, 28, "    PRIMITIVES =  {'String', 'Number', 'Boolean', 'Undefined', 'Null'}\n"))

zip_safe flag not set; analyzing archive contents...
js2py.host.jseval: module MAY be using inspect.stack
SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/Js2Py-0.37-py2.6.egg/js2py/pyjs.py', 50, 22, 'JS_BUILTINS = {k:v for k,v in scope.items()}\n'))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/Js2Py-0.37-py2.6.egg/js2py/base.py', 205, 28, "    PRIMITIVES =  {'String', 'Number', 'Boolean', 'Undefined', 'Null'}\n"))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/Js2Py-0.37-py2.6.egg/js2py/host/jsfunctions.py', 13, 36, "    if string and string[0] in {'+', '-'}:\n"))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/Js2Py-0.37-py2.6.egg/js2py/constructors/jsobject.py', 21, 35, "        elif val.TYPE in {'Number', 'String', 'Boolean'}:\n"))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/Js2Py-0.37-py2.6.egg/js2py/translators/translating_nodes.py', 255, 45, "        if argument['type'] in {'Identifier', 'MemberExpr
ession'}:\n"))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/Js2Py-0.37-py2.6.egg/js2py/translators/pyjsparserdata.py', 46, 20, 'TokenName = {v:k for k,v in token.items()}\n'))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/Js2Py-0.37-py2.6.egg/js2py/translators/friendly_nodes.py', 76, 28, "        if e[0] not in {'(', '[', '{'}:\n"))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/Js2Py-0.37-py2.6.egg/js2py/translators/jsregexps.py', 3, 30, "REGEXP_SPECIAL_SINGLE = {'\\\\', '^', '$', '*', '+', '?', '.'}\n"))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/Js2Py-0.37-py2.6.egg/js2py/translators/pyjsparser.py', 25, 30, "REGEXP_SPECIAL_SINGLE = {'\\\\', '^', '$', '*', '+', '?', '.', '[
', ']', '(', ')', '{', '{', '|', '-'}\n"))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/Js2Py-0.37-py2.6.egg/js2py/translators/std_nodes.py', 528, 37, '        return {k:node_to_dict(v) for k,v in six.iteritems(node)}
\n'))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/Js2Py-0.37-py2.6.egg/js2py/prototypes/jsjson.py', 46, 44, "                    if v.Class in {'String', 'Number'}:\n"))

SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/Js2Py-0.37-py2.6.egg/js2py/prototypes/jsarray.py', 154, 38, "        if not this.Class in {'Array', 'Arguments'}:\n"))

Adding Js2Py 0.37 to easy-install.pth file

Installed /usr/lib/python2.6/site-packages/Js2Py-0.37-py2.6.egg
Searching for requests==2.10.0

**Comment by vivescere** [comment]
Just checked, python 2.6 does not supports the syntax `"x" in {"x", "y"}`.

You could try a pull request using maybe lists to the js2py repo, but I think that switching to python 2.7 would be easier, I don't think there are [a lot of changes](http://stackoverflow.com/questions/21338119/switching-to-python-2-7-from-2-6) to do.

**Comment by ZizzyZizzy** [comment]
For other CentOS 6.x users:

yum -y install centos-release-SCL
yum -y install python27
scl enable python27  "python2.7 setup.py install"

The "scl enable python27" command allows you to gracefully use Python 2.7 with anything that requires it, without bricking yum on your server. (Yum on CentOS 6.x still requires Python 2.6.) Using scl will cause everything v2.7 to be maintained in /opt/redhat/python27/.
