### ISSUE TITLE
Getting "just a moment"

### ISSUE THREAD

**Issue by platedodev** [Anorov/cloudflare-scrape#77]
[](https://python-plateadodev.c9users.io/cgi-bin/seriesblanco.py?url=http://seriesblanco.com/)
I can't make it work. I'm just getting redirect, this is my code:
```
scraper = cfscrape.create_scraper()  # returns a CloudflareScraper instance
    headers = {'referer': 'http://seriesblanco.com/'}
    just_loggin = scraper.get(form.getvalue('url')) 
    print scraper.get(form.getvalue('url') , headers=headers).content  # => "<!DOCTYPE html><html><head>..."
```
Is something wrong with it?, thanks in advance.

Getting the page:

> Checking your browser before accessing seriesblanco.com.
> 
> This process is automatic. Your browser will redirect to your requested content shortly.
> Please allow up to 5 seconds…
> DDoS protection by CloudFlare 
> Ray ID: 2e04c766319425b5

And then:

> The requested URL /cdn-cgi/l/chk_jschl was not found on this server.
on my server.

**Comment by Twoure** [comment]
Works fine here.  I see the site provided pass cookie expires in a year, so you don't need to keep asking for a fresh cookie all the time.  Refer to https://github.com/Anorov/cloudflare-scrape/issues/72#issuecomment-236493353 for more info.

As for `cfscrape` usage, I've included 3 different examples below.  Move comments around to test each example.

```py
#!/usr/bin/env python

from lxml import html as HTML
import cfscrape
import requests

USER_AGENT = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'
HTTP_HEADERS = {'User-Agent': USER_AGENT}

URL = 'http://seriesblanco.com/serie/969/temporada-7/capitulo-06/archer.html'
BASE_URL = 'http://' + URL.rsplit('/')[2]

# ---                   Example 1                   --- #
# --- Setup Session with User-Agent and Referer set --- #
HTTP_HEADERS['Referer'] = BASE_URL
s = requests.session()
s.headers = HTTP_HEADERS

scraper_one = cfscrape.create_scraper(sess=s)
r = scraper_one.get(URL)

"""
# ---                           Example 2                         --- #
# --- Let cfscrape determin User-Agent, then manually set Referer --- #
scraper_two = cfscrape.create_scraper()

r = scraper_two.get(URL, headers={'Referer': BASE_URL})

# ---                           Example 3                                --- #
# --- Setup headers with User-Agent (must be the same across all calls) --- #
# --- scrape for cookies, then add to headers, then use within each call --- #
cookies, user_agent = cfscrape.get_cookie_string(url=BASE_URL, user_agent=USER_AGENT)
HTTP_HEADERS.update({'Cookie': cookies, 'Referer': BASE_URL})

r = requests.get(URL, headers=HTTP_HEADERS)
"""

# ---------------- Same results for all Examples --------------------------- #
#print(r.text)  # return page results in text format
print(HTML.fromstring(r.text))  # return page results in html format
print(r.status_code)  # check response status code
```

**Comment by platedodev** [comment]
@Twoure [Check this](https://python-plateadodev.c9users.io/cgi-bin/seriesblanco.py?url=http://seriesblanco.com/)

This is my code:
```
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# enable debugging
import cgi
import cgitb
import cfscrape
import requests;

cgitb.enable()
form = cgi.FieldStorage()

print "Content-type: text/html"
print ""
if not form.getvalue('url'):
    print "No url."
else:
    s = requests.session()
    URL = form.getvalue('url');
    BASE_URL = 'http://' + URL.rsplit('/')[2]
    USER_AGENT = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'
    HTTP_HEADERS = {'User-Agent': USER_AGENT}
    s.headers = HTTP_HEADERS
    # s, user_agent = cfscrape.get_cookie_string(url=BASE_URL, user_agent=USER_AGENT)
    HTTP_HEADERS.update({'Referer': BASE_URL})

    r = requests.get(URL, headers=HTTP_HEADERS)
    print r.content  # => "<!DOCTYPE html><html><head>..."
```

I used your examples but didn't work, can you check if works for you?.

**Comment by Twoure** [comment]
@platedodev Looks like you tried to combine Example 1 & 3, but left out some parts.  Assuming you wanted Example 3, the code should look as follows:

```py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# enable debugging
import cgi
import cgitb
import cfscrape
import requests

USER_AGENT = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"

cgitb.enable()
form = cgi.FieldStorage()

print "Content-type: text/html"
print ""
if not form.getvalue('url'):
    print "No url."
else:
    url = form.getvalue('url');
    base_url = "http://" if url.startswith("http:") else "https://" + url.rsplit('/')[2]
    http_headers = {'User-Agent': USER_AGENT}
    tokens = cfscrape.get_cookie_string(url=base_url, user_agent=USER_AGENT)
    http_headers.update({'Cookie': tokens[0], 'Referer': base_url})

    r = requests.get(url, headers=http_headers)
    print r.content  # => "<!DOCTYPE html><html><head>..."
```

Make sure to include the headers for each call after scraping for the cookies.  Otherwise use a session and let `cfscrape` handle the cookies internally.

**Comment by platedodev** [comment]
@Twoure Thanks man!, but I'm getting this error:

> <class 'requests.exceptions.HTTPError'>: 503 Server Error: Service Temporarily Unavailable 
>       args = ('503 Server Error: Service Temporarily Unavailable',) 
>       errno = None 
>       filename = None 
>       message = '503 Server Error: Service Temporarily Unavailable' 
>       response = <Response [503]> 
>       strerror = None

[Error here](https://anti-cf-plateadodev.c9users.io/cgi-bin/seriesblanco.py?url=http://seriesblanco.com/)

But the web is not showing any errors: http://seriesblanco.com/

**Comment by Twoure** [comment]
From your error page, I can see that you are using an outdated version of `cloudflare-scrape`.  Try updating and see if it fixes your issue.

**Comment by platedodev** [comment]
@Twoure I'm using cfscrape 1.6.6, same error :(

**Comment by Twoure** [comment]
Sorry, didn't realize the current master branch is three commits ahead of `1.6.6`.  However, I did notice the `js_engine` param within `/home/ubuntu/workspace/cgi-bin/cfscrape/__init__.pyc`, note its removal [here](https://github.com/Anorov/cloudflare-scrape/compare/1.6.5...1.6.6#diff-4e177b02b8bc8a449744bea7e162031cL156).  This is an indication of an older version.  Perhaps the `.pyc` didn't recompile after the update, hence using old code.

**Comment by platedodev** [comment]
@Twoure I did a git clone of cloudflare-scrape master and now works, thanks mate :).

**Comment by NickPotterfield** [comment]
I need help on how to fix this problem. I've waited for more that five seconds. And it just loops back to "just a moment". Can somebody please help me.

**Comment by saichandrareddy1** [comment]
@NickPotterfield I too ran into the same issue, can anyone please help me, if you solve can please send me the process.

@Twoure please check my issue

Error i got
HTTPError: 403 Client Error: Forbidden for url: https://clutch.co/
