### ISSUE TITLE
Remove js2py dependence?

### ISSUE THREAD

**Issue by Viper2k4** [Anorov/cloudflare-scrape#78]
Hi,

what u think about removing the js2py and using something like this:

https://github.com/elcattivo/CloudFlareUtilities/blob/master/CloudFlareUtilities/ChallengeSolver.cs

Less dependence are the best dependence  ^^

Greetings

*EDIT*
seberoth try a bit and a seems a good start
https://gist.github.com/seberoth/cde4c6edab29cf67cd641fbf2fadff01

**Comment by Anorov** [comment]
Please see https://github.com/Anorov/cloudflare-scrape/issues/62#issuecomment-225374752

And now that Node/PyV8 aren't dependencies, just a pure Python library, I especially see no reason to switch away from JS evaluation.
