### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by shodamaster** [Anorov/cloudflare-scrape#8]
Iam trying to fetch content from Arabic news website but it looks there are encoding problem can you please help fix that?
![unnamed](https://cloud.githubusercontent.com/assets/10523706/5771995/36590e6e-9d52-11e4-8d6c-b93acca2b138.png)

**Comment by Anorov** [comment]
This is an exception generated by `requests`. Try using `.content` instead of `.text`. For further information, consult [requests' documentation](http://docs.python-requests.org/en/latest/user/quickstart/#response-content).
