### ISSUE TITLE
Unable to parse certain pages

### ISSUE THREAD

**Issue by 5vbz3r0** [Anorov/cloudflare-scrape#80]
I get an error when trying to parse the [kissanime](www.kissanime.to) webpage. I can confirm that it was working as of last Sunday.
[Here](http://pastebin.com/EsVHpijg) is the source code of the page.
I'm running cfscrape 1.6.6.

Here is the error report:
![screenshot 19](https://cloud.githubusercontent.com/assets/10692309/19022306/15b80258-88f3-11e6-8b92-a80dc0f0e320.png)

**Comment by 5vbz3r0** [comment]
The problem fixed itself. I've done nothing extra on my end, so I'll leave this issue open in case there's a bug to be squashed.

**Comment by obskyr** [comment]
Oh, look, someone else with the same use case as me! I wrote an object-oriented API for Kissanime a while back using cfscrape. There's been a bit of trouble recently, though, so I gotta take a look at what's causing that...

**Comment by obskyr** [comment]
Hmm. The error suggests an alternate CloudFlare page would be used, but it isn't (anymore, at least). Maybe this issue should be closed until a case appears where an alternate page is used and can be properly documented and the error thus reproduced?

**Comment by 5vbz3r0** [comment]
> The error suggests an alternate CloudFlare page would be used, but it isn't - and wasn't in your case either.

Any idea what could've caused it then?

**Comment by obskyr** [comment]
@5vbz3r0 Some kind of temporary server error, maybe? I don't know if CloudFlare can give you a [500](http://httpstatuses.com/500), [503](http://httpstatuses.com/503), or [504](http://httpstatuses.com/504), but if it did I suppose CFScrape would error out there. That would have to mean the page you provided was grabbed at a time when it didn't error out, however.

**Comment by 5vbz3r0** [comment]
@obskyr I doubt the source grab is wrong. I suppose I'll just have to wait till the error can be reproduced then. Thanks.
