### ISSUE TITLE
not issue, just question

### ISSUE THREAD

**Issue by rangasarin** [Anorov/cloudflare-scrape#82]
Firstly I want to say your module is fantastic and works perfectly, I have a few questions if that's ok?

currently I am making one initial session with `.create_scraper(sess=sess)` then using `.cfscrape.get(someurl).content` and saving the cookie to a file from `.cookies` using `pickle.dump(requests_cookiejar, file)` so every request/session I make from any other .py file I can just do `requests.get(url, cookies=load_cookies(cookiefile)).content` which just loads the cookie from the file using pickle and this works very well and doesn't require the 5 second delay on any requests made from any of my .py file's because it was done initially from the original `.create_scraper`

However.. I have two problems and hoping make you could shed some light on this?

1) how would I turn the cookie that's returned to a readable HTTP cookie like this example: `#HttpOnly_.somesite    TRUE    /   FALSE   1528464221  __cfduid    de8ab1c4e3e11c676b4edfdbae7dc1c245374942278`
2) how would I do all this but setting a user_agent so I can use that in all my requests, because right now it's just using `python-requests/version` which works with that cookie I initially generated.. but I would like to make it something different.

I know this isn't an issue but I hope you wouldn't mind me asking this here?

Once again, fantastic job on the module it works absolutely wonderful! and thank you for your time reading this.

**Comment by Anorov** [comment]
1. You can save the contents of `get_cookie_string()`. Otherwise, just write some Python to convert the `CookieJar` object to whatever format you need.

2. When calling `get_cookie_string()`, you can pass a `user_agent` argument. Otherwise, `create_scraper()` creates a Requests session, so you'll want to consult the Requests documentation for setting a session's user-agent string.
