### ISSUE TITLE
Feature request: cloudflare protected email deobsfuscation

### ISSUE THREAD

**Issue by spiritualized** [Anorov/cloudflare-scrape#84]
First of all, excellent module, it has saved me a lot of time and effort.

Would it be possible to add support for de-obsfuscating cloudflare email fields?

A code snippet detailing the process can be found here: http://www.saltycrane.com/blog/2015/07/calling-javascript-python-de-cloudflare-scraped-content

**Comment by Anorov** [comment]
It would be possible. But I won't be doing it, sorry. It would primarily be used by spammers seeking to harvest email addresses. I definitely don't want to encourage anyone using this library to attack or harass websites or individuals.

**Comment by matoro** [comment]
I will say one annoyance that pops up is that cloudflare matches any string with an "@" symbol as an email address.  So even things like episode titles with an @ in the name get obfuscated.

**Comment by spiritualized** [comment]
This was my problem, too - any time I scrape content with an @ in the middle of a string, it gets converted to a protected email field. So far I have been correcting them manually, but it has been tedious. I have no wish to harvest email addresses. It would have been fine if Cloudflare were using an actual email regex, or didn't have the feature turned on by default.

**Comment by Anorov** [comment]
Sorry about that, but you should take that up with Cloudflare's customer service. I have no doubt the vast majority of people who would use this feature intend on giving it to spammers, even if there are some legitimate use cases.
