### ISSUE TITLE
Issues with PHP

### ISSUE THREAD

**Issue by sjau** [Anorov/cloudflare-scrape#87]
Hi there

A trading site for a game I play got DDoSed the other day and is now behind CF protection as well. So I came accross your tool and as standalone it works well. However my problem is I can't really integrate it into php.

I currently use this python snippet:

```
#!/usr/bin/env python
import subprocess
import cfscrape
ua = "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0"
cookie_arg, user_agent = cfscrape.get_cookie_string("https://poe.trade", user_agent=ua)
# Store cookie
f = open( 'cf_cookie.txt', 'w' )
f.write( cookie_arg )
f.close()
# Store UA
f = open( 'cf_ua.txt', 'w' )
f.write( ua )
f.close()
```

Looking at the stored files actually does return stuff:
```
user@comp # cat cf_ua.txt 
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
user@comp # cat cf_cookie.txt 
cf_clearance=321cf1ec1a9ca256de26a20a63e54733b9203010-1482477017-604800; __cfduid=d0f0ef18f64d30cf54f8f6429ae821f161482477012
```

So, your tool works fine.

However once I load those into php and make a query it fails:

```
<?php

# Get params and urlencode them
$name           = urlencode($_GET['league']);
$name           = urlencode($_GET['name']);
#[...]
$queryString='league=' . $league . '&name=' . $name . ';

$ua = file_get_contents("./cf_ua.txt");
$cookie = file_get_contents("./cf_cookie.txt");
# If ua or cookie are empty, run pythong CF scraper
if ( $ua == '' || $cookie == '' ) {
        exec("./cloudflare.py");
        $ua = file_get_contents("./cf_ua.txt");
        $cookie = file_get_contents("./cf_cookie.txt");
        echo "$ua - $cookie";
} else {
        echo "$ua - $cookie";
}

$url = "http://poe.trade/search";
$ch = curl_init();
$timeout = 10;
curl_setopt($ch,CURLOPT_URL,$url);
curl_setopt($ch,CURLOPT_REFERER, 'http://poe.trade');
curl_setopt($ch,CURLOPT_RETURNTRANSFER,1);
curl_setopt($ch,CURLOPT_CONNECTTIMEOUT,$timeout);
curl_setopt($ch,CURLOPT_FOLLOWLOCATION, TRUE);
curl_setopt($ch,CURLOPT_COOKIEFILE, "./cf_cookie.txt");
curl_setopt($ch,CURLOPT_USERAGENT, "$ua");
curl_setopt($ch,CURLOPT_POST, 1);
curl_setopt($ch,CURLOPT_POSTFIELDS, $queryString);
$data = curl_exec($ch);
echo "--$data--"; exit;
$finalURL=curl_getinfo($ch,CURLINFO_EFFECTIVE_URL);
curl_close($ch);
```

However the php issued curl query does provoke the cf protection screen. I also tried to use

```
curl_setopt($ch,CURLOPT_COOKIE, "$cookie");
```

But same result.

In your script you say that cookie and same UA are important. That's why I safe them from the python script and read them out in PHP. So it should work IMHO.

Do you have any idea?

**Comment by sjau** [comment]
Hmmmm, it works fine when I use curl in bash and read out the values....

**Comment by Anorov** [comment]
It should work. If you keep debugging, just make sure the cookie and user-agent header values are what you expect them to be.

**Comment by Bobselp** [comment]
Sorry to dig out this old issue that's only slightly related to the repo itself - @sjau, did you ever found out what's causing this? I'm currently running into the same problems - CLI curl works fine, PHP curl doesn't. I compared the outgoing requests ("curl -v" vs CURLINFO_HEADER_OUT output in PHP), the request looks exactly identical, cookie string and UA - yet CF rejects the request from PHP.

If you ever found a way around this, I'd be happy if you would share it :)
