### ISSUE TITLE
get_tokens does not contain cf_clearance

### ISSUE THREAD

**Issue by KristianSv** [Anorov/cloudflare-scrape#92]
Hi Anorov. First thanks for the contribution. Amazing job.

   `session = cfscrape.create_scraper()`
   `tokens = session.get_tokens("https://website.com")`

When i read 'tokens', it contains `__cfduid` and `useragent` as expected, but `cf_clearance` is empty.

Could this be, due to an update?

**Comment by Anorov** [comment]
Please follow this format: https://github.com/Anorov/cloudflare-scrape#updates

There is no Cloudflare update that I know of; everything still seems to be working ok. This could suggest the website either doesn't have IUAM ("I Am Under Attack Mode") enabled, or the script is having issues with the site for unknown reasons. Note that there won't be a `cf_clearance` cookie if the site is running Cloudflare in a security level below IUAM.

**Comment by KristianSv** [comment]
Hi again Anorov.

I do get `cf_clearance` when making the request in Chrome, and capture it in Postman.
So it's only through python I don't recieve it.

Here's the source code for the website I'm trying to access:
http://pastebin.com/tRZqbE0r

**Comment by Anorov** [comment]
When I visit https://opskins.com in my browser, I'm not presented with an IUAM screen.

**Comment by KristianSv** [comment]
The IUAM screen is presented when trying to search for items, or simply going to the login screen (click the **Sign In / Register** button in the top right corner please).
