### ISSUE TITLE
"based on requests" ??

### ISSUE THREAD

**Issue by zen0x90** [Anorov/cloudflare-scrape#93]
So how to use a proxy ??

With requests you only need to use "proxy" keyword.

**Comment by zen0x90** [comment]
Also, you can't use `quote_plus` from requests library...

**Comment by Anorov** [comment]
It works fine with proxies.

```python
sess = cfscrape.create_scraper()
sess.proxies = {"http": "http://127.0.0.1:8080"}
sess.get("http://website.com")
```

Note that Cloudflare may captcha-block or completely block requests from proxies, though. That's not something a library could help with.
