### ISSUE TITLE
Support get args on get_cookie_string/get_token

### ISSUE THREAD

**Issue by SlyDave** [Anorov/cloudflare-scrape#94]
I'm trying to get this to work with Requests proxies, but have come to realise the call to get() in get_cookie_string->get_tokens doesn't pass in any additionally provided arguments, so it's a bit harder to use.

My current thinking is I need to duplicate much of get_cookie_string and get_token
````
proxies = {
  'http': 'http://proxy:1234',
}
scraper = cfscrape.create_scraper()
resp = scraper.get(url, proxies=proxies)
#--- duplicate content of get_cookie_string/get_token
````

Where as I would like to do:
````
scraper = cfscrape.create_scraper()
cookie_arg, user_agent = scraper.get_cookie_string(url, useragent, proxies=proxies)
````

Equally I could be doing this utterly wrong, Python isn't my primary language, but it is growing on me...

**Comment by Anorov** [comment]
Since this is just to get the clearance cookies, do you think it would be acceptable if I just allowed this:

    cookie_arg, user_agent = cfscrape.get_cookie_string(url, useragent, proxies=proxies)

**Comment by Anorov** [comment]
I just pushed an update; please tell me if this works for you.

**Comment by SlyDave** [comment]
Excellent! works perfectly. Thanks for the quick response.
