### ISSUE TITLE
Newer versions will not allow execution from php

### ISSUE THREAD

**Issue by Wicloz** [Anorov/cloudflare-scrape#98]
When running the following script from php with the `exec()` function or one of it's alternatives, execution stops at the line which uses `cfscrape`, as apparent from the fact that only `mark1` is printed. This only occurs if said php is executed by loading a page. If the php is executed from a terminal it works fine.
Moreover, this is only observed on version 1.8.0. It works fine on version 1.6.8 and 1.7.1 (those are the only versions I tested, but it will probably work on version 1.6.6 - 1.7.1 and not beyond that)

```
import cfscrape
import sys
import json

if __name__ == "__main__":
  print('mark1')
  cookie_arg, user_agent = cfscrape.get_cookie_string(sys.argv[1])
  print('mark2')
  print(json.dumps({'cookies': cookie_arg, 'agent': user_agent}))
```

**Comment by Coriou** [comment]
And what's the error ? Most likely it's because you need to have use Node's JS engine, and have it in your path for the user running PHP (this is why it works while using CLI, but not through HTTP)

**Comment by Anorov** [comment]
Closing due to lack of information.
